// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul 15 14:16:59 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 191395
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0735708028078,3.29995322227]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.38928887248,4.99817085266]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400014162064,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00442243833095,5.99961948395]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400007665157,3.19892525673]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [6.74796683597e-05,3.14159226418]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00372505188,99.9998550415]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.2057132721,699.396728516]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.991043091]
MT2                           MT2                           MT2                           MT2                                                             'F'    [22.3099918365,399.925476074]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.150757178664,299.963409424]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.224551962713911;
   fWeightMatrix0to1[1][0] = 1.10562581597655;
   fWeightMatrix0to1[2][0] = -0.014980848988052;
   fWeightMatrix0to1[3][0] = 0.977212297075584;
   fWeightMatrix0to1[4][0] = -1.42919695319083;
   fWeightMatrix0to1[5][0] = -0.837356233247573;
   fWeightMatrix0to1[6][0] = -0.073298794599843;
   fWeightMatrix0to1[7][0] = 1.13582427295439;
   fWeightMatrix0to1[8][0] = -0.567654276026439;
   fWeightMatrix0to1[9][0] = -1.19391203605366;
   fWeightMatrix0to1[10][0] = -0.93145626541663;
   fWeightMatrix0to1[11][0] = 0.073231436089967;
   fWeightMatrix0to1[12][0] = -0.30035404462613;
   fWeightMatrix0to1[13][0] = -0.58484526437191;
   fWeightMatrix0to1[14][0] = -0.124011204450513;
   fWeightMatrix0to1[15][0] = 0.825869082011809;
   fWeightMatrix0to1[0][1] = 0.0223142290158288;
   fWeightMatrix0to1[1][1] = 0.613433656235458;
   fWeightMatrix0to1[2][1] = -2.091477256206;
   fWeightMatrix0to1[3][1] = 1.09442107952102;
   fWeightMatrix0to1[4][1] = -0.195591469636493;
   fWeightMatrix0to1[5][1] = -0.860643956774959;
   fWeightMatrix0to1[6][1] = 2.67659003116615;
   fWeightMatrix0to1[7][1] = 0.371067462874914;
   fWeightMatrix0to1[8][1] = -0.875934970421345;
   fWeightMatrix0to1[9][1] = -0.239818930861082;
   fWeightMatrix0to1[10][1] = 1.53107621356239;
   fWeightMatrix0to1[11][1] = -0.751965168796346;
   fWeightMatrix0to1[12][1] = -1.30376620330864;
   fWeightMatrix0to1[13][1] = -0.00647099724954184;
   fWeightMatrix0to1[14][1] = 0.781617674674168;
   fWeightMatrix0to1[15][1] = 1.45725294808512;
   fWeightMatrix0to1[0][2] = -0.227394093965893;
   fWeightMatrix0to1[1][2] = -0.307039052156846;
   fWeightMatrix0to1[2][2] = 0.596099153997379;
   fWeightMatrix0to1[3][2] = -0.531434964585195;
   fWeightMatrix0to1[4][2] = -1.07253791361493;
   fWeightMatrix0to1[5][2] = 1.67276724712229;
   fWeightMatrix0to1[6][2] = -0.673370056455141;
   fWeightMatrix0to1[7][2] = 0.64792180912263;
   fWeightMatrix0to1[8][2] = 1.26222225574069;
   fWeightMatrix0to1[9][2] = 0.68240353635172;
   fWeightMatrix0to1[10][2] = 1.45858215688716;
   fWeightMatrix0to1[11][2] = 0.221455690088106;
   fWeightMatrix0to1[12][2] = -0.338552317657002;
   fWeightMatrix0to1[13][2] = -0.8334152498687;
   fWeightMatrix0to1[14][2] = 0.77259423097459;
   fWeightMatrix0to1[15][2] = -0.247278116080479;
   fWeightMatrix0to1[0][3] = 1.48069119425601;
   fWeightMatrix0to1[1][3] = 0.857350857439529;
   fWeightMatrix0to1[2][3] = 0.998371294753746;
   fWeightMatrix0to1[3][3] = 1.11825978812632;
   fWeightMatrix0to1[4][3] = -1.37460922724441;
   fWeightMatrix0to1[5][3] = 1.3578927245241;
   fWeightMatrix0to1[6][3] = -1.0133172179967;
   fWeightMatrix0to1[7][3] = -1.05312043439396;
   fWeightMatrix0to1[8][3] = -1.06038061511832;
   fWeightMatrix0to1[9][3] = -1.29931435183737;
   fWeightMatrix0to1[10][3] = 1.26446894419115;
   fWeightMatrix0to1[11][3] = 0.514081717024492;
   fWeightMatrix0to1[12][3] = -1.29252106787686;
   fWeightMatrix0to1[13][3] = 0.744789729764175;
   fWeightMatrix0to1[14][3] = -0.1621869284057;
   fWeightMatrix0to1[15][3] = 0.403974365570009;
   fWeightMatrix0to1[0][4] = 1.52408856717226;
   fWeightMatrix0to1[1][4] = -0.237005572526842;
   fWeightMatrix0to1[2][4] = 0.113816745530489;
   fWeightMatrix0to1[3][4] = -1.15289295525882;
   fWeightMatrix0to1[4][4] = 0.659305535633071;
   fWeightMatrix0to1[5][4] = -0.21279251734088;
   fWeightMatrix0to1[6][4] = -0.126672582136907;
   fWeightMatrix0to1[7][4] = -1.78756874170957;
   fWeightMatrix0to1[8][4] = 0.605128506373442;
   fWeightMatrix0to1[9][4] = 0.694712882660852;
   fWeightMatrix0to1[10][4] = 0.654465943664205;
   fWeightMatrix0to1[11][4] = -0.366450773968171;
   fWeightMatrix0to1[12][4] = -1.07873510859271;
   fWeightMatrix0to1[13][4] = -0.864984303722158;
   fWeightMatrix0to1[14][4] = 0.677544115693763;
   fWeightMatrix0to1[15][4] = 0.131956466600727;
   fWeightMatrix0to1[0][5] = 0.660157521675579;
   fWeightMatrix0to1[1][5] = 0.427729756249531;
   fWeightMatrix0to1[2][5] = -0.452194573707153;
   fWeightMatrix0to1[3][5] = 0.171108439805773;
   fWeightMatrix0to1[4][5] = -0.368330574437801;
   fWeightMatrix0to1[5][5] = -0.708438978497863;
   fWeightMatrix0to1[6][5] = 0.59131514697503;
   fWeightMatrix0to1[7][5] = -0.325996138689644;
   fWeightMatrix0to1[8][5] = -1.1767749659094;
   fWeightMatrix0to1[9][5] = -0.478307714914653;
   fWeightMatrix0to1[10][5] = -0.91152497529552;
   fWeightMatrix0to1[11][5] = 0.636086236641302;
   fWeightMatrix0to1[12][5] = 1.31228934373559;
   fWeightMatrix0to1[13][5] = -0.358269814401198;
   fWeightMatrix0to1[14][5] = -0.598124602450996;
   fWeightMatrix0to1[15][5] = 0.643778409400857;
   fWeightMatrix0to1[0][6] = -0.609637651899817;
   fWeightMatrix0to1[1][6] = -1.46635554498993;
   fWeightMatrix0to1[2][6] = -0.482138584989007;
   fWeightMatrix0to1[3][6] = -0.206525749779985;
   fWeightMatrix0to1[4][6] = -1.09596985337814;
   fWeightMatrix0to1[5][6] = -0.944523955448639;
   fWeightMatrix0to1[6][6] = 0.234069923098196;
   fWeightMatrix0to1[7][6] = 0.903385574939639;
   fWeightMatrix0to1[8][6] = -0.341186130273641;
   fWeightMatrix0to1[9][6] = 1.43393041971206;
   fWeightMatrix0to1[10][6] = -0.494316936316354;
   fWeightMatrix0to1[11][6] = 0.180667287939121;
   fWeightMatrix0to1[12][6] = -0.253597207161518;
   fWeightMatrix0to1[13][6] = 0.255663897034622;
   fWeightMatrix0to1[14][6] = -1.28196673089592;
   fWeightMatrix0to1[15][6] = 0.33893354946389;
   fWeightMatrix0to1[0][7] = 1.10609920067604;
   fWeightMatrix0to1[1][7] = -0.510933820473528;
   fWeightMatrix0to1[2][7] = -2.94032789020339;
   fWeightMatrix0to1[3][7] = 0.626609697143541;
   fWeightMatrix0to1[4][7] = 0.475097216637825;
   fWeightMatrix0to1[5][7] = 0.0140207520233115;
   fWeightMatrix0to1[6][7] = 2.18681981752384;
   fWeightMatrix0to1[7][7] = -2.28337167655624;
   fWeightMatrix0to1[8][7] = -1.13547169378367;
   fWeightMatrix0to1[9][7] = 0.289207294773628;
   fWeightMatrix0to1[10][7] = -0.262520403974467;
   fWeightMatrix0to1[11][7] = 0.619499704405611;
   fWeightMatrix0to1[12][7] = 1.00124615465752;
   fWeightMatrix0to1[13][7] = -0.500657074644574;
   fWeightMatrix0to1[14][7] = -0.510514738863427;
   fWeightMatrix0to1[15][7] = 0.507462746742411;
   fWeightMatrix0to1[0][8] = -1.23076785858203;
   fWeightMatrix0to1[1][8] = 1.1530953704577;
   fWeightMatrix0to1[2][8] = -0.472547836292766;
   fWeightMatrix0to1[3][8] = -2.01324217827165;
   fWeightMatrix0to1[4][8] = 0.594554226657636;
   fWeightMatrix0to1[5][8] = -0.7245085083266;
   fWeightMatrix0to1[6][8] = 0.349558814940426;
   fWeightMatrix0to1[7][8] = 0.366644344581991;
   fWeightMatrix0to1[8][8] = 1.51882570937422;
   fWeightMatrix0to1[9][8] = -1.35926650847863;
   fWeightMatrix0to1[10][8] = 0.339436978640409;
   fWeightMatrix0to1[11][8] = 0.0105541219006553;
   fWeightMatrix0to1[12][8] = 0.725965393031655;
   fWeightMatrix0to1[13][8] = 0.139137976092438;
   fWeightMatrix0to1[14][8] = -1.32301952907392;
   fWeightMatrix0to1[15][8] = -0.132393207494106;
   fWeightMatrix0to1[0][9] = -0.926824099444204;
   fWeightMatrix0to1[1][9] = 0.961118025061901;
   fWeightMatrix0to1[2][9] = 1.35717344779913;
   fWeightMatrix0to1[3][9] = -1.19728405412543;
   fWeightMatrix0to1[4][9] = -0.340771061717159;
   fWeightMatrix0to1[5][9] = 0.693613115606116;
   fWeightMatrix0to1[6][9] = -1.46948338192236;
   fWeightMatrix0to1[7][9] = -0.375454697153141;
   fWeightMatrix0to1[8][9] = 1.8274786161865;
   fWeightMatrix0to1[9][9] = -0.729037925543674;
   fWeightMatrix0to1[10][9] = -0.630875359411551;
   fWeightMatrix0to1[11][9] = -0.512496497403977;
   fWeightMatrix0to1[12][9] = 0.849767831102976;
   fWeightMatrix0to1[13][9] = 0.289046175413074;
   fWeightMatrix0to1[14][9] = 0.780219679284082;
   fWeightMatrix0to1[15][9] = -1.24100840576582;
   fWeightMatrix0to1[0][10] = 1.8937945631301;
   fWeightMatrix0to1[1][10] = 0.769662703535693;
   fWeightMatrix0to1[2][10] = 0.165862350853286;
   fWeightMatrix0to1[3][10] = -0.235233318524928;
   fWeightMatrix0to1[4][10] = 0.938474405559712;
   fWeightMatrix0to1[5][10] = 0.342369097768472;
   fWeightMatrix0to1[6][10] = 0.116916902720877;
   fWeightMatrix0to1[7][10] = -0.253114977965924;
   fWeightMatrix0to1[8][10] = -0.778709012601421;
   fWeightMatrix0to1[9][10] = -0.566094848018333;
   fWeightMatrix0to1[10][10] = 1.61616634688336;
   fWeightMatrix0to1[11][10] = -0.127165204305449;
   fWeightMatrix0to1[12][10] = -0.559230880366084;
   fWeightMatrix0to1[13][10] = 1.0724669651353;
   fWeightMatrix0to1[14][10] = 1.62197325889134;
   fWeightMatrix0to1[15][10] = -1.3096585204184;
   fWeightMatrix0to1[0][11] = -0.845270856332779;
   fWeightMatrix0to1[1][11] = 0.769036965735615;
   fWeightMatrix0to1[2][11] = -2.19800516896479;
   fWeightMatrix0to1[3][11] = 0.211443642301993;
   fWeightMatrix0to1[4][11] = -1.61261647348533;
   fWeightMatrix0to1[5][11] = -0.780534666479631;
   fWeightMatrix0to1[6][11] = 2.02254282906853;
   fWeightMatrix0to1[7][11] = 0.662491829200691;
   fWeightMatrix0to1[8][11] = -0.728071320877249;
   fWeightMatrix0to1[9][11] = -0.139885046149526;
   fWeightMatrix0to1[10][11] = -0.0793575318267092;
   fWeightMatrix0to1[11][11] = 3.35030693231735;
   fWeightMatrix0to1[12][11] = -0.678746071460816;
   fWeightMatrix0to1[13][11] = 0.299549255997883;
   fWeightMatrix0to1[14][11] = -1.0060294707177;
   fWeightMatrix0to1[15][11] = 0.347709880563401;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.00867355197243918;
   fWeightMatrix1to2[0][1] = 0.0282916814524689;
   fWeightMatrix1to2[0][2] = 0.197521188116194;
   fWeightMatrix1to2[0][3] = -0.000837054212116645;
   fWeightMatrix1to2[0][4] = -0.00885059026583494;
   fWeightMatrix1to2[0][5] = 0.0172637763818337;
   fWeightMatrix1to2[0][6] = 0.200197792794937;
   fWeightMatrix1to2[0][7] = -0.0235030352421596;
   fWeightMatrix1to2[0][8] = -0.0103341693031124;
   fWeightMatrix1to2[0][9] = 0.0264177177057262;
   fWeightMatrix1to2[0][10] = -0.0111157691699967;
   fWeightMatrix1to2[0][11] = -0.883817529553978;
   fWeightMatrix1to2[0][12] = 0.000476881138236329;
   fWeightMatrix1to2[0][13] = 0.00610455459336357;
   fWeightMatrix1to2[0][14] = -0.0169716644262402;
   fWeightMatrix1to2[0][15] = -0.00131811508565795;
   fWeightMatrix1to2[0][16] = 0.862412013090296;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0982179269195;
   fMax_1[0][0] = 3.26685810089;
   fMin_1[1][0] = 0.0735708028078;
   fMax_1[1][0] = 3.29995322227;
   fMin_1[2][0] = 0.0735708028078;
   fMax_1[2][0] = 3.29995322227;
   fMin_1[0][1] = 0.396243304014;
   fMax_1[0][1] = 4.98819494247;
   fMin_1[1][1] = 0.38928887248;
   fMax_1[1][1] = 4.99817085266;
   fMin_1[2][1] = 0.38928887248;
   fMax_1[2][1] = 4.99817085266;
   fMin_1[0][2] = 0.40639847517;
   fMax_1[0][2] = 4.52669382095;
   fMin_1[1][2] = 0.400014162064;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400014162064;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.199371486902;
   fMax_1[0][3] = 5.64617824554;
   fMin_1[1][3] = 0.00442243833095;
   fMax_1[1][3] = 5.99961948395;
   fMin_1[2][3] = 0.00442243833095;
   fMax_1[2][3] = 5.99961948395;
   fMin_1[0][4] = 0.405622512102;
   fMax_1[0][4] = 3.09667754173;
   fMin_1[1][4] = 0.400007665157;
   fMax_1[1][4] = 3.19892525673;
   fMin_1[2][4] = 0.400007665157;
   fMax_1[2][4] = 3.19892525673;
   fMin_1[0][5] = 0.00980622135103;
   fMax_1[0][5] = 3.14103221893;
   fMin_1[1][5] = 6.74796683597e-05;
   fMax_1[1][5] = 3.14159226418;
   fMin_1[2][5] = 6.74796683597e-05;
   fMax_1[2][5] = 3.14159226418;
   fMin_1[0][6] = 5.08230638504;
   fMax_1[0][6] = 89.459236145;
   fMin_1[1][6] = 5.00372505188;
   fMax_1[1][6] = 99.9998550415;
   fMin_1[2][6] = 5.00372505188;
   fMax_1[2][6] = 99.9998550415;
   fMin_1[0][7] = 24.1363868713;
   fMax_1[0][7] = 697.120910645;
   fMin_1[1][7] = 22.2057132721;
   fMax_1[1][7] = 699.396728516;
   fMin_1[2][7] = 22.2057132721;
   fMax_1[2][7] = 699.396728516;
   fMin_1[0][8] = 0.102906107903;
   fMax_1[0][8] = 224.117172241;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.991043091;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.991043091;
   fMin_1[0][9] = 37.7909660339;
   fMax_1[0][9] = 376.829711914;
   fMin_1[1][9] = 22.3099918365;
   fMax_1[1][9] = 399.925476074;
   fMin_1[2][9] = 22.3099918365;
   fMax_1[2][9] = 399.925476074;
   fMin_1[0][10] = 1.8165872097;
   fMax_1[0][10] = 281.073822021;
   fMin_1[1][10] = 0.150757178664;
   fMax_1[1][10] = 299.963409424;
   fMin_1[2][10] = 0.150757178664;
   fMax_1[2][10] = 299.963409424;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
