// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 14:07:30 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 224300
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0717559531331,3.29995322227]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.373879045248,4.99817085266]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400081574917,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00442243833095,5.99961948395]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.40004247427,3.19991016388]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.66005920619e-05,3.14159226418]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00042486191,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0002632141,699.751220703]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.991043091]
MT2                           MT2                           MT2                           MT2                                                             'F'    [22.3099918365,399.925476074]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.326862245798,299.963409424]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.247996837182718;
   fWeightMatrix0to1[1][0] = -0.29150920893418;
   fWeightMatrix0to1[2][0] = 0.379382310653755;
   fWeightMatrix0to1[3][0] = 1.70279496618078;
   fWeightMatrix0to1[4][0] = -1.360714161041;
   fWeightMatrix0to1[5][0] = -1.15151952353116;
   fWeightMatrix0to1[6][0] = 1.05358108423667;
   fWeightMatrix0to1[7][0] = 1.80362170918028;
   fWeightMatrix0to1[8][0] = -1.07766277631686;
   fWeightMatrix0to1[9][0] = -0.0426229397690579;
   fWeightMatrix0to1[10][0] = -1.7514233005474;
   fWeightMatrix0to1[11][0] = -0.333548050128247;
   fWeightMatrix0to1[12][0] = -1.25866549511758;
   fWeightMatrix0to1[13][0] = -0.860790356675748;
   fWeightMatrix0to1[14][0] = -1.08890099440719;
   fWeightMatrix0to1[15][0] = 0.120796357197639;
   fWeightMatrix0to1[0][1] = -0.568212226901307;
   fWeightMatrix0to1[1][1] = 3.74540202974261;
   fWeightMatrix0to1[2][1] = -2.44043561778444;
   fWeightMatrix0to1[3][1] = 1.47333665732513;
   fWeightMatrix0to1[4][1] = -0.0463568197215738;
   fWeightMatrix0to1[5][1] = -1.36275824296911;
   fWeightMatrix0to1[6][1] = -3.1520356906487;
   fWeightMatrix0to1[7][1] = 0.0611887914326968;
   fWeightMatrix0to1[8][1] = -1.75994759355359;
   fWeightMatrix0to1[9][1] = -0.0202383398198863;
   fWeightMatrix0to1[10][1] = 0.603400415308368;
   fWeightMatrix0to1[11][1] = -1.39869458279828;
   fWeightMatrix0to1[12][1] = -1.82554550514241;
   fWeightMatrix0to1[13][1] = -0.0176291755723976;
   fWeightMatrix0to1[14][1] = 3.1053925945253;
   fWeightMatrix0to1[15][1] = 6.16082414813816;
   fWeightMatrix0to1[0][2] = -0.15817974028953;
   fWeightMatrix0to1[1][2] = 1.25727256200559;
   fWeightMatrix0to1[2][2] = 0.918882559378108;
   fWeightMatrix0to1[3][2] = -0.432973632856895;
   fWeightMatrix0to1[4][2] = -1.43351160497195;
   fWeightMatrix0to1[5][2] = 1.7071877659638;
   fWeightMatrix0to1[6][2] = 0.0233385986189338;
   fWeightMatrix0to1[7][2] = 0.924054352864691;
   fWeightMatrix0to1[8][2] = 0.630726134638865;
   fWeightMatrix0to1[9][2] = 0.602489574551235;
   fWeightMatrix0to1[10][2] = 1.58873033362002;
   fWeightMatrix0to1[11][2] = 0.42520944427224;
   fWeightMatrix0to1[12][2] = -0.269248995610999;
   fWeightMatrix0to1[13][2] = -1.35511426743542;
   fWeightMatrix0to1[14][2] = -0.065435304546942;
   fWeightMatrix0to1[15][2] = -0.335885306761041;
   fWeightMatrix0to1[0][3] = 1.43992630852145;
   fWeightMatrix0to1[1][3] = 2.07284516119495;
   fWeightMatrix0to1[2][3] = 0.267418806252271;
   fWeightMatrix0to1[3][3] = 1.40116507422939;
   fWeightMatrix0to1[4][3] = -1.83401396773732;
   fWeightMatrix0to1[5][3] = 1.038125940493;
   fWeightMatrix0to1[6][3] = 0.495874684594082;
   fWeightMatrix0to1[7][3] = -0.904435485468196;
   fWeightMatrix0to1[8][3] = -1.29984920992563;
   fWeightMatrix0to1[9][3] = -0.819989273274012;
   fWeightMatrix0to1[10][3] = 1.2510989068827;
   fWeightMatrix0to1[11][3] = 1.6196927090221;
   fWeightMatrix0to1[12][3] = -1.48813764065432;
   fWeightMatrix0to1[13][3] = 0.0524168040847993;
   fWeightMatrix0to1[14][3] = -0.47180592081835;
   fWeightMatrix0to1[15][3] = -1.36378933123903;
   fWeightMatrix0to1[0][4] = 2.04760697817715;
   fWeightMatrix0to1[1][4] = -0.501981397737736;
   fWeightMatrix0to1[2][4] = 0.552510878507939;
   fWeightMatrix0to1[3][4] = -1.3155135740064;
   fWeightMatrix0to1[4][4] = 0.200157185407078;
   fWeightMatrix0to1[5][4] = -0.250785808813427;
   fWeightMatrix0to1[6][4] = 0.260247245858651;
   fWeightMatrix0to1[7][4] = -1.46699566742182;
   fWeightMatrix0to1[8][4] = 0.376910533590532;
   fWeightMatrix0to1[9][4] = 0.843967220911335;
   fWeightMatrix0to1[10][4] = 1.5854715933062;
   fWeightMatrix0to1[11][4] = -0.787609282332105;
   fWeightMatrix0to1[12][4] = -1.60381122048938;
   fWeightMatrix0to1[13][4] = -1.67102445489805;
   fWeightMatrix0to1[14][4] = -0.257331521497106;
   fWeightMatrix0to1[15][4] = -0.388774772066041;
   fWeightMatrix0to1[0][5] = 1.81512191373122;
   fWeightMatrix0to1[1][5] = 0.488459982852801;
   fWeightMatrix0to1[2][5] = -0.0960862860472493;
   fWeightMatrix0to1[3][5] = -0.771575394838854;
   fWeightMatrix0to1[4][5] = -1.2322457978222;
   fWeightMatrix0to1[5][5] = -0.426234995749948;
   fWeightMatrix0to1[6][5] = -1.28734623757452;
   fWeightMatrix0to1[7][5] = -1.21696032197109;
   fWeightMatrix0to1[8][5] = -2.06335383273131;
   fWeightMatrix0to1[9][5] = -0.0713668306680326;
   fWeightMatrix0to1[10][5] = 0.0396348814684412;
   fWeightMatrix0to1[11][5] = -0.314319467254424;
   fWeightMatrix0to1[12][5] = 1.6856245211452;
   fWeightMatrix0to1[13][5] = -1.54973951445345;
   fWeightMatrix0to1[14][5] = 1.3130101419181;
   fWeightMatrix0to1[15][5] = 0.229378049690454;
   fWeightMatrix0to1[0][6] = -0.818282969826421;
   fWeightMatrix0to1[1][6] = -2.10524407364368;
   fWeightMatrix0to1[2][6] = -1.97024905608738;
   fWeightMatrix0to1[3][6] = -0.0489555830335519;
   fWeightMatrix0to1[4][6] = -1.38310524249454;
   fWeightMatrix0to1[5][6] = -1.72148092078956;
   fWeightMatrix0to1[6][6] = -0.132154782749719;
   fWeightMatrix0to1[7][6] = 1.59058045579462;
   fWeightMatrix0to1[8][6] = -1.57316367932392;
   fWeightMatrix0to1[9][6] = 1.89295948929359;
   fWeightMatrix0to1[10][6] = -0.972711726536102;
   fWeightMatrix0to1[11][6] = -2.59869372291388;
   fWeightMatrix0to1[12][6] = -0.463812624451904;
   fWeightMatrix0to1[13][6] = 0.370812109884526;
   fWeightMatrix0to1[14][6] = 0.0954920763851562;
   fWeightMatrix0to1[15][6] = 1.14022337408074;
   fWeightMatrix0to1[0][7] = 0.237796270329074;
   fWeightMatrix0to1[1][7] = -1.75760021615296;
   fWeightMatrix0to1[2][7] = -3.11500972276205;
   fWeightMatrix0to1[3][7] = 1.68589944539829;
   fWeightMatrix0to1[4][7] = 0.4987820805171;
   fWeightMatrix0to1[5][7] = -1.40466752971442;
   fWeightMatrix0to1[6][7] = 8.18158087049892;
   fWeightMatrix0to1[7][7] = -0.986130734526036;
   fWeightMatrix0to1[8][7] = -1.67017579348383;
   fWeightMatrix0to1[9][7] = 0.37034263212682;
   fWeightMatrix0to1[10][7] = -0.695042833191054;
   fWeightMatrix0to1[11][7] = 1.00589934456892;
   fWeightMatrix0to1[12][7] = 0.801059054994346;
   fWeightMatrix0to1[13][7] = -0.452699007738944;
   fWeightMatrix0to1[14][7] = -8.10403963150699;
   fWeightMatrix0to1[15][7] = 2.253472425948;
   fWeightMatrix0to1[0][8] = -1.47913501573612;
   fWeightMatrix0to1[1][8] = -1.3281555060836;
   fWeightMatrix0to1[2][8] = -1.19050238228902;
   fWeightMatrix0to1[3][8] = -1.82751889827102;
   fWeightMatrix0to1[4][8] = 1.35540246401666;
   fWeightMatrix0to1[5][8] = -1.73875955254755;
   fWeightMatrix0to1[6][8] = 0.790689424005701;
   fWeightMatrix0to1[7][8] = 1.03631857657318;
   fWeightMatrix0to1[8][8] = 1.24752171163214;
   fWeightMatrix0to1[9][8] = -4.1283460525965;
   fWeightMatrix0to1[10][8] = 0.595527962426323;
   fWeightMatrix0to1[11][8] = 1.26204050565843;
   fWeightMatrix0to1[12][8] = 1.73200960269482;
   fWeightMatrix0to1[13][8] = 1.0593858484839;
   fWeightMatrix0to1[14][8] = -0.802970878991368;
   fWeightMatrix0to1[15][8] = 0.747348967291069;
   fWeightMatrix0to1[0][9] = -1.34975229880525;
   fWeightMatrix0to1[1][9] = 2.71659477826414;
   fWeightMatrix0to1[2][9] = 4.82850404832786;
   fWeightMatrix0to1[3][9] = -0.61707579756723;
   fWeightMatrix0to1[4][9] = -0.609212144338505;
   fWeightMatrix0to1[5][9] = 0.176078447123953;
   fWeightMatrix0to1[6][9] = -6.46609937929862;
   fWeightMatrix0to1[7][9] = 0.678391678238715;
   fWeightMatrix0to1[8][9] = 1.8421889383967;
   fWeightMatrix0to1[9][9] = -0.555181140393503;
   fWeightMatrix0to1[10][9] = -0.640119332378333;
   fWeightMatrix0to1[11][9] = 0.499487782318483;
   fWeightMatrix0to1[12][9] = 1.0349233563618;
   fWeightMatrix0to1[13][9] = 0.508250609815573;
   fWeightMatrix0to1[14][9] = 6.38211153496251;
   fWeightMatrix0to1[15][9] = -2.65020987753399;
   fWeightMatrix0to1[0][10] = 1.61892352790587;
   fWeightMatrix0to1[1][10] = 3.02988147057489;
   fWeightMatrix0to1[2][10] = 0.149201766181908;
   fWeightMatrix0to1[3][10] = 0.197886796807675;
   fWeightMatrix0to1[4][10] = 0.693309162966169;
   fWeightMatrix0to1[5][10] = -0.141717309232707;
   fWeightMatrix0to1[6][10] = -2.54642430781421;
   fWeightMatrix0to1[7][10] = 1.17703603130115;
   fWeightMatrix0to1[8][10] = -0.66367880395249;
   fWeightMatrix0to1[9][10] = -0.409507595623183;
   fWeightMatrix0to1[10][10] = 1.9757395519327;
   fWeightMatrix0to1[11][10] = 0.454229106941876;
   fWeightMatrix0to1[12][10] = -0.265942272487774;
   fWeightMatrix0to1[13][10] = 1.46432249485107;
   fWeightMatrix0to1[14][10] = 2.51765038934586;
   fWeightMatrix0to1[15][10] = 0.578805395638504;
   fWeightMatrix0to1[0][11] = 0.508592442799509;
   fWeightMatrix0to1[1][11] = -2.96945921827543;
   fWeightMatrix0to1[2][11] = -2.87884810531525;
   fWeightMatrix0to1[3][11] = -1.44018780601327;
   fWeightMatrix0to1[4][11] = -1.79858193301946;
   fWeightMatrix0to1[5][11] = 1.04051729111805;
   fWeightMatrix0to1[6][11] = 5.23989257056763;
   fWeightMatrix0to1[7][11] = -1.87529914336007;
   fWeightMatrix0to1[8][11] = -0.192974455550154;
   fWeightMatrix0to1[9][11] = 1.18444146258265;
   fWeightMatrix0to1[10][11] = -0.0310642462186893;
   fWeightMatrix0to1[11][11] = 1.18848157450893;
   fWeightMatrix0to1[12][11] = -0.443026896028146;
   fWeightMatrix0to1[13][11] = -0.0650500845887267;
   fWeightMatrix0to1[14][11] = -5.20241526316628;
   fWeightMatrix0to1[15][11] = 6.23730571157316;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.00135726465812317;
   fWeightMatrix1to2[0][1] = -0.0375544983314663;
   fWeightMatrix1to2[0][2] = 0.0829241425142964;
   fWeightMatrix1to2[0][3] = 0.0014562219022014;
   fWeightMatrix1to2[0][4] = -0.00239189551877746;
   fWeightMatrix1to2[0][5] = -0.00563876495871497;
   fWeightMatrix1to2[0][6] = 4.92190277920914;
   fWeightMatrix1to2[0][7] = 0.0010346104207468;
   fWeightMatrix1to2[0][8] = 0.00472872095858843;
   fWeightMatrix1to2[0][9] = 0.0138471854534253;
   fWeightMatrix1to2[0][10] = -0.00587560591961032;
   fWeightMatrix1to2[0][11] = 0.0113424945762742;
   fWeightMatrix1to2[0][12] = 0.00111318667824312;
   fWeightMatrix1to2[0][13] = -0.00286701014924214;
   fWeightMatrix1to2[0][14] = 4.93077468661268;
   fWeightMatrix1to2[0][15] = 0.100892852499085;
   fWeightMatrix1to2[0][16] = -0.0516627620521937;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0717559531331;
   fMax_1[0][0] = 3.25879645348;
   fMin_1[1][0] = 0.0735708028078;
   fMax_1[1][0] = 3.29995322227;
   fMin_1[2][0] = 0.0717559531331;
   fMax_1[2][0] = 3.29995322227;
   fMin_1[0][1] = 0.395848423243;
   fMax_1[0][1] = 4.90018987656;
   fMin_1[1][1] = 0.373879045248;
   fMax_1[1][1] = 4.99817085266;
   fMin_1[2][1] = 0.373879045248;
   fMax_1[2][1] = 4.99817085266;
   fMin_1[0][2] = 0.42405718565;
   fMax_1[0][2] = 4.92102718353;
   fMin_1[1][2] = 0.400081574917;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400081574917;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.259432077408;
   fMax_1[0][3] = 5.75387620926;
   fMin_1[1][3] = 0.00442243833095;
   fMax_1[1][3] = 5.99961948395;
   fMin_1[2][3] = 0.00442243833095;
   fMax_1[2][3] = 5.99961948395;
   fMin_1[0][4] = 0.404076904058;
   fMax_1[0][4] = 3.1550784111;
   fMin_1[1][4] = 0.40004247427;
   fMax_1[1][4] = 3.19991016388;
   fMin_1[2][4] = 0.40004247427;
   fMax_1[2][4] = 3.19991016388;
   fMin_1[0][5] = 0.00109035370406;
   fMax_1[0][5] = 3.14151000977;
   fMin_1[1][5] = 1.66005920619e-05;
   fMax_1[1][5] = 3.14159226418;
   fMin_1[2][5] = 1.66005920619e-05;
   fMax_1[2][5] = 3.14159226418;
   fMin_1[0][6] = 5.09243822098;
   fMax_1[0][6] = 91.6413192749;
   fMin_1[1][6] = 5.00042486191;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00042486191;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.0064582825;
   fMax_1[0][7] = 691.564147949;
   fMin_1[1][7] = 22.0002632141;
   fMax_1[1][7] = 699.751220703;
   fMin_1[2][7] = 22.0002632141;
   fMax_1[2][7] = 699.751220703;
   fMin_1[0][8] = 0.0840331763029;
   fMax_1[0][8] = 248.512664795;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.991043091;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.991043091;
   fMin_1[0][9] = 53.6448020935;
   fMax_1[0][9] = 385.469360352;
   fMin_1[1][9] = 22.3099918365;
   fMax_1[1][9] = 399.925476074;
   fMin_1[2][9] = 22.3099918365;
   fMax_1[2][9] = 399.925476074;
   fMin_1[0][10] = 4.02555608749;
   fMax_1[0][10] = 299.664215088;
   fMin_1[1][10] = 0.326862245798;
   fMax_1[1][10] = 299.963409424;
   fMin_1[2][10] = 0.326862245798;
   fMax_1[2][10] = 299.963409424;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
