// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 11:03:06 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 224300
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0717559531331,3.29995322227]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.373879045248,4.99817085266]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400081574917,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00442243833095,5.99961948395]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.40004247427,3.19991016388]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.66005920619e-05,3.14159226418]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00042486191,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0002632141,699.751220703]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.991043091]
MT2                           MT2                           MT2                           MT2                                                             'F'    [22.3099918365,399.925476074]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.326862245798,299.963409424]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 0.99999988079071;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.768092208060191;
   fWeightMatrix0to1[1][0] = -0.549718537699627;
   fWeightMatrix0to1[2][0] = -0.705944483168631;
   fWeightMatrix0to1[3][0] = 0.640519406678207;
   fWeightMatrix0to1[4][0] = -1.31369950402666;
   fWeightMatrix0to1[5][0] = -0.342075374826809;
   fWeightMatrix0to1[6][0] = 0.546234231636723;
   fWeightMatrix0to1[7][0] = 0.768609059468005;
   fWeightMatrix0to1[8][0] = -0.543148769460143;
   fWeightMatrix0to1[9][0] = -1.02979753248158;
   fWeightMatrix0to1[10][0] = -0.81764017212277;
   fWeightMatrix0to1[11][0] = 0.188240052541862;
   fWeightMatrix0to1[12][0] = -0.554085871780996;
   fWeightMatrix0to1[13][0] = -0.526550913849737;
   fWeightMatrix0to1[14][0] = -0.999285735721033;
   fWeightMatrix0to1[15][0] = 0.99455556416983;
   fWeightMatrix0to1[0][1] = -0.741575494517822;
   fWeightMatrix0to1[1][1] = 1.74831643540608;
   fWeightMatrix0to1[2][1] = 0.852865198090292;
   fWeightMatrix0to1[3][1] = 0.890073918021175;
   fWeightMatrix0to1[4][1] = -0.192575633217669;
   fWeightMatrix0to1[5][1] = -0.761163471831452;
   fWeightMatrix0to1[6][1] = -0.984343772624449;
   fWeightMatrix0to1[7][1] = -0.220097723987977;
   fWeightMatrix0to1[8][1] = -0.760646669356977;
   fWeightMatrix0to1[9][1] = -0.0112460425982231;
   fWeightMatrix0to1[10][1] = 1.14864703097639;
   fWeightMatrix0to1[11][1] = -0.963500360542801;
   fWeightMatrix0to1[12][1] = -1.30481447079202;
   fWeightMatrix0to1[13][1] = 0.0671720374688965;
   fWeightMatrix0to1[14][1] = -1.0105047319362;
   fWeightMatrix0to1[15][1] = 3.20180053207845;
   fWeightMatrix0to1[0][2] = -0.0859885125659399;
   fWeightMatrix0to1[1][2] = -0.021552279778413;
   fWeightMatrix0to1[2][2] = 0.2342687311692;
   fWeightMatrix0to1[3][2] = -0.758874544831423;
   fWeightMatrix0to1[4][2] = -1.15793923603083;
   fWeightMatrix0to1[5][2] = 1.39348917976692;
   fWeightMatrix0to1[6][2] = -0.429002758929688;
   fWeightMatrix0to1[7][2] = 0.483994349433172;
   fWeightMatrix0to1[8][2] = 1.21528026320891;
   fWeightMatrix0to1[9][2] = 0.665899710822581;
   fWeightMatrix0to1[10][2] = 1.65506012320353;
   fWeightMatrix0to1[11][2] = 0.428584427043929;
   fWeightMatrix0to1[12][2] = -0.178079784657244;
   fWeightMatrix0to1[13][2] = -1.08912817577377;
   fWeightMatrix0to1[14][2] = -0.16840557695297;
   fWeightMatrix0to1[15][2] = 0.0797819108844127;
   fWeightMatrix0to1[0][3] = 1.40321342116801;
   fWeightMatrix0to1[1][3] = 1.23296022183903;
   fWeightMatrix0to1[2][3] = 0.935682646510523;
   fWeightMatrix0to1[3][3] = 0.777556391653347;
   fWeightMatrix0to1[4][3] = -1.51915549025731;
   fWeightMatrix0to1[5][3] = 1.21821970551162;
   fWeightMatrix0to1[6][3] = -0.9117411574667;
   fWeightMatrix0to1[7][3] = -1.18271153698492;
   fWeightMatrix0to1[8][3] = -1.02626231498387;
   fWeightMatrix0to1[9][3] = -1.33486095040305;
   fWeightMatrix0to1[10][3] = 1.39753546418095;
   fWeightMatrix0to1[11][3] = 0.591134455624848;
   fWeightMatrix0to1[12][3] = -0.977077019204665;
   fWeightMatrix0to1[13][3] = 0.564458710168784;
   fWeightMatrix0to1[14][3] = -0.227015383958176;
   fWeightMatrix0to1[15][3] = -0.342422696716672;
   fWeightMatrix0to1[0][4] = 0.872828626920344;
   fWeightMatrix0to1[1][4] = -0.555849945147752;
   fWeightMatrix0to1[2][4] = -0.149918304087074;
   fWeightMatrix0to1[3][4] = -1.13491000097616;
   fWeightMatrix0to1[4][4] = 0.558487650494938;
   fWeightMatrix0to1[5][4] = -0.0357253067702851;
   fWeightMatrix0to1[6][4] = 0.146226406732104;
   fWeightMatrix0to1[7][4] = -1.36637777460753;
   fWeightMatrix0to1[8][4] = 0.654828328411655;
   fWeightMatrix0to1[9][4] = 0.282073206081002;
   fWeightMatrix0to1[10][4] = 0.663723232886297;
   fWeightMatrix0to1[11][4] = -0.0420014262716858;
   fWeightMatrix0to1[12][4] = -0.279405826378684;
   fWeightMatrix0to1[13][4] = -0.850557647318656;
   fWeightMatrix0to1[14][4] = 0.172070734410396;
   fWeightMatrix0to1[15][4] = -0.0487280401622263;
   fWeightMatrix0to1[0][5] = 0.289960387470692;
   fWeightMatrix0to1[1][5] = 0.309736473107372;
   fWeightMatrix0to1[2][5] = 0.264018898735536;
   fWeightMatrix0to1[3][5] = 0.323570066390845;
   fWeightMatrix0to1[4][5] = -0.354956424313421;
   fWeightMatrix0to1[5][5] = -0.863398241569271;
   fWeightMatrix0to1[6][5] = -0.114433387366898;
   fWeightMatrix0to1[7][5] = 0.290299617886877;
   fWeightMatrix0to1[8][5] = -1.34919720469602;
   fWeightMatrix0to1[9][5] = -0.788550292761482;
   fWeightMatrix0to1[10][5] = -0.795665817289198;
   fWeightMatrix0to1[11][5] = -0.360835909761421;
   fWeightMatrix0to1[12][5] = 1.78114285762306;
   fWeightMatrix0to1[13][5] = -0.64832835503902;
   fWeightMatrix0to1[14][5] = 1.06475809831464;
   fWeightMatrix0to1[15][5] = -0.764036825296306;
   fWeightMatrix0to1[0][6] = -0.621611072393665;
   fWeightMatrix0to1[1][6] = -1.09012986782156;
   fWeightMatrix0to1[2][6] = -0.0393433935957862;
   fWeightMatrix0to1[3][6] = 1.04831624528785;
   fWeightMatrix0to1[4][6] = -1.05392250971253;
   fWeightMatrix0to1[5][6] = -1.02316263356814;
   fWeightMatrix0to1[6][6] = -0.258007043413329;
   fWeightMatrix0to1[7][6] = 0.556212838831963;
   fWeightMatrix0to1[8][6] = -0.356479733180665;
   fWeightMatrix0to1[9][6] = 1.31391510933494;
   fWeightMatrix0to1[10][6] = -0.526830639952036;
   fWeightMatrix0to1[11][6] = -0.373688422532536;
   fWeightMatrix0to1[12][6] = -0.0156521674402665;
   fWeightMatrix0to1[13][6] = 0.297132020912095;
   fWeightMatrix0to1[14][6] = -0.514511995215428;
   fWeightMatrix0to1[15][6] = 0.480797012046593;
   fWeightMatrix0to1[0][7] = 0.549924206932721;
   fWeightMatrix0to1[1][7] = -1.27483401073456;
   fWeightMatrix0to1[2][7] = -2.9381845742404;
   fWeightMatrix0to1[3][7] = 0.175302028099599;
   fWeightMatrix0to1[4][7] = 0.39106521513036;
   fWeightMatrix0to1[5][7] = -0.0321510710090256;
   fWeightMatrix0to1[6][7] = 2.97036198665587;
   fWeightMatrix0to1[7][7] = -2.53212522287676;
   fWeightMatrix0to1[8][7] = -1.05773537816913;
   fWeightMatrix0to1[9][7] = 0.00114773387392992;
   fWeightMatrix0to1[10][7] = -0.204450037341776;
   fWeightMatrix0to1[11][7] = 1.23574213644125;
   fWeightMatrix0to1[12][7] = 1.16807908057953;
   fWeightMatrix0to1[13][7] = -0.700306441766329;
   fWeightMatrix0to1[14][7] = -1.91317900227922;
   fWeightMatrix0to1[15][7] = 1.53026356269471;
   fWeightMatrix0to1[0][8] = -1.1888654626344;
   fWeightMatrix0to1[1][8] = -0.313746661924509;
   fWeightMatrix0to1[2][8] = -0.691592379499622;
   fWeightMatrix0to1[3][8] = -1.52770444792578;
   fWeightMatrix0to1[4][8] = 0.659977788163433;
   fWeightMatrix0to1[5][8] = -0.94966759607476;
   fWeightMatrix0to1[6][8] = 0.642077498216711;
   fWeightMatrix0to1[7][8] = -0.0161019873964263;
   fWeightMatrix0to1[8][8] = 0.708694972918313;
   fWeightMatrix0to1[9][8] = -0.605081566290446;
   fWeightMatrix0to1[10][8] = 0.0432203905523744;
   fWeightMatrix0to1[11][8] = 0.191299999344423;
   fWeightMatrix0to1[12][8] = 0.321296900334933;
   fWeightMatrix0to1[13][8] = -0.0624775393534533;
   fWeightMatrix0to1[14][8] = -0.594883694997565;
   fWeightMatrix0to1[15][8] = 0.688843920039032;
   fWeightMatrix0to1[0][9] = -1.60998232560049;
   fWeightMatrix0to1[1][9] = 2.35781826056567;
   fWeightMatrix0to1[2][9] = 5.1536731176367;
   fWeightMatrix0to1[3][9] = -1.35748668255675;
   fWeightMatrix0to1[4][9] = -0.488165532612003;
   fWeightMatrix0to1[5][9] = 0.877036485674092;
   fWeightMatrix0to1[6][9] = -5.38225547718891;
   fWeightMatrix0to1[7][9] = -0.657165962964688;
   fWeightMatrix0to1[8][9] = 1.80816749229295;
   fWeightMatrix0to1[9][9] = -0.633924072052008;
   fWeightMatrix0to1[10][9] = -0.535350723533389;
   fWeightMatrix0to1[11][9] = 0.0365604430004863;
   fWeightMatrix0to1[12][9] = 0.859897539421987;
   fWeightMatrix0to1[13][9] = -0.119743247414008;
   fWeightMatrix0to1[14][9] = 1.84651003318886;
   fWeightMatrix0to1[15][9] = -2.33493838304604;
   fWeightMatrix0to1[0][10] = 0.706349304660251;
   fWeightMatrix0to1[1][10] = 1.67779163641029;
   fWeightMatrix0to1[2][10] = 1.51292188784244;
   fWeightMatrix0to1[3][10] = -0.763454002250498;
   fWeightMatrix0to1[4][10] = 0.822251007449963;
   fWeightMatrix0to1[5][10] = 0.434883861245205;
   fWeightMatrix0to1[6][10] = -1.5812846307183;
   fWeightMatrix0to1[7][10] = -0.386650951223342;
   fWeightMatrix0to1[8][10] = -0.584882507954145;
   fWeightMatrix0to1[9][10] = -0.850255567792427;
   fWeightMatrix0to1[10][10] = 2.07368411892814;
   fWeightMatrix0to1[11][10] = 0.115537899038656;
   fWeightMatrix0to1[12][10] = -0.32604482100597;
   fWeightMatrix0to1[13][10] = 0.687498975221524;
   fWeightMatrix0to1[14][10] = 0.800758325155681;
   fWeightMatrix0to1[15][10] = -0.638669852720736;
   fWeightMatrix0to1[0][11] = -3.06072966031684;
   fWeightMatrix0to1[1][11] = -1.67479240317986;
   fWeightMatrix0to1[2][11] = -1.46564332591426;
   fWeightMatrix0to1[3][11] = 1.76893506543832;
   fWeightMatrix0to1[4][11] = -1.37873808802069;
   fWeightMatrix0to1[5][11] = -0.504857974203334;
   fWeightMatrix0to1[6][11] = 1.53373617604727;
   fWeightMatrix0to1[7][11] = 1.44155185187358;
   fWeightMatrix0to1[8][11] = -0.679213038349756;
   fWeightMatrix0to1[9][11] = 0.219329990762657;
   fWeightMatrix0to1[10][11] = -0.870487379631618;
   fWeightMatrix0to1[11][11] = 0.618875247656435;
   fWeightMatrix0to1[12][11] = -0.927892376680048;
   fWeightMatrix0to1[13][11] = 0.46497816881157;
   fWeightMatrix0to1[14][11] = -3.97554906075075;
   fWeightMatrix0to1[15][11] = 4.97703148211882;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.164934452504443;
   fWeightMatrix1to2[0][1] = -0.112675324639392;
   fWeightMatrix1to2[0][2] = 0.661298236909683;
   fWeightMatrix1to2[0][3] = 0.0631841787827378;
   fWeightMatrix1to2[0][4] = -0.000478510369404898;
   fWeightMatrix1to2[0][5] = 0.0303301467014706;
   fWeightMatrix1to2[0][6] = 0.624654731546171;
   fWeightMatrix1to2[0][7] = -0.069765289627159;
   fWeightMatrix1to2[0][8] = 0.000786093332478003;
   fWeightMatrix1to2[0][9] = -0.0101769805160324;
   fWeightMatrix1to2[0][10] = -0.020779637023443;
   fWeightMatrix1to2[0][11] = 0.000546644208939932;
   fWeightMatrix1to2[0][12] = -0.0152831793600638;
   fWeightMatrix1to2[0][13] = -0.00234703908502795;
   fWeightMatrix1to2[0][14] = 0.636917748010315;
   fWeightMatrix1to2[0][15] = 0.501471264636426;
   fWeightMatrix1to2[0][16] = -0.0911732506059422;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0717559531331;
   fMax_1[0][0] = 3.25879645348;
   fMin_1[1][0] = 0.0735708028078;
   fMax_1[1][0] = 3.29995322227;
   fMin_1[2][0] = 0.0717559531331;
   fMax_1[2][0] = 3.29995322227;
   fMin_1[0][1] = 0.395848423243;
   fMax_1[0][1] = 4.90018987656;
   fMin_1[1][1] = 0.373879045248;
   fMax_1[1][1] = 4.99817085266;
   fMin_1[2][1] = 0.373879045248;
   fMax_1[2][1] = 4.99817085266;
   fMin_1[0][2] = 0.42405718565;
   fMax_1[0][2] = 4.92102718353;
   fMin_1[1][2] = 0.400081574917;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400081574917;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.259432077408;
   fMax_1[0][3] = 5.75387620926;
   fMin_1[1][3] = 0.00442243833095;
   fMax_1[1][3] = 5.99961948395;
   fMin_1[2][3] = 0.00442243833095;
   fMax_1[2][3] = 5.99961948395;
   fMin_1[0][4] = 0.404076904058;
   fMax_1[0][4] = 3.1550784111;
   fMin_1[1][4] = 0.40004247427;
   fMax_1[1][4] = 3.19991016388;
   fMin_1[2][4] = 0.40004247427;
   fMax_1[2][4] = 3.19991016388;
   fMin_1[0][5] = 0.00109035370406;
   fMax_1[0][5] = 3.14151000977;
   fMin_1[1][5] = 1.66005920619e-05;
   fMax_1[1][5] = 3.14159226418;
   fMin_1[2][5] = 1.66005920619e-05;
   fMax_1[2][5] = 3.14159226418;
   fMin_1[0][6] = 5.09243822098;
   fMax_1[0][6] = 91.6413192749;
   fMin_1[1][6] = 5.00042486191;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00042486191;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.0064582825;
   fMax_1[0][7] = 691.564147949;
   fMin_1[1][7] = 22.0002632141;
   fMax_1[1][7] = 699.751220703;
   fMin_1[2][7] = 22.0002632141;
   fMax_1[2][7] = 699.751220703;
   fMin_1[0][8] = 0.0840331763029;
   fMax_1[0][8] = 248.512664795;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.991043091;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.991043091;
   fMin_1[0][9] = 53.6448020935;
   fMax_1[0][9] = 385.469360352;
   fMin_1[1][9] = 22.3099918365;
   fMax_1[1][9] = 399.925476074;
   fMin_1[2][9] = 22.3099918365;
   fMax_1[2][9] = 399.925476074;
   fMin_1[0][10] = 4.02555608749;
   fMax_1[0][10] = 299.664215088;
   fMin_1[1][10] = 0.326862245798;
   fMax_1[1][10] = 299.963409424;
   fMin_1[2][10] = 0.326862245798;
   fMax_1[2][10] = 299.963409424;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
