rm -rf slurm/*err
rm -rf slurm/*out
rm -rf parametersconfig_B1PU.txt_*
rm -rf parametersconfig_B3.txt_*
rm -rf parametersconfig_B2PU.txt_*
rm -rf parametersconfig_B3PU.txt_*
rm -rf parametersconfig_B4PU.txt_*
rm -rf parametersconfig_B5PU.txt_*
rm -rf parametersconfig_B6.txt_*
rm -rf parametersconfig_B6PU.txt_*
rm -rf parametersconfig_B7PU.txt_*
rm -rf parametersconfig_B8PU.txt_*
rm -rf parametersconfig_B9PU.txt_*
rm -rf parametersconfig_B10PU.txt_*
rm -rf parametersconfig_B11PU.txt_*
rm -rf parametersconfig_B12PU.txt_*
rm -rf parametersconfig_tt.txt_*
rm -rf parametersconfig_ttPU.txt_*
