rm -rf slurm/*err
rm -rf slurm/*out
rm -rf parametersconfig_B3.txt_*
rm -rf parametersconfig_B2PU.txt_*
rm -rf parametersconfig_B3PU.txt_*
rm -rf parametersconfig_B6.txt_*
rm -rf parametersconfig_B6PU.txt_*
rm -rf parametersconfig_B12PU.txt_*
rm -rf parametersconfig_tt.txt_*
rm -rf parametersconfig_ttPU.txt_*
