// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 14:14:25 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 223681
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0704743787646,3.29987287521]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.375657469034,4.99443387985]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400089144707,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00762077886611,5.97856473923]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400001376867,3.19950509071]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.76370463123e-06,3.1415810585]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00751638412,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0002632141,699.751220703]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.994110107]
MT2                           MT2                           MT2                           MT2                                                             'F'    [24.572063446,399.860321045]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.382993191481,299.960723877]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.198702220707292;
   fWeightMatrix0to1[1][0] = 0.00537668866808935;
   fWeightMatrix0to1[2][0] = 1.59421516944749;
   fWeightMatrix0to1[3][0] = 1.66807845335494;
   fWeightMatrix0to1[4][0] = -1.43183531179496;
   fWeightMatrix0to1[5][0] = -1.35964900074599;
   fWeightMatrix0to1[6][0] = 1.73551303968344;
   fWeightMatrix0to1[7][0] = 1.76592996881997;
   fWeightMatrix0to1[8][0] = -1.5037885848837;
   fWeightMatrix0to1[9][0] = -2.37570170584449;
   fWeightMatrix0to1[10][0] = -1.16596520889664;
   fWeightMatrix0to1[11][0] = -0.730123512945047;
   fWeightMatrix0to1[12][0] = -1.58066288375799;
   fWeightMatrix0to1[13][0] = -0.708065966857881;
   fWeightMatrix0to1[14][0] = -0.259473312764689;
   fWeightMatrix0to1[15][0] = 0.677647367127993;
   fWeightMatrix0to1[0][1] = -0.468797393479074;
   fWeightMatrix0to1[1][1] = 1.87397721748838;
   fWeightMatrix0to1[2][1] = 0.405749551692016;
   fWeightMatrix0to1[3][1] = 1.42171172024535;
   fWeightMatrix0to1[4][1] = -0.865387537085782;
   fWeightMatrix0to1[5][1] = -0.0718660046149798;
   fWeightMatrix0to1[6][1] = -1.51671096246464;
   fWeightMatrix0to1[7][1] = 0.0555961233860111;
   fWeightMatrix0to1[8][1] = -1.1581227368563;
   fWeightMatrix0to1[9][1] = 0.306280907070296;
   fWeightMatrix0to1[10][1] = 1.35934589934961;
   fWeightMatrix0to1[11][1] = -1.71333281188246;
   fWeightMatrix0to1[12][1] = -1.23887280722774;
   fWeightMatrix0to1[13][1] = 0.189775382906778;
   fWeightMatrix0to1[14][1] = 0.374119588288238;
   fWeightMatrix0to1[15][1] = 1.29095228376663;
   fWeightMatrix0to1[0][2] = -0.185108977788218;
   fWeightMatrix0to1[1][2] = 1.63589224293959;
   fWeightMatrix0to1[2][2] = 0.245812387794524;
   fWeightMatrix0to1[3][2] = -0.358058399777833;
   fWeightMatrix0to1[4][2] = -0.374833025794273;
   fWeightMatrix0to1[5][2] = 1.77726370468047;
   fWeightMatrix0to1[6][2] = 0.171216182806795;
   fWeightMatrix0to1[7][2] = 0.856213946160812;
   fWeightMatrix0to1[8][2] = 1.24057539749397;
   fWeightMatrix0to1[9][2] = 0.98000964339688;
   fWeightMatrix0to1[10][2] = 2.0694030025033;
   fWeightMatrix0to1[11][2] = 0.852505749622802;
   fWeightMatrix0to1[12][2] = 0.226629437835631;
   fWeightMatrix0to1[13][2] = -1.30091674398379;
   fWeightMatrix0to1[14][2] = 0.571645704611237;
   fWeightMatrix0to1[15][2] = 0.314325253440403;
   fWeightMatrix0to1[0][3] = 1.41925286184595;
   fWeightMatrix0to1[1][3] = 0.284587490486777;
   fWeightMatrix0to1[2][3] = 1.61985337222582;
   fWeightMatrix0to1[3][3] = 1.34846770339122;
   fWeightMatrix0to1[4][3] = -0.65331348248737;
   fWeightMatrix0to1[5][3] = 1.27328296095183;
   fWeightMatrix0to1[6][3] = 1.10152089636308;
   fWeightMatrix0to1[7][3] = -0.973217938599014;
   fWeightMatrix0to1[8][3] = -1.22678646643185;
   fWeightMatrix0to1[9][3] = -1.87839911601086;
   fWeightMatrix0to1[10][3] = 1.65957305218241;
   fWeightMatrix0to1[11][3] = 0.801483092624561;
   fWeightMatrix0to1[12][3] = -1.15450235825274;
   fWeightMatrix0to1[13][3] = 0.211013888226849;
   fWeightMatrix0to1[14][3] = -0.32984851740425;
   fWeightMatrix0to1[15][3] = 0.458677765107332;
   fWeightMatrix0to1[0][4] = 1.97272457019342;
   fWeightMatrix0to1[1][4] = -0.865530710789367;
   fWeightMatrix0to1[2][4] = -0.572926202900847;
   fWeightMatrix0to1[3][4] = -1.20551844383443;
   fWeightMatrix0to1[4][4] = 1.47402884547038;
   fWeightMatrix0to1[5][4] = -1.0137084086763;
   fWeightMatrix0to1[6][4] = -0.618634219363497;
   fWeightMatrix0to1[7][4] = -1.60022069525678;
   fWeightMatrix0to1[8][4] = 0.805886064264916;
   fWeightMatrix0to1[9][4] = 0.855400079029048;
   fWeightMatrix0to1[10][4] = 1.46543312619868;
   fWeightMatrix0to1[11][4] = -0.241495383146124;
   fWeightMatrix0to1[12][4] = -0.968522831603622;
   fWeightMatrix0to1[13][4] = -1.51654097500713;
   fWeightMatrix0to1[14][4] = -0.191280259356819;
   fWeightMatrix0to1[15][4] = 0.292208263762345;
   fWeightMatrix0to1[0][5] = 1.77116177555923;
   fWeightMatrix0to1[1][5] = 0.0984976754020905;
   fWeightMatrix0to1[2][5] = 0.727287533040209;
   fWeightMatrix0to1[3][5] = -0.781261750704017;
   fWeightMatrix0to1[4][5] = 0.270485449890346;
   fWeightMatrix0to1[5][5] = -0.710691126973259;
   fWeightMatrix0to1[6][5] = -0.688596871912033;
   fWeightMatrix0to1[7][5] = -1.23621995435252;
   fWeightMatrix0to1[8][5] = -1.54724237080737;
   fWeightMatrix0to1[9][5] = -1.59215161979872;
   fWeightMatrix0to1[10][5] = -0.518366053333532;
   fWeightMatrix0to1[11][5] = -0.152461226121364;
   fWeightMatrix0to1[12][5] = 2.33749746149002;
   fWeightMatrix0to1[13][5] = -1.84046107042227;
   fWeightMatrix0to1[14][5] = 0.597915856170135;
   fWeightMatrix0to1[15][5] = 1.24373861720037;
   fWeightMatrix0to1[0][6] = -0.9550981943679;
   fWeightMatrix0to1[1][6] = 0.0342048110880007;
   fWeightMatrix0to1[2][6] = -1.15616008624114;
   fWeightMatrix0to1[3][6] = 0.0473091593174596;
   fWeightMatrix0to1[4][6] = -0.986837070708462;
   fWeightMatrix0to1[5][6] = -2.27265774641247;
   fWeightMatrix0to1[6][6] = 0.463709257706731;
   fWeightMatrix0to1[7][6] = 1.58812724857771;
   fWeightMatrix0to1[8][6] = -1.21927427771805;
   fWeightMatrix0to1[9][6] = 0.498073855228475;
   fWeightMatrix0to1[10][6] = -0.6253346247737;
   fWeightMatrix0to1[11][6] = -0.591703139397992;
   fWeightMatrix0to1[12][6] = -0.129354697227988;
   fWeightMatrix0to1[13][6] = -0.0694447070218866;
   fWeightMatrix0to1[14][6] = -1.19452786258996;
   fWeightMatrix0to1[15][6] = 0.994966615485174;
   fWeightMatrix0to1[0][7] = 0.231688880919349;
   fWeightMatrix0to1[1][7] = -1.64003912541398;
   fWeightMatrix0to1[2][7] = -1.32482332522349;
   fWeightMatrix0to1[3][7] = 1.78787733258278;
   fWeightMatrix0to1[4][7] = 0.0212465881979471;
   fWeightMatrix0to1[5][7] = -0.501314668450137;
   fWeightMatrix0to1[6][7] = 5.94829106685601;
   fWeightMatrix0to1[7][7] = -1.16286972795803;
   fWeightMatrix0to1[8][7] = -1.46269495570457;
   fWeightMatrix0to1[9][7] = 0.509185726091655;
   fWeightMatrix0to1[10][7] = -0.24016600207494;
   fWeightMatrix0to1[11][7] = 0.879924378283405;
   fWeightMatrix0to1[12][7] = 1.34735325371352;
   fWeightMatrix0to1[13][7] = -0.0755121922145842;
   fWeightMatrix0to1[14][7] = -1.1674260736962;
   fWeightMatrix0to1[15][7] = -0.368821959797334;
   fWeightMatrix0to1[0][8] = -1.62354655872047;
   fWeightMatrix0to1[1][8] = -0.397291203310659;
   fWeightMatrix0to1[2][8] = 0.340525985407882;
   fWeightMatrix0to1[3][8] = -1.87422251350818;
   fWeightMatrix0to1[4][8] = -0.919907390124302;
   fWeightMatrix0to1[5][8] = -0.337316086670385;
   fWeightMatrix0to1[6][8] = 0.945117632995215;
   fWeightMatrix0to1[7][8] = 1.09149298983172;
   fWeightMatrix0to1[8][8] = 1.67595279565429;
   fWeightMatrix0to1[9][8] = -0.914730751262798;
   fWeightMatrix0to1[10][8] = -0.555482692881485;
   fWeightMatrix0to1[11][8] = 1.51899049569681;
   fWeightMatrix0to1[12][8] = 1.10678231578652;
   fWeightMatrix0to1[13][8] = 0.807312066616784;
   fWeightMatrix0to1[14][8] = -1.0739887452762;
   fWeightMatrix0to1[15][8] = 0.440696065450439;
   fWeightMatrix0to1[0][9] = -1.50907772465583;
   fWeightMatrix0to1[1][9] = 3.07510290735492;
   fWeightMatrix0to1[2][9] = 0.396009027314358;
   fWeightMatrix0to1[3][9] = -0.483208084615572;
   fWeightMatrix0to1[4][9] = -1.16184982248033;
   fWeightMatrix0to1[5][9] = -0.10905591503332;
   fWeightMatrix0to1[6][9] = -3.15779457769173;
   fWeightMatrix0to1[7][9] = 0.602535708453816;
   fWeightMatrix0to1[8][9] = 1.77253257162849;
   fWeightMatrix0to1[9][9] = -0.824110553118388;
   fWeightMatrix0to1[10][9] = -0.472716363426342;
   fWeightMatrix0to1[11][9] = 0.596237074828033;
   fWeightMatrix0to1[12][9] = 1.28424066003877;
   fWeightMatrix0to1[13][9] = 0.532317327729429;
   fWeightMatrix0to1[14][9] = 3.91056042867903;
   fWeightMatrix0to1[15][9] = -1.44175093945906;
   fWeightMatrix0to1[0][10] = 1.44667946752204;
   fWeightMatrix0to1[1][10] = 0.607109952048942;
   fWeightMatrix0to1[2][10] = 1.35776245475963;
   fWeightMatrix0to1[3][10] = 0.53566859232992;
   fWeightMatrix0to1[4][10] = 0.431223616103002;
   fWeightMatrix0to1[5][10] = -0.881698081543602;
   fWeightMatrix0to1[6][10] = -1.12668208302105;
   fWeightMatrix0to1[7][10] = 1.09395833760643;
   fWeightMatrix0to1[8][10] = -0.835906200238002;
   fWeightMatrix0to1[9][10] = -0.957378648594615;
   fWeightMatrix0to1[10][10] = 1.72883007155161;
   fWeightMatrix0to1[11][10] = 0.793631244884189;
   fWeightMatrix0to1[12][10] = -0.427026204872019;
   fWeightMatrix0to1[13][10] = 1.25596738492792;
   fWeightMatrix0to1[14][10] = 0.229417152231924;
   fWeightMatrix0to1[15][10] = -2.18843112303686;
   fWeightMatrix0to1[0][11] = 0.625135458691063;
   fWeightMatrix0to1[1][11] = -3.16844395121987;
   fWeightMatrix0to1[2][11] = 0.435262739973176;
   fWeightMatrix0to1[3][11] = -1.62874168352536;
   fWeightMatrix0to1[4][11] = -4.79173852008069;
   fWeightMatrix0to1[5][11] = 0.503902136656789;
   fWeightMatrix0to1[6][11] = 6.44851945921403;
   fWeightMatrix0to1[7][11] = -1.63622114797881;
   fWeightMatrix0to1[8][11] = -0.485905859716392;
   fWeightMatrix0to1[9][11] = -0.0486308089500921;
   fWeightMatrix0to1[10][11] = 0.15791787297022;
   fWeightMatrix0to1[11][11] = 1.86059540395337;
   fWeightMatrix0to1[12][11] = -0.320565126106439;
   fWeightMatrix0to1[13][11] = -0.325409018734542;
   fWeightMatrix0to1[14][11] = -2.23995607201729;
   fWeightMatrix0to1[15][11] = 1.34978543790625;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.000229279932765747;
   fWeightMatrix1to2[0][1] = -0.181632259791297;
   fWeightMatrix1to2[0][2] = -0.0115090597498683;
   fWeightMatrix1to2[0][3] = 0.00108584040172689;
   fWeightMatrix1to2[0][4] = -0.208974718532737;
   fWeightMatrix1to2[0][5] = 0.00549303683220837;
   fWeightMatrix1to2[0][6] = -0.372047095545994;
   fWeightMatrix1to2[0][7] = 0.00137119409793419;
   fWeightMatrix1to2[0][8] = -0.00185700724891398;
   fWeightMatrix1to2[0][9] = -0.00877102207320877;
   fWeightMatrix1to2[0][10] = 0.00467703790226622;
   fWeightMatrix1to2[0][11] = 0.002723401967926;
   fWeightMatrix1to2[0][12] = -0.00399140990554982;
   fWeightMatrix1to2[0][13] = -0.00279871726260537;
   fWeightMatrix1to2[0][14] = 0.165800019620358;
   fWeightMatrix1to2[0][15] = -0.00476292625151649;
   fWeightMatrix1to2[0][16] = 0.154566666462315;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0704743787646;
   fMax_1[0][0] = 3.28820085526;
   fMin_1[1][0] = 0.074289560318;
   fMax_1[1][0] = 3.29987287521;
   fMin_1[2][0] = 0.0704743787646;
   fMax_1[2][0] = 3.29987287521;
   fMin_1[0][1] = 0.391374766827;
   fMax_1[0][1] = 4.73231887817;
   fMin_1[1][1] = 0.375657469034;
   fMax_1[1][1] = 4.99443387985;
   fMin_1[2][1] = 0.375657469034;
   fMax_1[2][1] = 4.99443387985;
   fMin_1[0][2] = 0.561851322651;
   fMax_1[0][2] = 4.76327848434;
   fMin_1[1][2] = 0.400089144707;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400089144707;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.305736422539;
   fMax_1[0][3] = 5.5496301651;
   fMin_1[1][3] = 0.00762077886611;
   fMax_1[1][3] = 5.97856473923;
   fMin_1[2][3] = 0.00762077886611;
   fMax_1[2][3] = 5.97856473923;
   fMin_1[0][4] = 0.405655294657;
   fMax_1[0][4] = 3.19950509071;
   fMin_1[1][4] = 0.400001376867;
   fMax_1[1][4] = 3.19927811623;
   fMin_1[2][4] = 0.400001376867;
   fMax_1[2][4] = 3.19950509071;
   fMin_1[0][5] = 0.00367920775898;
   fMax_1[0][5] = 3.1411793232;
   fMin_1[1][5] = 1.76370463123e-06;
   fMax_1[1][5] = 3.1415810585;
   fMin_1[2][5] = 1.76370463123e-06;
   fMax_1[2][5] = 3.1415810585;
   fMin_1[0][6] = 5.03540611267;
   fMax_1[0][6] = 96.211151123;
   fMin_1[1][6] = 5.00751638412;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00751638412;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.8492965698;
   fMax_1[0][7] = 697.742614746;
   fMin_1[1][7] = 22.0002632141;
   fMax_1[1][7] = 699.751220703;
   fMin_1[2][7] = 22.0002632141;
   fMax_1[2][7] = 699.751220703;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 249.548706055;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.994110107;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.994110107;
   fMin_1[0][9] = 66.7935256958;
   fMax_1[0][9] = 399.860321045;
   fMin_1[1][9] = 24.572063446;
   fMax_1[1][9] = 399.678619385;
   fMin_1[2][9] = 24.572063446;
   fMax_1[2][9] = 399.860321045;
   fMin_1[0][10] = 4.15161895752;
   fMax_1[0][10] = 299.960723877;
   fMin_1[1][10] = 0.382993191481;
   fMax_1[1][10] = 299.8175354;
   fMin_1[2][10] = 0.382993191481;
   fMax_1[2][10] = 299.960723877;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
