// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 11:04:03 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 223681
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0704743787646,3.29987287521]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.375657469034,4.99443387985]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400089144707,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00762077886611,5.97856473923]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400001376867,3.19950509071]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.76370463123e-06,3.1415810585]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00751638412,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0002632141,699.751220703]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.994110107]
MT2                           MT2                           MT2                           MT2                                                             'F'    [24.572063446,399.860321045]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.382993191481,299.960723877]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.579221307648964;
   fWeightMatrix0to1[1][0] = -0.00633041373758645;
   fWeightMatrix0to1[2][0] = -0.527242463372796;
   fWeightMatrix0to1[3][0] = 1.07281430495973;
   fWeightMatrix0to1[4][0] = -1.56610419131232;
   fWeightMatrix0to1[5][0] = -0.878198798764957;
   fWeightMatrix0to1[6][0] = 1.76962887534428;
   fWeightMatrix0to1[7][0] = 1.01859965703752;
   fWeightMatrix0to1[8][0] = -0.847226649368494;
   fWeightMatrix0to1[9][0] = -1.09264556369329;
   fWeightMatrix0to1[10][0] = -1.13339033303735;
   fWeightMatrix0to1[11][0] = 0.2329365908458;
   fWeightMatrix0to1[12][0] = -0.727109537320954;
   fWeightMatrix0to1[13][0] = -0.519189110602994;
   fWeightMatrix0to1[14][0] = 0.42506487315771;
   fWeightMatrix0to1[15][0] = 0.613209211731213;
   fWeightMatrix0to1[0][1] = -0.731383207416868;
   fWeightMatrix0to1[1][1] = 1.42814680955397;
   fWeightMatrix0to1[2][1] = 0.414914187786333;
   fWeightMatrix0to1[3][1] = 1.42767040023487;
   fWeightMatrix0to1[4][1] = -0.462246697581031;
   fWeightMatrix0to1[5][1] = -0.48675380092278;
   fWeightMatrix0to1[6][1] = 0.130991038771672;
   fWeightMatrix0to1[7][1] = -0.344368806546316;
   fWeightMatrix0to1[8][1] = -0.864008958883379;
   fWeightMatrix0to1[9][1] = -0.183594106094872;
   fWeightMatrix0to1[10][1] = 1.25624558985341;
   fWeightMatrix0to1[11][1] = -0.962420367726369;
   fWeightMatrix0to1[12][1] = -1.52140483794439;
   fWeightMatrix0to1[13][1] = -0.0269744792301459;
   fWeightMatrix0to1[14][1] = 0.149222118690706;
   fWeightMatrix0to1[15][1] = 1.20951197838516;
   fWeightMatrix0to1[0][2] = -0.570386362871391;
   fWeightMatrix0to1[1][2] = 0.644869128958544;
   fWeightMatrix0to1[2][2] = 0.540694163852158;
   fWeightMatrix0to1[3][2] = 0.0152174594340454;
   fWeightMatrix0to1[4][2] = -1.14943496311991;
   fWeightMatrix0to1[5][2] = 1.51684707773214;
   fWeightMatrix0to1[6][2] = 0.151379281995883;
   fWeightMatrix0to1[7][2] = 0.64096259552374;
   fWeightMatrix0to1[8][2] = 1.37246342304653;
   fWeightMatrix0to1[9][2] = 0.747909265578598;
   fWeightMatrix0to1[10][2] = 1.62568536895385;
   fWeightMatrix0to1[11][2] = 0.26884193312327;
   fWeightMatrix0to1[12][2] = -0.174817619769879;
   fWeightMatrix0to1[13][2] = -1.26961684301213;
   fWeightMatrix0to1[14][2] = 0.143468878825831;
   fWeightMatrix0to1[15][2] = -0.488044171396524;
   fWeightMatrix0to1[0][3] = 1.15612755571581;
   fWeightMatrix0to1[1][3] = 0.642858396336347;
   fWeightMatrix0to1[2][3] = 0.811572147643172;
   fWeightMatrix0to1[3][3] = 1.57784125778439;
   fWeightMatrix0to1[4][3] = -1.4401931155149;
   fWeightMatrix0to1[5][3] = 1.2642351201193;
   fWeightMatrix0to1[6][3] = 0.330483856811407;
   fWeightMatrix0to1[7][3] = -1.17984704769786;
   fWeightMatrix0to1[8][3] = -0.962399335342624;
   fWeightMatrix0to1[9][3] = -1.79998501814423;
   fWeightMatrix0to1[10][3] = 1.49171436380634;
   fWeightMatrix0to1[11][3] = 0.535720031778091;
   fWeightMatrix0to1[12][3] = -1.38331196267385;
   fWeightMatrix0to1[13][3] = 0.284238102754784;
   fWeightMatrix0to1[14][3] = -0.199298686207153;
   fWeightMatrix0to1[15][3] = 0.217039122319347;
   fWeightMatrix0to1[0][4] = 1.74894129216653;
   fWeightMatrix0to1[1][4] = -0.102526261453611;
   fWeightMatrix0to1[2][4] = -0.0310583684246011;
   fWeightMatrix0to1[3][4] = -0.823412079713575;
   fWeightMatrix0to1[4][4] = 0.77524681165629;
   fWeightMatrix0to1[5][4] = -0.0165992929149373;
   fWeightMatrix0to1[6][4] = -0.438468567929773;
   fWeightMatrix0to1[7][4] = -1.69056889891198;
   fWeightMatrix0to1[8][4] = 0.926444629928868;
   fWeightMatrix0to1[9][4] = 0.297816840152792;
   fWeightMatrix0to1[10][4] = 1.19159632012249;
   fWeightMatrix0to1[11][4] = -0.584928271567192;
   fWeightMatrix0to1[12][4] = -1.31848879641064;
   fWeightMatrix0to1[13][4] = -1.68104597316808;
   fWeightMatrix0to1[14][4] = 0.761826933062309;
   fWeightMatrix0to1[15][4] = -0.165575584285311;
   fWeightMatrix0to1[0][5] = -0.417977444022819;
   fWeightMatrix0to1[1][5] = -0.210615028882491;
   fWeightMatrix0to1[2][5] = -0.180759111592418;
   fWeightMatrix0to1[3][5] = -0.50174183874649;
   fWeightMatrix0to1[4][5] = -0.516145688043198;
   fWeightMatrix0to1[5][5] = -0.722975839108048;
   fWeightMatrix0to1[6][5] = -0.53091136778821;
   fWeightMatrix0to1[7][5] = -0.238918134186484;
   fWeightMatrix0to1[8][5] = -1.47599067861211;
   fWeightMatrix0to1[9][5] = -1.03853462249098;
   fWeightMatrix0to1[10][5] = -0.964497573004213;
   fWeightMatrix0to1[11][5] = -0.474671336541197;
   fWeightMatrix0to1[12][5] = 1.42021787766448;
   fWeightMatrix0to1[13][5] = -0.6646876955424;
   fWeightMatrix0to1[14][5] = -0.205877855978867;
   fWeightMatrix0to1[15][5] = 1.06989073425431;
   fWeightMatrix0to1[0][6] = -1.04169326855556;
   fWeightMatrix0to1[1][6] = -0.167630495777978;
   fWeightMatrix0to1[2][6] = -1.02847718558832;
   fWeightMatrix0to1[3][6] = -0.369478947900433;
   fWeightMatrix0to1[4][6] = -1.34156803052257;
   fWeightMatrix0to1[5][6] = -1.69366546914713;
   fWeightMatrix0to1[6][6] = 0.482845096422148;
   fWeightMatrix0to1[7][6] = 1.19022752656469;
   fWeightMatrix0to1[8][6] = -0.834688352423676;
   fWeightMatrix0to1[9][6] = 1.63500554166444;
   fWeightMatrix0to1[10][6] = -0.603339308481174;
   fWeightMatrix0to1[11][6] = -0.0299021263806367;
   fWeightMatrix0to1[12][6] = -0.004499373505341;
   fWeightMatrix0to1[13][6] = 0.455453529788451;
   fWeightMatrix0to1[14][6] = -1.31702556729549;
   fWeightMatrix0to1[15][6] = 0.234946594799613;
   fWeightMatrix0to1[0][7] = 0.898535269601691;
   fWeightMatrix0to1[1][7] = -1.07611515426552;
   fWeightMatrix0to1[2][7] = -0.903119071043307;
   fWeightMatrix0to1[3][7] = 2.0229794898042;
   fWeightMatrix0to1[4][7] = 0.393600706235815;
   fWeightMatrix0to1[5][7] = 0.247820772340332;
   fWeightMatrix0to1[6][7] = 3.02156078610346;
   fWeightMatrix0to1[7][7] = -2.66434427044476;
   fWeightMatrix0to1[8][7] = -0.66360847208687;
   fWeightMatrix0to1[9][7] = -0.42449141603177;
   fWeightMatrix0to1[10][7] = 0.102279934234847;
   fWeightMatrix0to1[11][7] = 1.4399104636293;
   fWeightMatrix0to1[12][7] = 1.10613779538463;
   fWeightMatrix0to1[13][7] = -1.14126150483146;
   fWeightMatrix0to1[14][7] = 0.313030545750995;
   fWeightMatrix0to1[15][7] = -0.242716065859649;
   fWeightMatrix0to1[0][8] = -0.814557580483516;
   fWeightMatrix0to1[1][8] = -0.436934831256327;
   fWeightMatrix0to1[2][8] = -0.999501495900642;
   fWeightMatrix0to1[3][8] = -1.53292309304572;
   fWeightMatrix0to1[4][8] = 0.525152207783982;
   fWeightMatrix0to1[5][8] = -0.364172604762757;
   fWeightMatrix0to1[6][8] = 0.811323432410164;
   fWeightMatrix0to1[7][8] = 0.789793492445884;
   fWeightMatrix0to1[8][8] = 1.41898001375368;
   fWeightMatrix0to1[9][8] = -1.20785293817282;
   fWeightMatrix0to1[10][8] = 0.262359522517799;
   fWeightMatrix0to1[11][8] = 0.802952855999103;
   fWeightMatrix0to1[12][8] = 1.3105288571077;
   fWeightMatrix0to1[13][8] = -0.0240162846318396;
   fWeightMatrix0to1[14][8] = -0.800972051288543;
   fWeightMatrix0to1[15][8] = -0.221560982730269;
   fWeightMatrix0to1[0][9] = -1.07630629317365;
   fWeightMatrix0to1[1][9] = 1.87696649113016;
   fWeightMatrix0to1[2][9] = 2.75067980203026;
   fWeightMatrix0to1[3][9] = -0.132054643440692;
   fWeightMatrix0to1[4][9] = -0.233946265786493;
   fWeightMatrix0to1[5][9] = 0.620775411904213;
   fWeightMatrix0to1[6][9] = -3.2262201779748;
   fWeightMatrix0to1[7][9] = -0.340147519742834;
   fWeightMatrix0to1[8][9] = 2.11850815536012;
   fWeightMatrix0to1[9][9] = -0.965284395422244;
   fWeightMatrix0to1[10][9] = -0.367336248848969;
   fWeightMatrix0to1[11][9] = -0.0956452637343481;
   fWeightMatrix0to1[12][9] = 1.1989853982156;
   fWeightMatrix0to1[13][9] = -0.338755992426422;
   fWeightMatrix0to1[14][9] = 1.15468543034804;
   fWeightMatrix0to1[15][9] = -1.74660892428669;
   fWeightMatrix0to1[0][10] = 1.11437523106325;
   fWeightMatrix0to1[1][10] = 1.02241478552509;
   fWeightMatrix0to1[2][10] = 0.677483541252796;
   fWeightMatrix0to1[3][10] = 0.729368632487171;
   fWeightMatrix0to1[4][10] = 1.15683672674742;
   fWeightMatrix0to1[5][10] = 0.564397966430432;
   fWeightMatrix0to1[6][10] = -0.509998822248427;
   fWeightMatrix0to1[7][10] = -0.139914469279456;
   fWeightMatrix0to1[8][10] = -0.184244028526764;
   fWeightMatrix0to1[9][10] = -1.0009311231852;
   fWeightMatrix0to1[10][10] = 1.84564199103396;
   fWeightMatrix0to1[11][10] = 0.221626328798287;
   fWeightMatrix0to1[12][10] = -0.187762367666411;
   fWeightMatrix0to1[13][10] = 0.520254995966872;
   fWeightMatrix0to1[14][10] = 1.44039798800126;
   fWeightMatrix0to1[15][10] = -1.67183462442776;
   fWeightMatrix0to1[0][11] = -2.79861500020461;
   fWeightMatrix0to1[1][11] = -1.96507391413047;
   fWeightMatrix0to1[2][11] = -1.47939429636378;
   fWeightMatrix0to1[3][11] = -1.89182439076297;
   fWeightMatrix0to1[4][11] = -1.74365258796607;
   fWeightMatrix0to1[5][11] = -2.05529379801322;
   fWeightMatrix0to1[6][11] = 5.05976289273117;
   fWeightMatrix0to1[7][11] = 0.675899571100346;
   fWeightMatrix0to1[8][11] = -1.38901534669405;
   fWeightMatrix0to1[9][11] = 0.653023693435032;
   fWeightMatrix0to1[10][11] = -0.977332267570023;
   fWeightMatrix0to1[11][11] = 1.58654859637778;
   fWeightMatrix0to1[12][11] = -0.713285483737542;
   fWeightMatrix0to1[13][11] = 1.18335242133886;
   fWeightMatrix0to1[14][11] = -2.51082334942465;
   fWeightMatrix0to1[15][11] = 1.63658621889539;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.215285023628687;
   fWeightMatrix1to2[0][1] = -0.306388215081982;
   fWeightMatrix1to2[0][2] = 0.198385015343552;
   fWeightMatrix1to2[0][3] = 0.00516066026487587;
   fWeightMatrix1to2[0][4] = 0.000341708283165571;
   fWeightMatrix1to2[0][5] = -0.109178696099227;
   fWeightMatrix1to2[0][6] = -0.399745607532929;
   fWeightMatrix1to2[0][7] = 0.0108723416114553;
   fWeightMatrix1to2[0][8] = -0.00417834671592028;
   fWeightMatrix1to2[0][9] = 8.51688725245588e-05;
   fWeightMatrix1to2[0][10] = 0.0335934456293901;
   fWeightMatrix1to2[0][11] = 0.00163481920466589;
   fWeightMatrix1to2[0][12] = -0.000886523018382499;
   fWeightMatrix1to2[0][13] = -0.00536243715083148;
   fWeightMatrix1to2[0][14] = 0.346475951644922;
   fWeightMatrix1to2[0][15] = 0.0125463228493178;
   fWeightMatrix1to2[0][16] = 0.330042872739789;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0704743787646;
   fMax_1[0][0] = 3.28820085526;
   fMin_1[1][0] = 0.074289560318;
   fMax_1[1][0] = 3.29987287521;
   fMin_1[2][0] = 0.0704743787646;
   fMax_1[2][0] = 3.29987287521;
   fMin_1[0][1] = 0.391374766827;
   fMax_1[0][1] = 4.73231887817;
   fMin_1[1][1] = 0.375657469034;
   fMax_1[1][1] = 4.99443387985;
   fMin_1[2][1] = 0.375657469034;
   fMax_1[2][1] = 4.99443387985;
   fMin_1[0][2] = 0.561851322651;
   fMax_1[0][2] = 4.76327848434;
   fMin_1[1][2] = 0.400089144707;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400089144707;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.305736422539;
   fMax_1[0][3] = 5.5496301651;
   fMin_1[1][3] = 0.00762077886611;
   fMax_1[1][3] = 5.97856473923;
   fMin_1[2][3] = 0.00762077886611;
   fMax_1[2][3] = 5.97856473923;
   fMin_1[0][4] = 0.405655294657;
   fMax_1[0][4] = 3.19950509071;
   fMin_1[1][4] = 0.400001376867;
   fMax_1[1][4] = 3.19927811623;
   fMin_1[2][4] = 0.400001376867;
   fMax_1[2][4] = 3.19950509071;
   fMin_1[0][5] = 0.00367920775898;
   fMax_1[0][5] = 3.1411793232;
   fMin_1[1][5] = 1.76370463123e-06;
   fMax_1[1][5] = 3.1415810585;
   fMin_1[2][5] = 1.76370463123e-06;
   fMax_1[2][5] = 3.1415810585;
   fMin_1[0][6] = 5.03540611267;
   fMax_1[0][6] = 96.211151123;
   fMin_1[1][6] = 5.00751638412;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00751638412;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.8492965698;
   fMax_1[0][7] = 697.742614746;
   fMin_1[1][7] = 22.0002632141;
   fMax_1[1][7] = 699.751220703;
   fMin_1[2][7] = 22.0002632141;
   fMax_1[2][7] = 699.751220703;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 249.548706055;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.994110107;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.994110107;
   fMin_1[0][9] = 66.7935256958;
   fMax_1[0][9] = 399.860321045;
   fMin_1[1][9] = 24.572063446;
   fMax_1[1][9] = 399.678619385;
   fMin_1[2][9] = 24.572063446;
   fMax_1[2][9] = 399.860321045;
   fMin_1[0][10] = 4.15161895752;
   fMax_1[0][10] = 299.960723877;
   fMin_1[1][10] = 0.382993191481;
   fMax_1[1][10] = 299.8175354;
   fMin_1[2][10] = 0.382993191481;
   fMax_1[2][10] = 299.960723877;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
