// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 14:11:14 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 222534
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0706459358335,3.29995322227]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.378905236721,4.99817085266]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400014162064,4.99972915649]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00442243833095,5.99096441269]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400001376867,3.19991016388]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.76370463123e-06,3.14159226418]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00372505188,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.000579834,699.17364502]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.991043091]
MT2                           MT2                           MT2                           MT2                                                             'F'    [22.3099918365,399.818786621]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.32002851367,299.8175354]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.8451844516668;
   fWeightMatrix0to1[1][0] = 1.27158958515749;
   fWeightMatrix0to1[2][0] = 2.15670838146884;
   fWeightMatrix0to1[3][0] = 0.668636177829432;
   fWeightMatrix0to1[4][0] = -2.37520153753591;
   fWeightMatrix0to1[5][0] = 0.00946002236089642;
   fWeightMatrix0to1[6][0] = -0.773224061360133;
   fWeightMatrix0to1[7][0] = 2.43125187874129;
   fWeightMatrix0to1[8][0] = -1.5624350753469;
   fWeightMatrix0to1[9][0] = -0.858948349142413;
   fWeightMatrix0to1[10][0] = -3.16517833134444;
   fWeightMatrix0to1[11][0] = -0.517706292239981;
   fWeightMatrix0to1[12][0] = -0.942083189080005;
   fWeightMatrix0to1[13][0] = -1.64312071476309;
   fWeightMatrix0to1[14][0] = -0.910674842006926;
   fWeightMatrix0to1[15][0] = 0.390267048637681;
   fWeightMatrix0to1[0][1] = -2.28982594722031;
   fWeightMatrix0to1[1][1] = 1.98727029524629;
   fWeightMatrix0to1[2][1] = 2.29152164887259;
   fWeightMatrix0to1[3][1] = 1.33090364021675;
   fWeightMatrix0to1[4][1] = -0.875181940810796;
   fWeightMatrix0to1[5][1] = -1.66246828525001;
   fWeightMatrix0to1[6][1] = 0.395155590420003;
   fWeightMatrix0to1[7][1] = 0.32679900931019;
   fWeightMatrix0to1[8][1] = 0.671167018766238;
   fWeightMatrix0to1[9][1] = -2.12228380282234;
   fWeightMatrix0to1[10][1] = 2.90926259244287;
   fWeightMatrix0to1[11][1] = -1.46540167422202;
   fWeightMatrix0to1[12][1] = -3.35095288476599;
   fWeightMatrix0to1[13][1] = -0.730782991501366;
   fWeightMatrix0to1[14][1] = 1.28002114452131;
   fWeightMatrix0to1[15][1] = 0.987155995557905;
   fWeightMatrix0to1[0][2] = -0.621759110553616;
   fWeightMatrix0to1[1][2] = 0.152289551629477;
   fWeightMatrix0to1[2][2] = 5.68261802659316;
   fWeightMatrix0to1[3][2] = -0.101989538896217;
   fWeightMatrix0to1[4][2] = -1.66811868918898;
   fWeightMatrix0to1[5][2] = -0.0598406104923202;
   fWeightMatrix0to1[6][2] = -0.957302055301067;
   fWeightMatrix0to1[7][2] = 1.48277883464956;
   fWeightMatrix0to1[8][2] = 0.874765631795168;
   fWeightMatrix0to1[9][2] = 0.61789372402857;
   fWeightMatrix0to1[10][2] = 1.11441104069085;
   fWeightMatrix0to1[11][2] = 0.129790418062343;
   fWeightMatrix0to1[12][2] = 1.93324314660297;
   fWeightMatrix0to1[13][2] = -1.62050065360336;
   fWeightMatrix0to1[14][2] = 1.75642023955778;
   fWeightMatrix0to1[15][2] = 0.513452565883235;
   fWeightMatrix0to1[0][3] = 0.372353206544512;
   fWeightMatrix0to1[1][3] = 1.63773821072787;
   fWeightMatrix0to1[2][3] = 6.29411528897347;
   fWeightMatrix0to1[3][3] = -2.04150365658261;
   fWeightMatrix0to1[4][3] = -1.57720584327664;
   fWeightMatrix0to1[5][3] = -0.715911720667694;
   fWeightMatrix0to1[6][3] = -1.78679647774485;
   fWeightMatrix0to1[7][3] = 0.172324731837364;
   fWeightMatrix0to1[8][3] = -1.00686184462501;
   fWeightMatrix0to1[9][3] = -2.29677322006828;
   fWeightMatrix0to1[10][3] = 2.91691931529374;
   fWeightMatrix0to1[11][3] = 0.877241395433357;
   fWeightMatrix0to1[12][3] = 1.45636296995103;
   fWeightMatrix0to1[13][3] = -0.610167793587851;
   fWeightMatrix0to1[14][3] = -0.169535641857665;
   fWeightMatrix0to1[15][3] = 1.61021256565733;
   fWeightMatrix0to1[0][4] = 1.93103268250285;
   fWeightMatrix0to1[1][4] = -0.799776413198111;
   fWeightMatrix0to1[2][4] = 3.18800827493831;
   fWeightMatrix0to1[3][4] = -1.10704811768509;
   fWeightMatrix0to1[4][4] = 0.173431613418714;
   fWeightMatrix0to1[5][4] = -0.142786651866806;
   fWeightMatrix0to1[6][4] = -0.474180941945966;
   fWeightMatrix0to1[7][4] = -2.39835887949128;
   fWeightMatrix0to1[8][4] = 1.76260292507551;
   fWeightMatrix0to1[9][4] = 0.992473650876805;
   fWeightMatrix0to1[10][4] = 1.51376732029078;
   fWeightMatrix0to1[11][4] = 0.706092992944502;
   fWeightMatrix0to1[12][4] = 0.352435936951825;
   fWeightMatrix0to1[13][4] = -1.43569436811114;
   fWeightMatrix0to1[14][4] = 1.28233385674125;
   fWeightMatrix0to1[15][4] = 0.202289361459886;
   fWeightMatrix0to1[0][5] = 0.353158806579232;
   fWeightMatrix0to1[1][5] = -0.837250594778625;
   fWeightMatrix0to1[2][5] = 4.98829584994243;
   fWeightMatrix0to1[3][5] = 0.995438657657693;
   fWeightMatrix0to1[4][5] = -1.08402532971996;
   fWeightMatrix0to1[5][5] = -1.40942140682274;
   fWeightMatrix0to1[6][5] = 1.16634389921616;
   fWeightMatrix0to1[7][5] = -0.330910798320976;
   fWeightMatrix0to1[8][5] = -0.38641470581474;
   fWeightMatrix0to1[9][5] = -2.78358229765137;
   fWeightMatrix0to1[10][5] = 0.240671701227914;
   fWeightMatrix0to1[11][5] = -0.485946922468122;
   fWeightMatrix0to1[12][5] = 3.68246471898799;
   fWeightMatrix0to1[13][5] = -3.01731472246293;
   fWeightMatrix0to1[14][5] = -1.29622952215219;
   fWeightMatrix0to1[15][5] = 2.55845263581706;
   fWeightMatrix0to1[0][6] = -0.664430192818915;
   fWeightMatrix0to1[1][6] = -2.34033924733894;
   fWeightMatrix0to1[2][6] = -1.07118315652308;
   fWeightMatrix0to1[3][6] = -1.94297386770979;
   fWeightMatrix0to1[4][6] = -1.28190076136019;
   fWeightMatrix0to1[5][6] = -1.50325216162771;
   fWeightMatrix0to1[6][6] = 0.830452264750701;
   fWeightMatrix0to1[7][6] = 1.04557825373413;
   fWeightMatrix0to1[8][6] = -0.672463092318593;
   fWeightMatrix0to1[9][6] = 0.352146512528537;
   fWeightMatrix0to1[10][6] = -0.465970967434927;
   fWeightMatrix0to1[11][6] = 1.67093993203164;
   fWeightMatrix0to1[12][6] = 3.09401706895444;
   fWeightMatrix0to1[13][6] = -0.0403798508331349;
   fWeightMatrix0to1[14][6] = -2.24147168549815;
   fWeightMatrix0to1[15][6] = -0.133249065188725;
   fWeightMatrix0to1[0][7] = -1.04928864022194;
   fWeightMatrix0to1[1][7] = 1.41696863369388;
   fWeightMatrix0to1[2][7] = 4.19774118142221;
   fWeightMatrix0to1[3][7] = -1.70692054387088;
   fWeightMatrix0to1[4][7] = -0.287340159681474;
   fWeightMatrix0to1[5][7] = -1.59698619828821;
   fWeightMatrix0to1[6][7] = 0.342239300664324;
   fWeightMatrix0to1[7][7] = -1.50147154173265;
   fWeightMatrix0to1[8][7] = -1.70814560454221;
   fWeightMatrix0to1[9][7] = -0.411879149050548;
   fWeightMatrix0to1[10][7] = -1.30214758158798;
   fWeightMatrix0to1[11][7] = 3.32493497119081;
   fWeightMatrix0to1[12][7] = -1.99716391221849;
   fWeightMatrix0to1[13][7] = -0.996359078458057;
   fWeightMatrix0to1[14][7] = 0.200240594891402;
   fWeightMatrix0to1[15][7] = 0.167320758196216;
   fWeightMatrix0to1[0][8] = -2.70033206405532;
   fWeightMatrix0to1[1][8] = -0.798714451472799;
   fWeightMatrix0to1[2][8] = -0.509069846454635;
   fWeightMatrix0to1[3][8] = -1.99321008163715;
   fWeightMatrix0to1[4][8] = 0.46833128192112;
   fWeightMatrix0to1[5][8] = -5.0947999677574;
   fWeightMatrix0to1[6][8] = 0.119673508416249;
   fWeightMatrix0to1[7][8] = 2.12916336418547;
   fWeightMatrix0to1[8][8] = 4.56949597437744;
   fWeightMatrix0to1[9][8] = -2.55619230326352;
   fWeightMatrix0to1[10][8] = 0.708931922061388;
   fWeightMatrix0to1[11][8] = 0.239553837695252;
   fWeightMatrix0to1[12][8] = 3.55687104773376;
   fWeightMatrix0to1[13][8] = 0.239492502729206;
   fWeightMatrix0to1[14][8] = 0.665931279668176;
   fWeightMatrix0to1[15][8] = -0.369090359179434;
   fWeightMatrix0to1[0][9] = -1.42058240610804;
   fWeightMatrix0to1[1][9] = 1.15214995774647;
   fWeightMatrix0to1[2][9] = 6.07596274762359;
   fWeightMatrix0to1[3][9] = -3.9031163010804;
   fWeightMatrix0to1[4][9] = -0.310934327246647;
   fWeightMatrix0to1[5][9] = -1.00741915274471;
   fWeightMatrix0to1[6][9] = -1.61724707254956;
   fWeightMatrix0to1[7][9] = 0.638505594625052;
   fWeightMatrix0to1[8][9] = 1.13398092953473;
   fWeightMatrix0to1[9][9] = 0.488038469052307;
   fWeightMatrix0to1[10][9] = -0.318858212902937;
   fWeightMatrix0to1[11][9] = 4.60765399671627;
   fWeightMatrix0to1[12][9] = 2.02453397023939;
   fWeightMatrix0to1[13][9] = 0.162711535840583;
   fWeightMatrix0to1[14][9] = 1.33274603083614;
   fWeightMatrix0to1[15][9] = -0.636054537922433;
   fWeightMatrix0to1[0][10] = 1.57672781659361;
   fWeightMatrix0to1[1][10] = 0.823323593960393;
   fWeightMatrix0to1[2][10] = 3.83312201363943;
   fWeightMatrix0to1[3][10] = -2.08697152767554;
   fWeightMatrix0to1[4][10] = 1.03545792510819;
   fWeightMatrix0to1[5][10] = 0.0956998888372733;
   fWeightMatrix0to1[6][10] = -0.814824592016494;
   fWeightMatrix0to1[7][10] = -0.00906594111407995;
   fWeightMatrix0to1[8][10] = -2.59463920417569;
   fWeightMatrix0to1[9][10] = 0.269911464655829;
   fWeightMatrix0to1[10][10] = -0.580603265223055;
   fWeightMatrix0to1[11][10] = 1.86080477767413;
   fWeightMatrix0to1[12][10] = -2.32131720642352;
   fWeightMatrix0to1[13][10] = 0.67807825789464;
   fWeightMatrix0to1[14][10] = 1.61592122702293;
   fWeightMatrix0to1[15][10] = -1.88222023682379;
   fWeightMatrix0to1[0][11] = 0.884420736534417;
   fWeightMatrix0to1[1][11] = -1.10393559011381;
   fWeightMatrix0to1[2][11] = -7.03340526633653;
   fWeightMatrix0to1[3][11] = -10.0066184262156;
   fWeightMatrix0to1[4][11] = -1.19663576829295;
   fWeightMatrix0to1[5][11] = 0.674524368158353;
   fWeightMatrix0to1[6][11] = 1.88591395060703;
   fWeightMatrix0to1[7][11] = -0.94474690362424;
   fWeightMatrix0to1[8][11] = -0.339161181377186;
   fWeightMatrix0to1[9][11] = -2.60852304203596;
   fWeightMatrix0to1[10][11] = 0.0812092413386876;
   fWeightMatrix0to1[11][11] = 9.3033555549852;
   fWeightMatrix0to1[12][11] = 5.38363907135954;
   fWeightMatrix0to1[13][11] = -1.14543177837884;
   fWeightMatrix0to1[14][11] = -0.353220014446022;
   fWeightMatrix0to1[15][11] = 0.459032309213826;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.00142216620463627;
   fWeightMatrix1to2[0][1] = 0.00603041561850228;
   fWeightMatrix1to2[0][2] = -0.000473640276399193;
   fWeightMatrix1to2[0][3] = -0.286084331828221;
   fWeightMatrix1to2[0][4] = -0.00179365337413071;
   fWeightMatrix1to2[0][5] = 0.00027115565811127;
   fWeightMatrix1to2[0][6] = 0.00448308565125376;
   fWeightMatrix1to2[0][7] = -0.000481486741053745;
   fWeightMatrix1to2[0][8] = 0.00161599232666403;
   fWeightMatrix1to2[0][9] = 0.00243286487199585;
   fWeightMatrix1to2[0][10] = -0.000645552031582625;
   fWeightMatrix1to2[0][11] = -0.380172856785994;
   fWeightMatrix1to2[0][12] = -0.00103400388392585;
   fWeightMatrix1to2[0][13] = -0.00242296104663899;
   fWeightMatrix1to2[0][14] = 0.000523401635148474;
   fWeightMatrix1to2[0][15] = -0.00260184724155649;
   fWeightMatrix1to2[0][16] = 0.0974113173392967;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.124257586896;
   fMax_1[0][0] = 3.29416155815;
   fMin_1[1][0] = 0.0706459358335;
   fMax_1[1][0] = 3.29995322227;
   fMin_1[2][0] = 0.0706459358335;
   fMax_1[2][0] = 3.29995322227;
   fMin_1[0][1] = 0.433966368437;
   fMax_1[0][1] = 4.79502058029;
   fMin_1[1][1] = 0.378905236721;
   fMax_1[1][1] = 4.99817085266;
   fMin_1[2][1] = 0.378905236721;
   fMax_1[2][1] = 4.99817085266;
   fMin_1[0][2] = 0.401666283607;
   fMax_1[0][2] = 4.68586063385;
   fMin_1[1][2] = 0.400014162064;
   fMax_1[1][2] = 4.99972915649;
   fMin_1[2][2] = 0.400014162064;
   fMax_1[2][2] = 4.99972915649;
   fMin_1[0][3] = 0.0674199610949;
   fMax_1[0][3] = 5.5010304451;
   fMin_1[1][3] = 0.00442243833095;
   fMax_1[1][3] = 5.99096441269;
   fMin_1[2][3] = 0.00442243833095;
   fMax_1[2][3] = 5.99096441269;
   fMin_1[0][4] = 0.400749415159;
   fMax_1[0][4] = 2.92169165611;
   fMin_1[1][4] = 0.400001376867;
   fMax_1[1][4] = 3.19991016388;
   fMin_1[2][4] = 0.400001376867;
   fMax_1[2][4] = 3.19991016388;
   fMin_1[0][5] = 0.000595237128437;
   fMax_1[0][5] = 3.1403400898;
   fMin_1[1][5] = 1.76370463123e-06;
   fMax_1[1][5] = 3.14159226418;
   fMin_1[2][5] = 1.76370463123e-06;
   fMax_1[2][5] = 3.14159226418;
   fMin_1[0][6] = 5.0251250267;
   fMax_1[0][6] = 99.5218429565;
   fMin_1[1][6] = 5.00372505188;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00372505188;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.5086154938;
   fMax_1[0][7] = 621.25189209;
   fMin_1[1][7] = 22.000579834;
   fMax_1[1][7] = 699.17364502;
   fMin_1[2][7] = 22.000579834;
   fMax_1[2][7] = 699.17364502;
   fMin_1[0][8] = 0.100902490318;
   fMax_1[0][8] = 248.784973145;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.991043091;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.991043091;
   fMin_1[0][9] = 27.5859622955;
   fMax_1[0][9] = 395.626098633;
   fMin_1[1][9] = 22.3099918365;
   fMax_1[1][9] = 399.818786621;
   fMin_1[2][9] = 22.3099918365;
   fMax_1[2][9] = 399.818786621;
   fMin_1[0][10] = 0.331056147814;
   fMax_1[0][10] = 236.97354126;
   fMin_1[1][10] = 0.32002851367;
   fMax_1[1][10] = 299.8175354;
   fMin_1[2][10] = 0.32002851367;
   fMax_1[2][10] = 299.8175354;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
