// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul  1 14:13:24 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 225323
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0700357034802,3.29995322227]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380170583725,4.99817085266]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400014162064,4.97834825516]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00442243833095,5.99961948395]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400001376867,3.19991016388]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.76370463123e-06,3.14159226418]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00372505188,99.9998016357]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.000579834,699.751220703]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.973556519]
MT2                           MT2                           MT2                           MT2                                                             'F'    [22.3099918365,399.925476074]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.150757178664,299.963409424]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.495071075144415;
   fWeightMatrix0to1[1][0] = 1.24301173652404;
   fWeightMatrix0to1[2][0] = -0.810921658278016;
   fWeightMatrix0to1[3][0] = 1.68905579601121;
   fWeightMatrix0to1[4][0] = -0.928502060081261;
   fWeightMatrix0to1[5][0] = -1.07142968807153;
   fWeightMatrix0to1[6][0] = -0.0639509920095382;
   fWeightMatrix0to1[7][0] = 1.93576388198073;
   fWeightMatrix0to1[8][0] = -1.30783866680166;
   fWeightMatrix0to1[9][0] = 0.33289598898967;
   fWeightMatrix0to1[10][0] = -1.81644649481153;
   fWeightMatrix0to1[11][0] = -0.913829665892493;
   fWeightMatrix0to1[12][0] = -1.74448692506044;
   fWeightMatrix0to1[13][0] = -0.0393691872044288;
   fWeightMatrix0to1[14][0] = -0.403413754831326;
   fWeightMatrix0to1[15][0] = 1.97817881125456;
   fWeightMatrix0to1[0][1] = -0.802401927172353;
   fWeightMatrix0to1[1][1] = 0.0276739332776068;
   fWeightMatrix0to1[2][1] = 1.05707138893871;
   fWeightMatrix0to1[3][1] = 1.39963939492938;
   fWeightMatrix0to1[4][1] = -0.974902970528511;
   fWeightMatrix0to1[5][1] = -0.986737259196431;
   fWeightMatrix0to1[6][1] = -2.12672968274578;
   fWeightMatrix0to1[7][1] = 0.458356852647469;
   fWeightMatrix0to1[8][1] = -1.51932099255635;
   fWeightMatrix0to1[9][1] = -0.518183914989995;
   fWeightMatrix0to1[10][1] = 1.08378869704041;
   fWeightMatrix0to1[11][1] = -1.87838477943057;
   fWeightMatrix0to1[12][1] = -1.71770989564604;
   fWeightMatrix0to1[13][1] = -0.0295341206616546;
   fWeightMatrix0to1[14][1] = 2.04823965922575;
   fWeightMatrix0to1[15][1] = 1.04323306154059;
   fWeightMatrix0to1[0][2] = -0.134265046612432;
   fWeightMatrix0to1[1][2] = 1.16279614990483;
   fWeightMatrix0to1[2][2] = -0.142199301506183;
   fWeightMatrix0to1[3][2] = -0.167911965071177;
   fWeightMatrix0to1[4][2] = -0.433964749226639;
   fWeightMatrix0to1[5][2] = 2.04631818206265;
   fWeightMatrix0to1[6][2] = -0.611198789869638;
   fWeightMatrix0to1[7][2] = 0.995709634452233;
   fWeightMatrix0to1[8][2] = 0.913151230832898;
   fWeightMatrix0to1[9][2] = 1.18717195570372;
   fWeightMatrix0to1[10][2] = 1.48570739864423;
   fWeightMatrix0to1[11][2] = -0.011660372021429;
   fWeightMatrix0to1[12][2] = 0.172013553551808;
   fWeightMatrix0to1[13][2] = -0.230768046203299;
   fWeightMatrix0to1[14][2] = 0.135005528163871;
   fWeightMatrix0to1[15][2] = 1.02396329528289;
   fWeightMatrix0to1[0][3] = 1.52210458138421;
   fWeightMatrix0to1[1][3] = 1.68235180833452;
   fWeightMatrix0to1[2][3] = -0.501952053501402;
   fWeightMatrix0to1[3][3] = 1.56417635747128;
   fWeightMatrix0to1[4][3] = -1.25634801274732;
   fWeightMatrix0to1[5][3] = 1.39774694294078;
   fWeightMatrix0to1[6][3] = -0.427146015868855;
   fWeightMatrix0to1[7][3] = -0.747425643935961;
   fWeightMatrix0to1[8][3] = -1.4595442827956;
   fWeightMatrix0to1[9][3] = -1.81565579570344;
   fWeightMatrix0to1[10][3] = 1.37424571461304;
   fWeightMatrix0to1[11][3] = 0.218864762331329;
   fWeightMatrix0to1[12][3] = -1.06556836014654;
   fWeightMatrix0to1[13][3] = 0.686557205845313;
   fWeightMatrix0to1[14][3] = -0.141636419753436;
   fWeightMatrix0to1[15][3] = 0.731269661199686;
   fWeightMatrix0to1[0][4] = 2.18429197454849;
   fWeightMatrix0to1[1][4] = -0.811513368778698;
   fWeightMatrix0to1[2][4] = 0.382288516685404;
   fWeightMatrix0to1[3][4] = -0.976270627175358;
   fWeightMatrix0to1[4][4] = 0.157514572608227;
   fWeightMatrix0to1[5][4] = -0.604303907442561;
   fWeightMatrix0to1[6][4] = 0.194351022163507;
   fWeightMatrix0to1[7][4] = -1.62309677034637;
   fWeightMatrix0to1[8][4] = 0.534572739784024;
   fWeightMatrix0to1[9][4] = 1.27388876081013;
   fWeightMatrix0to1[10][4] = 1.674232494534;
   fWeightMatrix0to1[11][4] = -0.901257595827367;
   fWeightMatrix0to1[12][4] = -0.248370562378922;
   fWeightMatrix0to1[13][4] = -1.25657354141333;
   fWeightMatrix0to1[14][4] = 0.0509726295625801;
   fWeightMatrix0to1[15][4] = -0.0769696624762484;
   fWeightMatrix0to1[0][5] = 1.15865199937827;
   fWeightMatrix0to1[1][5] = -0.691931583190038;
   fWeightMatrix0to1[2][5] = 0.800282322966088;
   fWeightMatrix0to1[3][5] = -0.515452100266602;
   fWeightMatrix0to1[4][5] = -0.900135141269012;
   fWeightMatrix0to1[5][5] = -0.0466792137718174;
   fWeightMatrix0to1[6][5] = -0.0108126460171994;
   fWeightMatrix0to1[7][5] = -1.30236109252851;
   fWeightMatrix0to1[8][5] = -1.62507493106765;
   fWeightMatrix0to1[9][5] = -1.00520890483213;
   fWeightMatrix0to1[10][5] = -0.52316813272672;
   fWeightMatrix0to1[11][5] = -0.970913176396819;
   fWeightMatrix0to1[12][5] = 2.65955948778029;
   fWeightMatrix0to1[13][5] = -1.02934190637004;
   fWeightMatrix0to1[14][5] = 0.567139152653165;
   fWeightMatrix0to1[15][5] = 0.535487827457638;
   fWeightMatrix0to1[0][6] = -0.649841605201611;
   fWeightMatrix0to1[1][6] = 1.24892921736832;
   fWeightMatrix0to1[2][6] = -0.269513385463608;
   fWeightMatrix0to1[3][6] = 0.000702272015499107;
   fWeightMatrix0to1[4][6] = -1.96885577954376;
   fWeightMatrix0to1[5][6] = -1.58199604130862;
   fWeightMatrix0to1[6][6] = -0.387764211353239;
   fWeightMatrix0to1[7][6] = 1.65032148817885;
   fWeightMatrix0to1[8][6] = -0.985252325032675;
   fWeightMatrix0to1[9][6] = 1.57763239202632;
   fWeightMatrix0to1[10][6] = -1.18428867015531;
   fWeightMatrix0to1[11][6] = -0.467559307840147;
   fWeightMatrix0to1[12][6] = 0.228573236222017;
   fWeightMatrix0to1[13][6] = 0.170377320433596;
   fWeightMatrix0to1[14][6] = -0.316292118403666;
   fWeightMatrix0to1[15][6] = 0.504292677307238;
   fWeightMatrix0to1[0][7] = 0.685519115074947;
   fWeightMatrix0to1[1][7] = -1.66026531508187;
   fWeightMatrix0to1[2][7] = -3.92251868764893;
   fWeightMatrix0to1[3][7] = 1.87962303989205;
   fWeightMatrix0to1[4][7] = 0.282995011647233;
   fWeightMatrix0to1[5][7] = -0.927236205150358;
   fWeightMatrix0to1[6][7] = 5.84223260895019;
   fWeightMatrix0to1[7][7] = -1.04342637051069;
   fWeightMatrix0to1[8][7] = -1.84386236312435;
   fWeightMatrix0to1[9][7] = 0.383041092620012;
   fWeightMatrix0to1[10][7] = -0.32911273060794;
   fWeightMatrix0to1[11][7] = 1.21698612497524;
   fWeightMatrix0to1[12][7] = 0.237504303699801;
   fWeightMatrix0to1[13][7] = 0.0509362089817423;
   fWeightMatrix0to1[14][7] = -5.94788662679471;
   fWeightMatrix0to1[15][7] = -0.0430060808979211;
   fWeightMatrix0to1[0][8] = -2.16164400163723;
   fWeightMatrix0to1[1][8] = 0.946412197007738;
   fWeightMatrix0to1[2][8] = -0.450391333067034;
   fWeightMatrix0to1[3][8] = -1.75068098611979;
   fWeightMatrix0to1[4][8] = 1.65055882863654;
   fWeightMatrix0to1[5][8] = -1.35972833378001;
   fWeightMatrix0to1[6][8] = 0.286738049816692;
   fWeightMatrix0to1[7][8] = 0.858344406992976;
   fWeightMatrix0to1[8][8] = 1.55770968423633;
   fWeightMatrix0to1[9][8] = -1.99631232185826;
   fWeightMatrix0to1[10][8] = 0.00664837638539453;
   fWeightMatrix0to1[11][8] = 1.64831716590644;
   fWeightMatrix0to1[12][8] = 0.854579012948916;
   fWeightMatrix0to1[13][8] = 1.73822250856528;
   fWeightMatrix0to1[14][8] = -0.630191842048235;
   fWeightMatrix0to1[15][8] = -0.979434086412316;
   fWeightMatrix0to1[0][9] = -1.41033279991003;
   fWeightMatrix0to1[1][9] = 2.80466568763345;
   fWeightMatrix0to1[2][9] = 2.72564312521227;
   fWeightMatrix0to1[3][9] = -0.4097698355332;
   fWeightMatrix0to1[4][9] = -0.95093012572098;
   fWeightMatrix0to1[5][9] = 0.26023071276823;
   fWeightMatrix0to1[6][9] = -4.10126104362191;
   fWeightMatrix0to1[7][9] = 0.491347509683604;
   fWeightMatrix0to1[8][9] = 1.65079911184395;
   fWeightMatrix0to1[9][9] = -1.69525938332057;
   fWeightMatrix0to1[10][9] = -0.497101384897192;
   fWeightMatrix0to1[11][9] = 0.524775492171792;
   fWeightMatrix0to1[12][9] = 0.957269830776695;
   fWeightMatrix0to1[13][9] = 1.03916926883457;
   fWeightMatrix0to1[14][9] = 3.74225421831036;
   fWeightMatrix0to1[15][9] = -2.0534134430005;
   fWeightMatrix0to1[0][10] = 1.35713765481559;
   fWeightMatrix0to1[1][10] = 0.158174669723391;
   fWeightMatrix0to1[2][10] = 1.22333382320478;
   fWeightMatrix0to1[3][10] = 0.626559196809399;
   fWeightMatrix0to1[4][10] = 1.58222145205656;
   fWeightMatrix0to1[5][10] = -0.261433832223863;
   fWeightMatrix0to1[6][10] = -1.57777221107092;
   fWeightMatrix0to1[7][10] = 0.573524815941007;
   fWeightMatrix0to1[8][10] = -0.798824690925538;
   fWeightMatrix0to1[9][10] = -1.1690040917705;
   fWeightMatrix0to1[10][10] = 1.9042056449622;
   fWeightMatrix0to1[11][10] = 1.33360275218493;
   fWeightMatrix0to1[12][10] = -0.919652852948846;
   fWeightMatrix0to1[13][10] = 2.19709009844007;
   fWeightMatrix0to1[14][10] = 1.56763283603288;
   fWeightMatrix0to1[15][10] = -2.03532213556176;
   fWeightMatrix0to1[0][11] = -0.577875326887152;
   fWeightMatrix0to1[1][11] = -3.59052789952309;
   fWeightMatrix0to1[2][11] = -2.42606765363046;
   fWeightMatrix0to1[3][11] = -1.78424955602447;
   fWeightMatrix0to1[4][11] = -2.22634351703715;
   fWeightMatrix0to1[5][11] = 1.23597299386728;
   fWeightMatrix0to1[6][11] = 4.2054822635541;
   fWeightMatrix0to1[7][11] = -1.88139398889145;
   fWeightMatrix0to1[8][11] = 0.0885903165411092;
   fWeightMatrix0to1[9][11] = -1.26351692009395;
   fWeightMatrix0to1[10][11] = 0.0173720380111854;
   fWeightMatrix0to1[11][11] = 1.83632889474098;
   fWeightMatrix0to1[12][11] = -0.0200639281666967;
   fWeightMatrix0to1[13][11] = -0.227869295590864;
   fWeightMatrix0to1[14][11] = -3.89299560329323;
   fWeightMatrix0to1[15][11] = 0.869321120204842;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0139444241137918;
   fWeightMatrix1to2[0][1] = 0.15451328097369;
   fWeightMatrix1to2[0][2] = -0.129619404024706;
   fWeightMatrix1to2[0][3] = -0.000695760339314301;
   fWeightMatrix1to2[0][4] = -0.0324705197899857;
   fWeightMatrix1to2[0][5] = -0.00272971520769137;
   fWeightMatrix1to2[0][6] = 0.627619145206351;
   fWeightMatrix1to2[0][7] = 0.00483310327532049;
   fWeightMatrix1to2[0][8] = 0.00218556767138545;
   fWeightMatrix1to2[0][9] = -0.00580470089716117;
   fWeightMatrix1to2[0][10] = 0.0066668394976432;
   fWeightMatrix1to2[0][11] = 0.00993054625207379;
   fWeightMatrix1to2[0][12] = -0.00377825439119411;
   fWeightMatrix1to2[0][13] = -0.0299673696459261;
   fWeightMatrix1to2[0][14] = 0.716505723891069;
   fWeightMatrix1to2[0][15] = -0.0486491169522207;
   fWeightMatrix1to2[0][16] = 0.127558771397775;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0700357034802;
   fMax_1[0][0] = 3.27965116501;
   fMin_1[1][0] = 0.0706459358335;
   fMax_1[1][0] = 3.29995322227;
   fMin_1[2][0] = 0.0700357034802;
   fMax_1[2][0] = 3.29995322227;
   fMin_1[0][1] = 0.39005368948;
   fMax_1[0][1] = 4.80312728882;
   fMin_1[1][1] = 0.380170583725;
   fMax_1[1][1] = 4.99817085266;
   fMin_1[2][1] = 0.380170583725;
   fMax_1[2][1] = 4.99817085266;
   fMin_1[0][2] = 0.475951552391;
   fMax_1[0][2] = 4.54190635681;
   fMin_1[1][2] = 0.400014162064;
   fMax_1[1][2] = 4.97834825516;
   fMin_1[2][2] = 0.400014162064;
   fMax_1[2][2] = 4.97834825516;
   fMin_1[0][3] = 0.288734763861;
   fMax_1[0][3] = 5.59597015381;
   fMin_1[1][3] = 0.00442243833095;
   fMax_1[1][3] = 5.99961948395;
   fMin_1[2][3] = 0.00442243833095;
   fMax_1[2][3] = 5.99961948395;
   fMin_1[0][4] = 0.403152883053;
   fMax_1[0][4] = 3.17182016373;
   fMin_1[1][4] = 0.400001376867;
   fMax_1[1][4] = 3.19991016388;
   fMin_1[2][4] = 0.400001376867;
   fMax_1[2][4] = 3.19991016388;
   fMin_1[0][5] = 0.0344244167209;
   fMax_1[0][5] = 3.14154648781;
   fMin_1[1][5] = 1.76370463123e-06;
   fMax_1[1][5] = 3.14159226418;
   fMin_1[2][5] = 1.76370463123e-06;
   fMax_1[2][5] = 3.14159226418;
   fMin_1[0][6] = 5.01443195343;
   fMax_1[0][6] = 98.743522644;
   fMin_1[1][6] = 5.00372505188;
   fMax_1[1][6] = 99.9998016357;
   fMin_1[2][6] = 5.00372505188;
   fMax_1[2][6] = 99.9998016357;
   fMin_1[0][7] = 22.2487831116;
   fMax_1[0][7] = 691.662414551;
   fMin_1[1][7] = 22.000579834;
   fMax_1[1][7] = 699.751220703;
   fMin_1[2][7] = 22.000579834;
   fMax_1[2][7] = 699.751220703;
   fMin_1[0][8] = 0.0236637573689;
   fMax_1[0][8] = 248.594039917;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.973556519;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.973556519;
   fMin_1[0][9] = 56.6907806396;
   fMax_1[0][9] = 392.435821533;
   fMin_1[1][9] = 22.3099918365;
   fMax_1[1][9] = 399.925476074;
   fMin_1[2][9] = 22.3099918365;
   fMax_1[2][9] = 399.925476074;
   fMin_1[0][10] = 5.08085107803;
   fMax_1[0][10] = 299.668151855;
   fMin_1[1][10] = 0.150757178664;
   fMax_1[1][10] = 299.963409424;
   fMin_1[2][10] = 0.150757178664;
   fMax_1[2][10] = 299.963409424;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
