// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May 13 11:43:46 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 15654
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0744008347392,3.29884552956]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380652487278,4.95207595825]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.401666283607,4.83203697205]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0355969779193,5.91814279556]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400697886944,3.17235708237]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.000525824725628,3.14149975777]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.0251250267,99.9966583252]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.002456665,688.641540527]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0.0127812996507,249.781051636]
MT2                           MT2                           MT2                           MT2                                                             'F'    [27.5859622955,395.626098633]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.331056147814,298.342681885]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.38902988646288;
   fWeightMatrix0to1[1][0] = 1.83651422169897;
   fWeightMatrix0to1[2][0] = 0.202111172199362;
   fWeightMatrix0to1[3][0] = -0.419515988168638;
   fWeightMatrix0to1[4][0] = -2.74348346119868;
   fWeightMatrix0to1[5][0] = -0.34048344855294;
   fWeightMatrix0to1[6][0] = 0.9813902711935;
   fWeightMatrix0to1[7][0] = 2.74384888977633;
   fWeightMatrix0to1[8][0] = -1.66118849087923;
   fWeightMatrix0to1[9][0] = -0.0517579920769586;
   fWeightMatrix0to1[10][0] = -2.58274470191732;
   fWeightMatrix0to1[11][0] = -0.467088927511791;
   fWeightMatrix0to1[12][0] = -1.86735960221292;
   fWeightMatrix0to1[13][0] = -0.453995774470683;
   fWeightMatrix0to1[14][0] = -0.635775443407361;
   fWeightMatrix0to1[15][0] = 3.08756219648767;
   fWeightMatrix0to1[0][1] = -3.26596102012808;
   fWeightMatrix0to1[1][1] = 1.35586509645647;
   fWeightMatrix0to1[2][1] = 2.00914440238925;
   fWeightMatrix0to1[3][1] = -1.3708948296396;
   fWeightMatrix0to1[4][1] = -2.10382676249169;
   fWeightMatrix0to1[5][1] = 0.326998596054644;
   fWeightMatrix0to1[6][1] = -0.525060648154079;
   fWeightMatrix0to1[7][1] = 1.24306178652917;
   fWeightMatrix0to1[8][1] = -0.821186668501346;
   fWeightMatrix0to1[9][1] = -1.88517514865151;
   fWeightMatrix0to1[10][1] = 2.85252099673405;
   fWeightMatrix0to1[11][1] = -1.61355691612318;
   fWeightMatrix0to1[12][1] = -2.54771100833253;
   fWeightMatrix0to1[13][1] = 0.327815897013272;
   fWeightMatrix0to1[14][1] = 1.06163041790682;
   fWeightMatrix0to1[15][1] = 2.37307983128317;
   fWeightMatrix0to1[0][2] = -0.69202071192143;
   fWeightMatrix0to1[1][2] = -0.627197818127261;
   fWeightMatrix0to1[2][2] = -0.554409008079638;
   fWeightMatrix0to1[3][2] = 0.0865332438112675;
   fWeightMatrix0to1[4][2] = -0.729440021693097;
   fWeightMatrix0to1[5][2] = 0.001259308603008;
   fWeightMatrix0to1[6][2] = -0.958330692308394;
   fWeightMatrix0to1[7][2] = 0.668419857012304;
   fWeightMatrix0to1[8][2] = 1.3409798604686;
   fWeightMatrix0to1[9][2] = 0.498254811994182;
   fWeightMatrix0to1[10][2] = 1.8760993729996;
   fWeightMatrix0to1[11][2] = 0.310629750441929;
   fWeightMatrix0to1[12][2] = 0.187191042308207;
   fWeightMatrix0to1[13][2] = -2.55372834146851;
   fWeightMatrix0to1[14][2] = 1.55601450914906;
   fWeightMatrix0to1[15][2] = 1.08974471503575;
   fWeightMatrix0to1[0][3] = -0.0517288129305503;
   fWeightMatrix0to1[1][3] = 0.785880694760375;
   fWeightMatrix0to1[2][3] = 2.23047468624287;
   fWeightMatrix0to1[3][3] = -0.602839224629754;
   fWeightMatrix0to1[4][3] = -2.73002170294916;
   fWeightMatrix0to1[5][3] = 0.257392533069832;
   fWeightMatrix0to1[6][3] = -1.93711837337838;
   fWeightMatrix0to1[7][3] = -0.0544055632344964;
   fWeightMatrix0to1[8][3] = -1.1734920090334;
   fWeightMatrix0to1[9][3] = -3.38175743875648;
   fWeightMatrix0to1[10][3] = 1.17610838787096;
   fWeightMatrix0to1[11][3] = 0.825713409781983;
   fWeightMatrix0to1[12][3] = -1.78044450248335;
   fWeightMatrix0to1[13][3] = 0.0321048709521293;
   fWeightMatrix0to1[14][3] = 0.700452049881254;
   fWeightMatrix0to1[15][3] = 3.4123438891837;
   fWeightMatrix0to1[0][4] = 1.33186060745405;
   fWeightMatrix0to1[1][4] = -0.106918951524287;
   fWeightMatrix0to1[2][4] = -2.23671610323436;
   fWeightMatrix0to1[3][4] = -0.285805581365286;
   fWeightMatrix0to1[4][4] = 0.647593351118479;
   fWeightMatrix0to1[5][4] = -0.934901397292093;
   fWeightMatrix0to1[6][4] = 0.640300241956441;
   fWeightMatrix0to1[7][4] = -0.83099399808488;
   fWeightMatrix0to1[8][4] = 0.885314102282319;
   fWeightMatrix0to1[9][4] = 1.80429105546952;
   fWeightMatrix0to1[10][4] = 1.39624435699597;
   fWeightMatrix0to1[11][4] = 0.411649817946922;
   fWeightMatrix0to1[12][4] = -1.03634630367697;
   fWeightMatrix0to1[13][4] = -2.02666845805276;
   fWeightMatrix0to1[14][4] = -2.25350009568462;
   fWeightMatrix0to1[15][4] = -1.10555693395518;
   fWeightMatrix0to1[0][5] = 1.59054893835473;
   fWeightMatrix0to1[1][5] = -0.0351713532030232;
   fWeightMatrix0to1[2][5] = 1.1989354260926;
   fWeightMatrix0to1[3][5] = 0.437426098236101;
   fWeightMatrix0to1[4][5] = -1.04376499300721;
   fWeightMatrix0to1[5][5] = -0.154230313226405;
   fWeightMatrix0to1[6][5] = 2.22733831401998;
   fWeightMatrix0to1[7][5] = -0.573840822475306;
   fWeightMatrix0to1[8][5] = -1.2829004194684;
   fWeightMatrix0to1[9][5] = -1.01077502873941;
   fWeightMatrix0to1[10][5] = -0.793065009508785;
   fWeightMatrix0to1[11][5] = -0.435591694095896;
   fWeightMatrix0to1[12][5] = 1.82071750117186;
   fWeightMatrix0to1[13][5] = -1.70982046663493;
   fWeightMatrix0to1[14][5] = -1.94656761744766;
   fWeightMatrix0to1[15][5] = 1.37983487388215;
   fWeightMatrix0to1[0][6] = 0.727310724217621;
   fWeightMatrix0to1[1][6] = -1.30775468336958;
   fWeightMatrix0to1[2][6] = -1.61653857618261;
   fWeightMatrix0to1[3][6] = -0.950154147045456;
   fWeightMatrix0to1[4][6] = -0.304067281231078;
   fWeightMatrix0to1[5][6] = -1.9713547535049;
   fWeightMatrix0to1[6][6] = 1.46018435316638;
   fWeightMatrix0to1[7][6] = 1.10450107565938;
   fWeightMatrix0to1[8][6] = -1.69427529423008;
   fWeightMatrix0to1[9][6] = 0.895764894566959;
   fWeightMatrix0to1[10][6] = 1.40652969464409;
   fWeightMatrix0to1[11][6] = 1.77479127827175;
   fWeightMatrix0to1[12][6] = -0.233711878323721;
   fWeightMatrix0to1[13][6] = -0.959129728795591;
   fWeightMatrix0to1[14][6] = -2.08533922571824;
   fWeightMatrix0to1[15][6] = 0.119046954756813;
   fWeightMatrix0to1[0][7] = 0.0476227218930742;
   fWeightMatrix0to1[1][7] = 0.900175061117457;
   fWeightMatrix0to1[2][7] = 0.264794116164662;
   fWeightMatrix0to1[3][7] = 1.42565914931832;
   fWeightMatrix0to1[4][7] = -0.614002897931041;
   fWeightMatrix0to1[5][7] = -0.76847026385591;
   fWeightMatrix0to1[6][7] = 1.03810001314257;
   fWeightMatrix0to1[7][7] = -0.167145316943307;
   fWeightMatrix0to1[8][7] = -2.47836806969775;
   fWeightMatrix0to1[9][7] = -1.52381784636593;
   fWeightMatrix0to1[10][7] = -0.366608252381098;
   fWeightMatrix0to1[11][7] = 5.26234353122415;
   fWeightMatrix0to1[12][7] = 0.0235174078882366;
   fWeightMatrix0to1[13][7] = -0.127201048464894;
   fWeightMatrix0to1[14][7] = -0.568631767469609;
   fWeightMatrix0to1[15][7] = 0.736314672589209;
   fWeightMatrix0to1[0][8] = -2.88847567343148;
   fWeightMatrix0to1[1][8] = 0.57920400275529;
   fWeightMatrix0to1[2][8] = 0.595405112433258;
   fWeightMatrix0to1[3][8] = -5.37737141517884;
   fWeightMatrix0to1[4][8] = 0.17422623436769;
   fWeightMatrix0to1[5][8] = -5.2420923425573;
   fWeightMatrix0to1[6][8] = 1.37335133315057;
   fWeightMatrix0to1[7][8] = 4.42697943712242;
   fWeightMatrix0to1[8][8] = 1.11151685184176;
   fWeightMatrix0to1[9][8] = -1.2338397380475;
   fWeightMatrix0to1[10][8] = 0.547107796683626;
   fWeightMatrix0to1[11][8] = -0.186989673236451;
   fWeightMatrix0to1[12][8] = 1.72708812482221;
   fWeightMatrix0to1[13][8] = 0.530409476906674;
   fWeightMatrix0to1[14][8] = -1.77141914371462;
   fWeightMatrix0to1[15][8] = -0.164424234847099;
   fWeightMatrix0to1[0][9] = -0.0630612123516451;
   fWeightMatrix0to1[1][9] = 1.37047238550406;
   fWeightMatrix0to1[2][9] = 1.58436908137963;
   fWeightMatrix0to1[3][9] = -1.45972873016288;
   fWeightMatrix0to1[4][9] = -0.385169097623896;
   fWeightMatrix0to1[5][9] = -1.85197049102108;
   fWeightMatrix0to1[6][9] = -1.00103101806271;
   fWeightMatrix0to1[7][9] = 0.71682156734861;
   fWeightMatrix0to1[8][9] = 1.31574062016949;
   fWeightMatrix0to1[9][9] = -1.26418816958434;
   fWeightMatrix0to1[10][9] = -1.23537603226599;
   fWeightMatrix0to1[11][9] = 6.95874304302514;
   fWeightMatrix0to1[12][9] = 0.442352595152318;
   fWeightMatrix0to1[13][9] = -0.168408413559277;
   fWeightMatrix0to1[14][9] = 1.37936773597619;
   fWeightMatrix0to1[15][9] = -0.276687388077298;
   fWeightMatrix0to1[0][10] = 1.85402256859744;
   fWeightMatrix0to1[1][10] = 0.582479189381206;
   fWeightMatrix0to1[2][10] = -0.037845756214252;
   fWeightMatrix0to1[3][10] = -0.118046272592754;
   fWeightMatrix0to1[4][10] = 2.14917588942137;
   fWeightMatrix0to1[5][10] = -0.056821898506854;
   fWeightMatrix0to1[6][10] = -1.26009585587907;
   fWeightMatrix0to1[7][10] = -0.519350919017242;
   fWeightMatrix0to1[8][10] = -1.54698038793038;
   fWeightMatrix0to1[9][10] = -1.19563209065231;
   fWeightMatrix0to1[10][10] = -0.103543803968912;
   fWeightMatrix0to1[11][10] = 1.9305211110706;
   fWeightMatrix0to1[12][10] = 0.152535733231383;
   fWeightMatrix0to1[13][10] = 0.376029999578335;
   fWeightMatrix0to1[14][10] = 0.0930071758721615;
   fWeightMatrix0to1[15][10] = -2.79259947204197;
   fWeightMatrix0to1[0][11] = -0.107517636704522;
   fWeightMatrix0to1[1][11] = -3.05533859352987;
   fWeightMatrix0to1[2][11] = 0.856206048582455;
   fWeightMatrix0to1[3][11] = -2.9317167102764;
   fWeightMatrix0to1[4][11] = -1.03559990028965;
   fWeightMatrix0to1[5][11] = -3.29632613858778;
   fWeightMatrix0to1[6][11] = 3.61833751522582;
   fWeightMatrix0to1[7][11] = -0.564710539557896;
   fWeightMatrix0to1[8][11] = -0.209895360612328;
   fWeightMatrix0to1[9][11] = -2.05180861575317;
   fWeightMatrix0to1[10][11] = -0.349572921437481;
   fWeightMatrix0to1[11][11] = 11.1424974580175;
   fWeightMatrix0to1[12][11] = 0.872599225439559;
   fWeightMatrix0to1[13][11] = -1.06825317737181;
   fWeightMatrix0to1[14][11] = -5.01551204893603;
   fWeightMatrix0to1[15][11] = 0.949541673602126;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.0414212862120548;
   fWeightMatrix1to2[0][1] = 0.352174198272678;
   fWeightMatrix1to2[0][2] = -0.0717760191788889;
   fWeightMatrix1to2[0][3] = -0.0906137219461524;
   fWeightMatrix1to2[0][4] = -0.159455486765369;
   fWeightMatrix1to2[0][5] = 0.0935559393526966;
   fWeightMatrix1to2[0][6] = 0.26834853372879;
   fWeightMatrix1to2[0][7] = -0.0377752152335796;
   fWeightMatrix1to2[0][8] = 0.0223544113753619;
   fWeightMatrix1to2[0][9] = -0.0643431194511904;
   fWeightMatrix1to2[0][10] = -0.0259297331350442;
   fWeightMatrix1to2[0][11] = -0.394891726852903;
   fWeightMatrix1to2[0][12] = 0.0196203613626071;
   fWeightMatrix1to2[0][13] = -0.0175817787961608;
   fWeightMatrix1to2[0][14] = 0.52581810107242;
   fWeightMatrix1to2[0][15] = -0.138155508228839;
   fWeightMatrix1to2[0][16] = 0.971587482717556;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.124257586896;
   fMax_1[0][0] = 3.29416155815;
   fMin_1[1][0] = 0.0744008347392;
   fMax_1[1][0] = 3.29884552956;
   fMin_1[2][0] = 0.0744008347392;
   fMax_1[2][0] = 3.29884552956;
   fMin_1[0][1] = 0.433966368437;
   fMax_1[0][1] = 4.79502058029;
   fMin_1[1][1] = 0.380652487278;
   fMax_1[1][1] = 4.95207595825;
   fMin_1[2][1] = 0.380652487278;
   fMax_1[2][1] = 4.95207595825;
   fMin_1[0][2] = 0.401666283607;
   fMax_1[0][2] = 4.68586063385;
   fMin_1[1][2] = 0.404565602541;
   fMax_1[1][2] = 4.83203697205;
   fMin_1[2][2] = 0.401666283607;
   fMax_1[2][2] = 4.83203697205;
   fMin_1[0][3] = 0.0674199610949;
   fMax_1[0][3] = 5.5010304451;
   fMin_1[1][3] = 0.0355969779193;
   fMax_1[1][3] = 5.91814279556;
   fMin_1[2][3] = 0.0355969779193;
   fMax_1[2][3] = 5.91814279556;
   fMin_1[0][4] = 0.400749415159;
   fMax_1[0][4] = 2.92169165611;
   fMin_1[1][4] = 0.400697886944;
   fMax_1[1][4] = 3.17235708237;
   fMin_1[2][4] = 0.400697886944;
   fMax_1[2][4] = 3.17235708237;
   fMin_1[0][5] = 0.000595237128437;
   fMax_1[0][5] = 3.1403400898;
   fMin_1[1][5] = 0.000525824725628;
   fMax_1[1][5] = 3.14149975777;
   fMin_1[2][5] = 0.000525824725628;
   fMax_1[2][5] = 3.14149975777;
   fMin_1[0][6] = 5.0251250267;
   fMax_1[0][6] = 99.5218429565;
   fMin_1[1][6] = 5.02790021896;
   fMax_1[1][6] = 99.9966583252;
   fMin_1[2][6] = 5.0251250267;
   fMax_1[2][6] = 99.9966583252;
   fMin_1[0][7] = 22.5086154938;
   fMax_1[0][7] = 621.25189209;
   fMin_1[1][7] = 22.002456665;
   fMax_1[1][7] = 688.641540527;
   fMin_1[2][7] = 22.002456665;
   fMax_1[2][7] = 688.641540527;
   fMin_1[0][8] = 0.100902490318;
   fMax_1[0][8] = 248.784973145;
   fMin_1[1][8] = 0.0127812996507;
   fMax_1[1][8] = 249.781051636;
   fMin_1[2][8] = 0.0127812996507;
   fMax_1[2][8] = 249.781051636;
   fMin_1[0][9] = 27.5859622955;
   fMax_1[0][9] = 395.626098633;
   fMin_1[1][9] = 32.4793205261;
   fMax_1[1][9] = 391.314117432;
   fMin_1[2][9] = 27.5859622955;
   fMax_1[2][9] = 395.626098633;
   fMin_1[0][10] = 0.331056147814;
   fMax_1[0][10] = 236.97354126;
   fMin_1[1][10] = 1.37581372261;
   fMax_1[1][10] = 298.342681885;
   fMin_1[2][10] = 0.331056147814;
   fMax_1[2][10] = 298.342681885;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
