// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May  6 14:11:35 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 16801
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0704743787646,3.29991745949]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.385140359402,4.97898674011]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.403012275696,4.83203697205]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0163523908705,5.91814279556]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400462150574,3.19950509071]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.000659405777697,3.14121699333]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00658273697,99.9985351562]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.1016559601,697.742614746]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.548706055]
MT2                           MT2                           MT2                           MT2                                                             'F'    [25.0663490295,399.860321045]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [1.33661460876,299.960723877]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.124693776974618;
   fWeightMatrix0to1[1][0] = 1.01685647501103;
   fWeightMatrix0to1[2][0] = 0.837301144449625;
   fWeightMatrix0to1[3][0] = 1.73440197074236;
   fWeightMatrix0to1[4][0] = -1.11918965570879;
   fWeightMatrix0to1[5][0] = -1.34315924657447;
   fWeightMatrix0to1[6][0] = -0.204045197547614;
   fWeightMatrix0to1[7][0] = 1.76523970947162;
   fWeightMatrix0to1[8][0] = -1.32466835151363;
   fWeightMatrix0to1[9][0] = -0.985295198290827;
   fWeightMatrix0to1[10][0] = -1.26848245277855;
   fWeightMatrix0to1[11][0] = -0.968264172065272;
   fWeightMatrix0to1[12][0] = -1.25755770416755;
   fWeightMatrix0to1[13][0] = -0.613689172931426;
   fWeightMatrix0to1[14][0] = -1.08249771141824;
   fWeightMatrix0to1[15][0] = 1.3531328723035;
   fWeightMatrix0to1[0][1] = -0.149886383772036;
   fWeightMatrix0to1[1][1] = 1.3187000603839;
   fWeightMatrix0to1[2][1] = 0.459485346216396;
   fWeightMatrix0to1[3][1] = 1.46580356820603;
   fWeightMatrix0to1[4][1] = -0.858961360637697;
   fWeightMatrix0to1[5][1] = -0.417978961776533;
   fWeightMatrix0to1[6][1] = 0.867770037736821;
   fWeightMatrix0to1[7][1] = -0.269610714041125;
   fWeightMatrix0to1[8][1] = -1.11794245844296;
   fWeightMatrix0to1[9][1] = -0.408863084076663;
   fWeightMatrix0to1[10][1] = 1.14258059553967;
   fWeightMatrix0to1[11][1] = -1.42315904052327;
   fWeightMatrix0to1[12][1] = -1.57151872264908;
   fWeightMatrix0to1[13][1] = 0.093545558246515;
   fWeightMatrix0to1[14][1] = 0.526214113304984;
   fWeightMatrix0to1[15][1] = 1.34506243445772;
   fWeightMatrix0to1[0][2] = -0.21943791323601;
   fWeightMatrix0to1[1][2] = 0.333742291320959;
   fWeightMatrix0to1[2][2] = 0.212971882026037;
   fWeightMatrix0to1[3][2] = -0.299782824628783;
   fWeightMatrix0to1[4][2] = -0.730208235169676;
   fWeightMatrix0to1[5][2] = 2.05958713907049;
   fWeightMatrix0to1[6][2] = -0.412621126306721;
   fWeightMatrix0to1[7][2] = 0.809670131213362;
   fWeightMatrix0to1[8][2] = 1.25407396903695;
   fWeightMatrix0to1[9][2] = 0.855537225318795;
   fWeightMatrix0to1[10][2] = 1.79013272697595;
   fWeightMatrix0to1[11][2] = 0.554435652475229;
   fWeightMatrix0to1[12][2] = -0.471758534308602;
   fWeightMatrix0to1[13][2] = -1.47831257485367;
   fWeightMatrix0to1[14][2] = 0.27652866414243;
   fWeightMatrix0to1[15][2] = 0.0663439761232912;
   fWeightMatrix0to1[0][3] = 1.47269924894822;
   fWeightMatrix0to1[1][3] = 1.64287737332636;
   fWeightMatrix0to1[2][3] = 1.48862535566991;
   fWeightMatrix0to1[3][3] = 1.28346841314087;
   fWeightMatrix0to1[4][3] = -1.20578378322002;
   fWeightMatrix0to1[5][3] = 1.36665860282355;
   fWeightMatrix0to1[6][3] = -1.7484124092618;
   fWeightMatrix0to1[7][3] = -0.992842839176017;
   fWeightMatrix0to1[8][3] = -1.25197777312181;
   fWeightMatrix0to1[9][3] = -1.74089233481784;
   fWeightMatrix0to1[10][3] = 1.4954263446052;
   fWeightMatrix0to1[11][3] = 0.913876638861378;
   fWeightMatrix0to1[12][3] = -1.6163636489693;
   fWeightMatrix0to1[13][3] = 0.21402438912039;
   fWeightMatrix0to1[14][3] = 0.00421348515245267;
   fWeightMatrix0to1[15][3] = 0.509335346144892;
   fWeightMatrix0to1[0][4] = 2.08920407014119;
   fWeightMatrix0to1[1][4] = -0.621016602029327;
   fWeightMatrix0to1[2][4] = 0.192006712805786;
   fWeightMatrix0to1[3][4] = -1.21714466108621;
   fWeightMatrix0to1[4][4] = 0.924981154329945;
   fWeightMatrix0to1[5][4] = -0.465887382115176;
   fWeightMatrix0to1[6][4] = -0.421691747937737;
   fWeightMatrix0to1[7][4] = -1.70633602321277;
   fWeightMatrix0to1[8][4] = 0.645855969527966;
   fWeightMatrix0to1[9][4] = 0.95759886730602;
   fWeightMatrix0to1[10][4] = 1.37986279119952;
   fWeightMatrix0to1[11][4] = 0.114471667383389;
   fWeightMatrix0to1[12][4] = -1.46947489857607;
   fWeightMatrix0to1[13][4] = -1.8986997902929;
   fWeightMatrix0to1[14][4] = 0.0137237444965293;
   fWeightMatrix0to1[15][4] = 0.00348279713282532;
   fWeightMatrix0to1[0][5] = 1.10881170804769;
   fWeightMatrix0to1[1][5] = -0.346832531269076;
   fWeightMatrix0to1[2][5] = 0.416976296934932;
   fWeightMatrix0to1[3][5] = -0.692451937441801;
   fWeightMatrix0to1[4][5] = -0.0881486033650448;
   fWeightMatrix0to1[5][5] = -0.931971575588552;
   fWeightMatrix0to1[6][5] = 0.143895100760596;
   fWeightMatrix0to1[7][5] = -0.535798523955309;
   fWeightMatrix0to1[8][5] = -1.49944156092664;
   fWeightMatrix0to1[9][5] = -1.44210355577998;
   fWeightMatrix0to1[10][5] = -0.541710226023258;
   fWeightMatrix0to1[11][5] = 0.137908303735162;
   fWeightMatrix0to1[12][5] = 1.17300693042249;
   fWeightMatrix0to1[13][5] = -1.3222430634531;
   fWeightMatrix0to1[14][5] = 0.299911075582866;
   fWeightMatrix0to1[15][5] = 1.01261965502845;
   fWeightMatrix0to1[0][6] = -0.901119451174646;
   fWeightMatrix0to1[1][6] = -0.247915005256181;
   fWeightMatrix0to1[2][6] = -1.42389705521285;
   fWeightMatrix0to1[3][6] = -0.0655362000031949;
   fWeightMatrix0to1[4][6] = -1.94975972437351;
   fWeightMatrix0to1[5][6] = -1.80186476691612;
   fWeightMatrix0to1[6][6] = 1.24027252255874;
   fWeightMatrix0to1[7][6] = 1.9538674746198;
   fWeightMatrix0to1[8][6] = -1.06023642122903;
   fWeightMatrix0to1[9][6] = 1.6297143723194;
   fWeightMatrix0to1[10][6] = -0.920061359852105;
   fWeightMatrix0to1[11][6] = -0.754837156462329;
   fWeightMatrix0to1[12][6] = -0.357072773926983;
   fWeightMatrix0to1[13][6] = 0.316603774214891;
   fWeightMatrix0to1[14][6] = -0.656352321328329;
   fWeightMatrix0to1[15][6] = 0.798719820325115;
   fWeightMatrix0to1[0][7] = 1.10662952052038;
   fWeightMatrix0to1[1][7] = -0.461083235481095;
   fWeightMatrix0to1[2][7] = -0.826745260149116;
   fWeightMatrix0to1[3][7] = 1.68079459560289;
   fWeightMatrix0to1[4][7] = 0.0345221090858583;
   fWeightMatrix0to1[5][7] = -0.0169234859796168;
   fWeightMatrix0to1[6][7] = 1.60693067970573;
   fWeightMatrix0to1[7][7] = -1.89310945774982;
   fWeightMatrix0to1[8][7] = -1.46907800729456;
   fWeightMatrix0to1[9][7] = -0.073939623266614;
   fWeightMatrix0to1[10][7] = -0.219232182179597;
   fWeightMatrix0to1[11][7] = 1.61821599947833;
   fWeightMatrix0to1[12][7] = 1.03390981438652;
   fWeightMatrix0to1[13][7] = -0.596289991595627;
   fWeightMatrix0to1[14][7] = -1.28740578859165;
   fWeightMatrix0to1[15][7] = 0.0176791182246907;
   fWeightMatrix0to1[0][8] = -1.19492790904545;
   fWeightMatrix0to1[1][8] = 0.480363196874099;
   fWeightMatrix0to1[2][8] = 0.391708317182413;
   fWeightMatrix0to1[3][8] = -1.96587092078902;
   fWeightMatrix0to1[4][8] = 0.389319688581895;
   fWeightMatrix0to1[5][8] = -0.906727233222706;
   fWeightMatrix0to1[6][8] = 0.224763084248804;
   fWeightMatrix0to1[7][8] = 0.757433113501152;
   fWeightMatrix0to1[8][8] = 1.64074945490512;
   fWeightMatrix0to1[9][8] = -1.7186871270737;
   fWeightMatrix0to1[10][8] = 0.300900324881884;
   fWeightMatrix0to1[11][8] = 0.674101721268182;
   fWeightMatrix0to1[12][8] = 1.56938096780225;
   fWeightMatrix0to1[13][8] = 0.246201492162044;
   fWeightMatrix0to1[14][8] = -1.21109534114418;
   fWeightMatrix0to1[15][8] = -0.0599239659459166;
   fWeightMatrix0to1[0][9] = -0.918887777843766;
   fWeightMatrix0to1[1][9] = 2.36699635584169;
   fWeightMatrix0to1[2][9] = 1.5225977282741;
   fWeightMatrix0to1[3][9] = -0.696624588340154;
   fWeightMatrix0to1[4][9] = -0.833108290603971;
   fWeightMatrix0to1[5][9] = 0.621152237452193;
   fWeightMatrix0to1[6][9] = -2.0332667979947;
   fWeightMatrix0to1[7][9] = 0.383681462271792;
   fWeightMatrix0to1[8][9] = 1.73717567352393;
   fWeightMatrix0to1[9][9] = -0.572896107003113;
   fWeightMatrix0to1[10][9] = -0.387285729998793;
   fWeightMatrix0to1[11][9] = 0.575770609175191;
   fWeightMatrix0to1[12][9] = 1.2178378329838;
   fWeightMatrix0to1[13][9] = 0.125699803003118;
   fWeightMatrix0to1[14][9] = 4.38894559763027;
   fWeightMatrix0to1[15][9] = -1.70829573625426;
   fWeightMatrix0to1[0][10] = 2.03827126091127;
   fWeightMatrix0to1[1][10] = 0.644398432170745;
   fWeightMatrix0to1[2][10] = 0.729298528450418;
   fWeightMatrix0to1[3][10] = 0.332269841665104;
   fWeightMatrix0to1[4][10] = 1.01578962896046;
   fWeightMatrix0to1[5][10] = -0.0182237261832523;
   fWeightMatrix0to1[6][10] = -0.639869305353282;
   fWeightMatrix0to1[7][10] = 0.607272182212669;
   fWeightMatrix0to1[8][10] = -0.841880223851128;
   fWeightMatrix0to1[9][10] = -0.577217866859058;
   fWeightMatrix0to1[10][10] = 2.02847112103748;
   fWeightMatrix0to1[11][10] = 0.862206681346575;
   fWeightMatrix0to1[12][10] = -0.250663678770642;
   fWeightMatrix0to1[13][10] = 0.944462433505678;
   fWeightMatrix0to1[14][10] = 0.559745775146456;
   fWeightMatrix0to1[15][10] = -1.72963702563729;
   fWeightMatrix0to1[0][11] = -0.511512938042892;
   fWeightMatrix0to1[1][11] = -1.91680608352823;
   fWeightMatrix0to1[2][11] = -0.274488773438239;
   fWeightMatrix0to1[3][11] = -1.16392429836388;
   fWeightMatrix0to1[4][11] = -2.1902439942126;
   fWeightMatrix0to1[5][11] = -0.174410884623959;
   fWeightMatrix0to1[6][11] = 1.77972497967956;
   fWeightMatrix0to1[7][11] = -0.551878795841565;
   fWeightMatrix0to1[8][11] = -0.316902675666868;
   fWeightMatrix0to1[9][11] = -0.349353543012819;
   fWeightMatrix0to1[10][11] = -0.390256903001442;
   fWeightMatrix0to1[11][11] = 1.02480090956362;
   fWeightMatrix0to1[12][11] = -0.417918239042187;
   fWeightMatrix0to1[13][11] = 0.349513150395122;
   fWeightMatrix0to1[14][11] = -1.07422713736176;
   fWeightMatrix0to1[15][11] = 0.95187559589707;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0121305041789147;
   fWeightMatrix1to2[0][1] = -0.341068474559482;
   fWeightMatrix1to2[0][2] = -0.00823078508060047;
   fWeightMatrix1to2[0][3] = 0.0129590560249754;
   fWeightMatrix1to2[0][4] = -0.0561009546681086;
   fWeightMatrix1to2[0][5] = 0.0179006827380163;
   fWeightMatrix1to2[0][6] = -0.13052745926828;
   fWeightMatrix1to2[0][7] = -0.0148324362851897;
   fWeightMatrix1to2[0][8] = 0.00262249854401124;
   fWeightMatrix1to2[0][9] = -0.00913599518314208;
   fWeightMatrix1to2[0][10] = -0.00943632854920237;
   fWeightMatrix1to2[0][11] = -0.0462007397211314;
   fWeightMatrix1to2[0][12] = 0.0146317346128093;
   fWeightMatrix1to2[0][13] = -4.78712840129902e-06;
   fWeightMatrix1to2[0][14] = 0.376734376282577;
   fWeightMatrix1to2[0][15] = -0.0509020937870284;
   fWeightMatrix1to2[0][16] = 0.160306234233411;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0704743787646;
   fMax_1[0][0] = 3.28820085526;
   fMin_1[1][0] = 0.0710144713521;
   fMax_1[1][0] = 3.29991745949;
   fMin_1[2][0] = 0.0704743787646;
   fMax_1[2][0] = 3.29991745949;
   fMin_1[0][1] = 0.391374766827;
   fMax_1[0][1] = 4.73231887817;
   fMin_1[1][1] = 0.385140359402;
   fMax_1[1][1] = 4.97898674011;
   fMin_1[2][1] = 0.385140359402;
   fMax_1[2][1] = 4.97898674011;
   fMin_1[0][2] = 0.561851322651;
   fMax_1[0][2] = 4.76327848434;
   fMin_1[1][2] = 0.403012275696;
   fMax_1[1][2] = 4.83203697205;
   fMin_1[2][2] = 0.403012275696;
   fMax_1[2][2] = 4.83203697205;
   fMin_1[0][3] = 0.305736422539;
   fMax_1[0][3] = 5.5496301651;
   fMin_1[1][3] = 0.0163523908705;
   fMax_1[1][3] = 5.91814279556;
   fMin_1[2][3] = 0.0163523908705;
   fMax_1[2][3] = 5.91814279556;
   fMin_1[0][4] = 0.405655294657;
   fMax_1[0][4] = 3.19950509071;
   fMin_1[1][4] = 0.400462150574;
   fMax_1[1][4] = 3.18153500557;
   fMin_1[2][4] = 0.400462150574;
   fMax_1[2][4] = 3.19950509071;
   fMin_1[0][5] = 0.00367920775898;
   fMax_1[0][5] = 3.1411793232;
   fMin_1[1][5] = 0.000659405777697;
   fMax_1[1][5] = 3.14121699333;
   fMin_1[2][5] = 0.000659405777697;
   fMax_1[2][5] = 3.14121699333;
   fMin_1[0][6] = 5.03540611267;
   fMax_1[0][6] = 96.211151123;
   fMin_1[1][6] = 5.00658273697;
   fMax_1[1][6] = 99.9985351562;
   fMin_1[2][6] = 5.00658273697;
   fMax_1[2][6] = 99.9985351562;
   fMin_1[0][7] = 22.8492965698;
   fMax_1[0][7] = 697.742614746;
   fMin_1[1][7] = 22.1016559601;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.1016559601;
   fMax_1[2][7] = 697.742614746;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 249.548706055;
   fMin_1[1][8] = 0.0127812996507;
   fMax_1[1][8] = 249.129959106;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.548706055;
   fMin_1[0][9] = 66.7935256958;
   fMax_1[0][9] = 399.860321045;
   fMin_1[1][9] = 25.0663490295;
   fMax_1[1][9] = 395.092895508;
   fMin_1[2][9] = 25.0663490295;
   fMax_1[2][9] = 399.860321045;
   fMin_1[0][10] = 4.15161895752;
   fMax_1[0][10] = 299.960723877;
   fMin_1[1][10] = 1.33661460876;
   fMax_1[1][10] = 296.65045166;
   fMin_1[2][10] = 1.33661460876;
   fMax_1[2][10] = 299.960723877;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
