// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May 13 12:27:41 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 17420
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0717559531331,3.29683256149]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380652487278,4.91932344437]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400819450617,4.92102718353]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0285045839846,5.87358903885]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400563418865,3.17235708237]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.000525824725628,3.14151000977]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00658273697,99.9897766113]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0064582825,694.112365723]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0.0334702506661,249.843353271]
MT2                           MT2                           MT2                           MT2                                                             'F'    [25.0663490295,391.314117432]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.954420506954,299.664215088]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 0.99999988079071;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.400117450705105;
   fWeightMatrix0to1[1][0] = -0.0959214166927318;
   fWeightMatrix0to1[2][0] = -0.38932457904428;
   fWeightMatrix0to1[3][0] = 2.23464661810541;
   fWeightMatrix0to1[4][0] = -0.0532044431502027;
   fWeightMatrix0to1[5][0] = -0.965363672043639;
   fWeightMatrix0to1[6][0] = 0.116226059299375;
   fWeightMatrix0to1[7][0] = 1.05041205737614;
   fWeightMatrix0to1[8][0] = -0.249559646014896;
   fWeightMatrix0to1[9][0] = -0.948389716453704;
   fWeightMatrix0to1[10][0] = -2.06854778493909;
   fWeightMatrix0to1[11][0] = -1.0078736899182;
   fWeightMatrix0to1[12][0] = -0.48659379400666;
   fWeightMatrix0to1[13][0] = -0.285483833007599;
   fWeightMatrix0to1[14][0] = 0.275061296941705;
   fWeightMatrix0to1[15][0] = 0.841024491911849;
   fWeightMatrix0to1[0][1] = 0.183341224665211;
   fWeightMatrix0to1[1][1] = 1.07647596608401;
   fWeightMatrix0to1[2][1] = 0.586303725337783;
   fWeightMatrix0to1[3][1] = 0.964441357100677;
   fWeightMatrix0to1[4][1] = -0.553541971748763;
   fWeightMatrix0to1[5][1] = -0.270453089130126;
   fWeightMatrix0to1[6][1] = 4.21672268018109;
   fWeightMatrix0to1[7][1] = -0.264666906209322;
   fWeightMatrix0to1[8][1] = -1.42163203928209;
   fWeightMatrix0to1[9][1] = 0.0324738324306313;
   fWeightMatrix0to1[10][1] = 1.25107458616045;
   fWeightMatrix0to1[11][1] = -1.37134089139648;
   fWeightMatrix0to1[12][1] = -1.45589175182638;
   fWeightMatrix0to1[13][1] = -0.0846110465331566;
   fWeightMatrix0to1[14][1] = 0.261221508530508;
   fWeightMatrix0to1[15][1] = 1.93983139396883;
   fWeightMatrix0to1[0][2] = -0.283734401982586;
   fWeightMatrix0to1[1][2] = 0.602637109689834;
   fWeightMatrix0to1[2][2] = 0.141828715005654;
   fWeightMatrix0to1[3][2] = -0.583538559775986;
   fWeightMatrix0to1[4][2] = 0.290198534257229;
   fWeightMatrix0to1[5][2] = 1.62998125825475;
   fWeightMatrix0to1[6][2] = -0.501146320997158;
   fWeightMatrix0to1[7][2] = 0.470496694825302;
   fWeightMatrix0to1[8][2] = 1.56859172762622;
   fWeightMatrix0to1[9][2] = 0.64347669284579;
   fWeightMatrix0to1[10][2] = 1.32458976482827;
   fWeightMatrix0to1[11][2] = 0.195121822206491;
   fWeightMatrix0to1[12][2] = -0.823357415285044;
   fWeightMatrix0to1[13][2] = -1.21247073672276;
   fWeightMatrix0to1[14][2] = 0.211667895300584;
   fWeightMatrix0to1[15][2] = -0.375088858777979;
   fWeightMatrix0to1[0][3] = 1.62414631861617;
   fWeightMatrix0to1[1][3] = 0.448910481719336;
   fWeightMatrix0to1[2][3] = 0.938328722007656;
   fWeightMatrix0to1[3][3] = 1.20608153006348;
   fWeightMatrix0to1[4][3] = -0.353991878860466;
   fWeightMatrix0to1[5][3] = 1.71250982270369;
   fWeightMatrix0to1[6][3] = -1.2753003338921;
   fWeightMatrix0to1[7][3] = -1.11427853614337;
   fWeightMatrix0to1[8][3] = -0.0749711462847998;
   fWeightMatrix0to1[9][3] = -1.69407094813466;
   fWeightMatrix0to1[10][3] = 1.1867253356503;
   fWeightMatrix0to1[11][3] = 0.958816261468873;
   fWeightMatrix0to1[12][3] = -1.29978842167879;
   fWeightMatrix0to1[13][3] = 0.339701788171059;
   fWeightMatrix0to1[14][3] = 1.13625514865133;
   fWeightMatrix0to1[15][3] = 0.228434027894599;
   fWeightMatrix0to1[0][4] = 0.776054519968313;
   fWeightMatrix0to1[1][4] = -0.181745161180958;
   fWeightMatrix0to1[2][4] = -0.17275601488694;
   fWeightMatrix0to1[3][4] = -1.18966551444338;
   fWeightMatrix0to1[4][4] = 0.55009205928309;
   fWeightMatrix0to1[5][4] = -0.0877773366185876;
   fWeightMatrix0to1[6][4] = -0.181868699988101;
   fWeightMatrix0to1[7][4] = -1.25993399468791;
   fWeightMatrix0to1[8][4] = 0.728565831442086;
   fWeightMatrix0to1[9][4] = 0.720057578567906;
   fWeightMatrix0to1[10][4] = 0.849182464471753;
   fWeightMatrix0to1[11][4] = 0.330658298301733;
   fWeightMatrix0to1[12][4] = -1.39135232502142;
   fWeightMatrix0to1[13][4] = -1.69531075460809;
   fWeightMatrix0to1[14][4] = 0.420223673621163;
   fWeightMatrix0to1[15][4] = 0.0305883234441033;
   fWeightMatrix0to1[0][5] = 0.167868866316684;
   fWeightMatrix0to1[1][5] = -0.11233019195423;
   fWeightMatrix0to1[2][5] = 0.410768383522347;
   fWeightMatrix0to1[3][5] = -0.257517510757806;
   fWeightMatrix0to1[4][5] = -0.0865009006468948;
   fWeightMatrix0to1[5][5] = -0.268807821282078;
   fWeightMatrix0to1[6][5] = 0.406543204945405;
   fWeightMatrix0to1[7][5] = -0.0957414874726555;
   fWeightMatrix0to1[8][5] = -1.07226313316893;
   fWeightMatrix0to1[9][5] = -1.23607651421238;
   fWeightMatrix0to1[10][5] = -0.413634772466553;
   fWeightMatrix0to1[11][5] = -0.0470713545927456;
   fWeightMatrix0to1[12][5] = 1.47598941638238;
   fWeightMatrix0to1[13][5] = -0.897233657557471;
   fWeightMatrix0to1[14][5] = -0.116108584139072;
   fWeightMatrix0to1[15][5] = 0.470367097482176;
   fWeightMatrix0to1[0][6] = -0.851661684370694;
   fWeightMatrix0to1[1][6] = 0.322347123044258;
   fWeightMatrix0to1[2][6] = -0.607085350693372;
   fWeightMatrix0to1[3][6] = -0.228327062734826;
   fWeightMatrix0to1[4][6] = -1.76572157225606;
   fWeightMatrix0to1[5][6] = -2.06861497335076;
   fWeightMatrix0to1[6][6] = 0.3536826920695;
   fWeightMatrix0to1[7][6] = 2.02085198193107;
   fWeightMatrix0to1[8][6] = -0.902834801264983;
   fWeightMatrix0to1[9][6] = 1.48275613895167;
   fWeightMatrix0to1[10][6] = -0.211635160681119;
   fWeightMatrix0to1[11][6] = -0.132363862795689;
   fWeightMatrix0to1[12][6] = -0.706729912047023;
   fWeightMatrix0to1[13][6] = 0.147627037784269;
   fWeightMatrix0to1[14][6] = -2.14345916149795;
   fWeightMatrix0to1[15][6] = 0.501369771423044;
   fWeightMatrix0to1[0][7] = 0.430917125178533;
   fWeightMatrix0to1[1][7] = -2.19848874341654;
   fWeightMatrix0to1[2][7] = -4.13338279278722;
   fWeightMatrix0to1[3][7] = 0.502199496758468;
   fWeightMatrix0to1[4][7] = -0.165509984711589;
   fWeightMatrix0to1[5][7] = 0.461169780169666;
   fWeightMatrix0to1[6][7] = 1.63525531068788;
   fWeightMatrix0to1[7][7] = -2.35829740257262;
   fWeightMatrix0to1[8][7] = -1.55338035874204;
   fWeightMatrix0to1[9][7] = -0.126158630886955;
   fWeightMatrix0to1[10][7] = -0.166603982951611;
   fWeightMatrix0to1[11][7] = 1.61436310806048;
   fWeightMatrix0to1[12][7] = 0.943290106667869;
   fWeightMatrix0to1[13][7] = -0.787792707860841;
   fWeightMatrix0to1[14][7] = -0.681425763960366;
   fWeightMatrix0to1[15][7] = 0.586469203116996;
   fWeightMatrix0to1[0][8] = -2.01002186510521;
   fWeightMatrix0to1[1][8] = -0.333878566783698;
   fWeightMatrix0to1[2][8] = -0.719288173165401;
   fWeightMatrix0to1[3][8] = -1.49459644916523;
   fWeightMatrix0to1[4][8] = 1.62467494995479;
   fWeightMatrix0to1[5][8] = -0.101298643276447;
   fWeightMatrix0to1[6][8] = 0.234074387894959;
   fWeightMatrix0to1[7][8] = 1.27953170541854;
   fWeightMatrix0to1[8][8] = 0.59062359539722;
   fWeightMatrix0to1[9][8] = -1.65942857230193;
   fWeightMatrix0to1[10][8] = 0.193745719363143;
   fWeightMatrix0to1[11][8] = -0.209256581725506;
   fWeightMatrix0to1[12][8] = 1.45215003268584;
   fWeightMatrix0to1[13][8] = -0.115902608941233;
   fWeightMatrix0to1[14][8] = -1.92176696018162;
   fWeightMatrix0to1[15][8] = 0.0416903347294919;
   fWeightMatrix0to1[0][9] = -2.2424769774551;
   fWeightMatrix0to1[1][9] = 3.35033348988122;
   fWeightMatrix0to1[2][9] = 3.99156098389199;
   fWeightMatrix0to1[3][9] = -1.34984199898559;
   fWeightMatrix0to1[4][9] = -0.950668748388903;
   fWeightMatrix0to1[5][9] = 0.962644693463054;
   fWeightMatrix0to1[6][9] = -1.88425026020164;
   fWeightMatrix0to1[7][9] = 0.082241630205641;
   fWeightMatrix0to1[8][9] = 2.1977545029509;
   fWeightMatrix0to1[9][9] = -0.574979929640003;
   fWeightMatrix0to1[10][9] = -0.132060589811495;
   fWeightMatrix0to1[11][9] = 0.744313851125978;
   fWeightMatrix0to1[12][9] = 1.31544539747914;
   fWeightMatrix0to1[13][9] = -0.260740773468786;
   fWeightMatrix0to1[14][9] = 0.810613117376914;
   fWeightMatrix0to1[15][9] = -1.27930000040236;
   fWeightMatrix0to1[0][10] = 1.11611606029688;
   fWeightMatrix0to1[1][10] = 1.26001101760076;
   fWeightMatrix0to1[2][10] = 1.31349086081294;
   fWeightMatrix0to1[3][10] = -0.209967325822076;
   fWeightMatrix0to1[4][10] = 0.554825400219492;
   fWeightMatrix0to1[5][10] = 0.791249904019601;
   fWeightMatrix0to1[6][10] = 0.568204168904535;
   fWeightMatrix0to1[7][10] = -0.0470902936852776;
   fWeightMatrix0to1[8][10] = -0.666982820755199;
   fWeightMatrix0to1[9][10] = -0.619583334828678;
   fWeightMatrix0to1[10][10] = 1.28218769861534;
   fWeightMatrix0to1[11][10] = 0.0461585970026223;
   fWeightMatrix0to1[12][10] = -0.295037040321258;
   fWeightMatrix0to1[13][10] = 0.73173162106963;
   fWeightMatrix0to1[14][10] = 0.755367353532554;
   fWeightMatrix0to1[15][10] = -1.47950596808881;
   fWeightMatrix0to1[0][11] = -2.01845534289387;
   fWeightMatrix0to1[1][11] = -1.24884255859618;
   fWeightMatrix0to1[2][11] = -1.99566082629816;
   fWeightMatrix0to1[3][11] = -0.0778192279439973;
   fWeightMatrix0to1[4][11] = -1.76567965629969;
   fWeightMatrix0to1[5][11] = -0.92123831928337;
   fWeightMatrix0to1[6][11] = 3.90841639135666;
   fWeightMatrix0to1[7][11] = 0.0734901172943999;
   fWeightMatrix0to1[8][11] = -0.495355854439564;
   fWeightMatrix0to1[9][11] = 0.25532726350776;
   fWeightMatrix0to1[10][11] = -0.31101504388851;
   fWeightMatrix0to1[11][11] = -0.543176016797905;
   fWeightMatrix0to1[12][11] = 0.0392163258390233;
   fWeightMatrix0to1[13][11] = 0.546775037647232;
   fWeightMatrix0to1[14][11] = -0.823936074657627;
   fWeightMatrix0to1[15][11] = 0.800944078409596;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.205117148020749;
   fWeightMatrix1to2[0][1] = -0.529896349551331;
   fWeightMatrix1to2[0][2] = 0.483121452603998;
   fWeightMatrix1to2[0][3] = 0.0474715009524053;
   fWeightMatrix1to2[0][4] = -0.12699540350913;
   fWeightMatrix1to2[0][5] = -0.182392591063696;
   fWeightMatrix1to2[0][6] = 0.283756399257248;
   fWeightMatrix1to2[0][7] = 0.0774489056488521;
   fWeightMatrix1to2[0][8] = 0.0721368426982032;
   fWeightMatrix1to2[0][9] = 0.0208582829189368;
   fWeightMatrix1to2[0][10] = 0.117808323758106;
   fWeightMatrix1to2[0][11] = 0.410380430551071;
   fWeightMatrix1to2[0][12] = 0.0240941504343589;
   fWeightMatrix1to2[0][13] = -0.00979696113609621;
   fWeightMatrix1to2[0][14] = 0.24212602694205;
   fWeightMatrix1to2[0][15] = -0.0386366724351045;
   fWeightMatrix1to2[0][16] = -0.0901581665981282;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0717559531331;
   fMax_1[0][0] = 3.25879645348;
   fMin_1[1][0] = 0.0744008347392;
   fMax_1[1][0] = 3.29683256149;
   fMin_1[2][0] = 0.0717559531331;
   fMax_1[2][0] = 3.29683256149;
   fMin_1[0][1] = 0.395848423243;
   fMax_1[0][1] = 4.90018987656;
   fMin_1[1][1] = 0.380652487278;
   fMax_1[1][1] = 4.91932344437;
   fMin_1[2][1] = 0.380652487278;
   fMax_1[2][1] = 4.91932344437;
   fMin_1[0][2] = 0.42405718565;
   fMax_1[0][2] = 4.92102718353;
   fMin_1[1][2] = 0.400819450617;
   fMax_1[1][2] = 4.78586483002;
   fMin_1[2][2] = 0.400819450617;
   fMax_1[2][2] = 4.92102718353;
   fMin_1[0][3] = 0.259432077408;
   fMax_1[0][3] = 5.75387620926;
   fMin_1[1][3] = 0.0285045839846;
   fMax_1[1][3] = 5.87358903885;
   fMin_1[2][3] = 0.0285045839846;
   fMax_1[2][3] = 5.87358903885;
   fMin_1[0][4] = 0.404076904058;
   fMax_1[0][4] = 3.1550784111;
   fMin_1[1][4] = 0.400563418865;
   fMax_1[1][4] = 3.17235708237;
   fMin_1[2][4] = 0.400563418865;
   fMax_1[2][4] = 3.17235708237;
   fMin_1[0][5] = 0.00109035370406;
   fMax_1[0][5] = 3.14151000977;
   fMin_1[1][5] = 0.000525824725628;
   fMax_1[1][5] = 3.14138936996;
   fMin_1[2][5] = 0.000525824725628;
   fMax_1[2][5] = 3.14151000977;
   fMin_1[0][6] = 5.09243822098;
   fMax_1[0][6] = 91.6413192749;
   fMin_1[1][6] = 5.00658273697;
   fMax_1[1][6] = 99.9897766113;
   fMin_1[2][6] = 5.00658273697;
   fMax_1[2][6] = 99.9897766113;
   fMin_1[0][7] = 22.0064582825;
   fMax_1[0][7] = 691.564147949;
   fMin_1[1][7] = 22.1016559601;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.0064582825;
   fMax_1[2][7] = 694.112365723;
   fMin_1[0][8] = 0.0840331763029;
   fMax_1[0][8] = 248.512664795;
   fMin_1[1][8] = 0.0334702506661;
   fMax_1[1][8] = 249.843353271;
   fMin_1[2][8] = 0.0334702506661;
   fMax_1[2][8] = 249.843353271;
   fMin_1[0][9] = 53.6448020935;
   fMax_1[0][9] = 385.469360352;
   fMin_1[1][9] = 25.0663490295;
   fMax_1[1][9] = 391.314117432;
   fMin_1[2][9] = 25.0663490295;
   fMax_1[2][9] = 391.314117432;
   fMin_1[0][10] = 4.02555608749;
   fMax_1[0][10] = 299.664215088;
   fMin_1[1][10] = 0.954420506954;
   fMax_1[1][10] = 298.342681885;
   fMin_1[2][10] = 0.954420506954;
   fMax_1[2][10] = 299.664215088;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
