// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May  6 12:26:58 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 18443
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0700357034802,3.29991745949]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380652487278,4.95207595825]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400819450617,4.91523265839]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0163523908705,5.91814279556]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400697886944,3.17182016373]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.00037625504774,3.14154648781]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.01443195343,99.9985351562]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.002456665,694.112365723]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0.0127812996507,249.397186279]
MT2                           MT2                           MT2                           MT2                                                             'F'    [25.0663490295,392.435821533]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.660549879074,299.668151855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.218837127052023;
   fWeightMatrix0to1[1][0] = 0.421138729668775;
   fWeightMatrix0to1[2][0] = -0.231736829952472;
   fWeightMatrix0to1[3][0] = 1.96748812087351;
   fWeightMatrix0to1[4][0] = -0.855323546750723;
   fWeightMatrix0to1[5][0] = -0.816306402989268;
   fWeightMatrix0to1[6][0] = -0.293196621115092;
   fWeightMatrix0to1[7][0] = 1.39551425778702;
   fWeightMatrix0to1[8][0] = -1.09286029491485;
   fWeightMatrix0to1[9][0] = -0.953593967396232;
   fWeightMatrix0to1[10][0] = -1.14441359865273;
   fWeightMatrix0to1[11][0] = 0.4603720012946;
   fWeightMatrix0to1[12][0] = -0.393576576646327;
   fWeightMatrix0to1[13][0] = -0.540868496106401;
   fWeightMatrix0to1[14][0] = -0.608899360006379;
   fWeightMatrix0to1[15][0] = 1.56303596427799;
   fWeightMatrix0to1[0][1] = -0.382009002513709;
   fWeightMatrix0to1[1][1] = 1.5267602221827;
   fWeightMatrix0to1[2][1] = 1.08414855066161;
   fWeightMatrix0to1[3][1] = 1.14856001419214;
   fWeightMatrix0to1[4][1] = -0.691485089809149;
   fWeightMatrix0to1[5][1] = -0.3718353777026;
   fWeightMatrix0to1[6][1] = 0.549679340872505;
   fWeightMatrix0to1[7][1] = -0.222769317743305;
   fWeightMatrix0to1[8][1] = -1.01876387820568;
   fWeightMatrix0to1[9][1] = -0.101549607681037;
   fWeightMatrix0to1[10][1] = 1.28561825204886;
   fWeightMatrix0to1[11][1] = -1.38122790735359;
   fWeightMatrix0to1[12][1] = -1.48020217373716;
   fWeightMatrix0to1[13][1] = -0.136915267114135;
   fWeightMatrix0to1[14][1] = 0.507029459712464;
   fWeightMatrix0to1[15][1] = 1.38298359713345;
   fWeightMatrix0to1[0][2] = 0.153915228878939;
   fWeightMatrix0to1[1][2] = 0.584733461314183;
   fWeightMatrix0to1[2][2] = 1.16051255307584;
   fWeightMatrix0to1[3][2] = -0.197227098206646;
   fWeightMatrix0to1[4][2] = -0.438539432561365;
   fWeightMatrix0to1[5][2] = 2.14956424944661;
   fWeightMatrix0to1[6][2] = -0.572539534977498;
   fWeightMatrix0to1[7][2] = 0.700532006206281;
   fWeightMatrix0to1[8][2] = 1.18714784680143;
   fWeightMatrix0to1[9][2] = 0.863209419895892;
   fWeightMatrix0to1[10][2] = 1.70079764162914;
   fWeightMatrix0to1[11][2] = 0.216530214755874;
   fWeightMatrix0to1[12][2] = -0.614987988721528;
   fWeightMatrix0to1[13][2] = -1.43240304525396;
   fWeightMatrix0to1[14][2] = 0.304037707969572;
   fWeightMatrix0to1[15][2] = 0.0440105101319988;
   fWeightMatrix0to1[0][3] = 1.70940259763425;
   fWeightMatrix0to1[1][3] = 1.66961595027625;
   fWeightMatrix0to1[2][3] = 2.20600894617187;
   fWeightMatrix0to1[3][3] = 1.2304240504437;
   fWeightMatrix0to1[4][3] = -0.923078868023944;
   fWeightMatrix0to1[5][3] = 1.87607241056515;
   fWeightMatrix0to1[6][3] = -0.898636229359508;
   fWeightMatrix0to1[7][3] = -1.0213364008096;
   fWeightMatrix0to1[8][3] = -1.17190081056741;
   fWeightMatrix0to1[9][3] = -1.73240878500749;
   fWeightMatrix0to1[10][3] = 1.41390245445888;
   fWeightMatrix0to1[11][3] = 0.923959696904956;
   fWeightMatrix0to1[12][3] = -1.99683070578841;
   fWeightMatrix0to1[13][3] = 0.272691044396032;
   fWeightMatrix0to1[14][3] = 1.1858847326761;
   fWeightMatrix0to1[15][3] = 0.46037238645626;
   fWeightMatrix0to1[0][4] = 1.9439938437783;
   fWeightMatrix0to1[1][4] = -1.03591152890848;
   fWeightMatrix0to1[2][4] = -0.201215353922669;
   fWeightMatrix0to1[3][4] = -1.47820736075213;
   fWeightMatrix0to1[4][4] = 0.857322077272662;
   fWeightMatrix0to1[5][4] = -0.0679930363338371;
   fWeightMatrix0to1[6][4] = 0.0870019415104605;
   fWeightMatrix0to1[7][4] = -1.70370301436581;
   fWeightMatrix0to1[8][4] = 0.67623004945419;
   fWeightMatrix0to1[9][4] = 0.686427793885651;
   fWeightMatrix0to1[10][4] = 1.23926864657929;
   fWeightMatrix0to1[11][4] = -0.350874988334602;
   fWeightMatrix0to1[12][4] = -1.92613545814078;
   fWeightMatrix0to1[13][4] = -1.76743758051435;
   fWeightMatrix0to1[14][4] = 0.117734909010308;
   fWeightMatrix0to1[15][4] = 0.162497552234628;
   fWeightMatrix0to1[0][5] = 0.816306276264792;
   fWeightMatrix0to1[1][5] = -0.467534081072889;
   fWeightMatrix0to1[2][5] = -0.604257743288125;
   fWeightMatrix0to1[3][5] = -0.500135304182027;
   fWeightMatrix0to1[4][5] = 0.167241001467969;
   fWeightMatrix0to1[5][5] = -0.497439072494892;
   fWeightMatrix0to1[6][5] = 0.141244693105094;
   fWeightMatrix0to1[7][5] = -0.216522313312958;
   fWeightMatrix0to1[8][5] = -1.60513718305752;
   fWeightMatrix0to1[9][5] = -1.35070752669424;
   fWeightMatrix0to1[10][5] = -0.62591540864199;
   fWeightMatrix0to1[11][5] = 0.106534607032867;
   fWeightMatrix0to1[12][5] = 0.935022804800604;
   fWeightMatrix0to1[13][5] = -1.01015177936057;
   fWeightMatrix0to1[14][5] = 0.125281017067104;
   fWeightMatrix0to1[15][5] = 0.725371652284506;
   fWeightMatrix0to1[0][6] = -0.510382920877847;
   fWeightMatrix0to1[1][6] = -0.328257999920683;
   fWeightMatrix0to1[2][6] = -0.782868972880064;
   fWeightMatrix0to1[3][6] = -0.198025062863462;
   fWeightMatrix0to1[4][6] = -1.72234907642837;
   fWeightMatrix0to1[5][6] = -1.37854050981075;
   fWeightMatrix0to1[6][6] = -1.70572647854064;
   fWeightMatrix0to1[7][6] = 1.90332756630154;
   fWeightMatrix0to1[8][6] = -0.870739051435306;
   fWeightMatrix0to1[9][6] = 1.60821404769559;
   fWeightMatrix0to1[10][6] = -0.5655546713116;
   fWeightMatrix0to1[11][6] = 0.719991345677029;
   fWeightMatrix0to1[12][6] = -0.374481717025507;
   fWeightMatrix0to1[13][6] = 0.271315205935758;
   fWeightMatrix0to1[14][6] = -0.920820654837189;
   fWeightMatrix0to1[15][6] = 0.95443566669069;
   fWeightMatrix0to1[0][7] = 0.774393491913048;
   fWeightMatrix0to1[1][7] = -1.16311541103086;
   fWeightMatrix0to1[2][7] = -1.64647568425219;
   fWeightMatrix0to1[3][7] = 0.978005476098346;
   fWeightMatrix0to1[4][7] = 0.159305532101673;
   fWeightMatrix0to1[5][7] = 0.0475745178973764;
   fWeightMatrix0to1[6][7] = 1.04505109134479;
   fWeightMatrix0to1[7][7] = -2.117221069026;
   fWeightMatrix0to1[8][7] = -1.29148273519208;
   fWeightMatrix0to1[9][7] = -0.140750048720399;
   fWeightMatrix0to1[10][7] = -0.0763686651771433;
   fWeightMatrix0to1[11][7] = -0.371902197933597;
   fWeightMatrix0to1[12][7] = 0.539014205868321;
   fWeightMatrix0to1[13][7] = -0.89922806673715;
   fWeightMatrix0to1[14][7] = -4.65723738639364;
   fWeightMatrix0to1[15][7] = 0.195233726841359;
   fWeightMatrix0to1[0][8] = -1.20715200329136;
   fWeightMatrix0to1[1][8] = 0.610168127134585;
   fWeightMatrix0to1[2][8] = -0.760873416812816;
   fWeightMatrix0to1[3][8] = -1.97251538655637;
   fWeightMatrix0to1[4][8] = 0.594676219950775;
   fWeightMatrix0to1[5][8] = -0.606777161184721;
   fWeightMatrix0to1[6][8] = 0.25661084239473;
   fWeightMatrix0to1[7][8] = 0.778405269419663;
   fWeightMatrix0to1[8][8] = 1.54309625523247;
   fWeightMatrix0to1[9][8] = -1.48037175272823;
   fWeightMatrix0to1[10][8] = 0.285429545956306;
   fWeightMatrix0to1[11][8] = 0.472807110468858;
   fWeightMatrix0to1[12][8] = 1.84550549020072;
   fWeightMatrix0to1[13][8] = 0.0327524224339523;
   fWeightMatrix0to1[14][8] = -1.22409479080859;
   fWeightMatrix0to1[15][8] = 0.0158538943406554;
   fWeightMatrix0to1[0][9] = -0.778082468102512;
   fWeightMatrix0to1[1][9] = 2.59236933245013;
   fWeightMatrix0to1[2][9] = 4.48281704405979;
   fWeightMatrix0to1[3][9] = -1.13450530017437;
   fWeightMatrix0to1[4][9] = -1.05215319808235;
   fWeightMatrix0to1[5][9] = 0.656646656334803;
   fWeightMatrix0to1[6][9] = -2.10987154184289;
   fWeightMatrix0to1[7][9] = 0.303232193091058;
   fWeightMatrix0to1[8][9] = 1.8463736410728;
   fWeightMatrix0to1[9][9] = -0.686622563300108;
   fWeightMatrix0to1[10][9] = -0.395808432386072;
   fWeightMatrix0to1[11][9] = -0.616211046037561;
   fWeightMatrix0to1[12][9] = 0.590507472864326;
   fWeightMatrix0to1[13][9] = -0.116553393348568;
   fWeightMatrix0to1[14][9] = 4.3949838638937;
   fWeightMatrix0to1[15][9] = -1.54291991282937;
   fWeightMatrix0to1[0][10] = 2.08253745487629;
   fWeightMatrix0to1[1][10] = 1.1245314220455;
   fWeightMatrix0to1[2][10] = 1.40010754147875;
   fWeightMatrix0to1[3][10] = 0.0409384960321201;
   fWeightMatrix0to1[4][10] = 0.751878585834333;
   fWeightMatrix0to1[5][10] = -0.0655786314859706;
   fWeightMatrix0to1[6][10] = -0.520755051100693;
   fWeightMatrix0to1[7][10] = 0.400251903563989;
   fWeightMatrix0to1[8][10] = -0.766106691117627;
   fWeightMatrix0to1[9][10] = -0.761655820144998;
   fWeightMatrix0to1[10][10] = 1.87243087684254;
   fWeightMatrix0to1[11][10] = -0.303165216908651;
   fWeightMatrix0to1[12][10] = -0.378571744224848;
   fWeightMatrix0to1[13][10] = 0.69865481749433;
   fWeightMatrix0to1[14][10] = 1.41995556250869;
   fWeightMatrix0to1[15][10] = -1.69240780405861;
   fWeightMatrix0to1[0][11] = -0.840841258752505;
   fWeightMatrix0to1[1][11] = -0.529711437860349;
   fWeightMatrix0to1[2][11] = 0.936537427771115;
   fWeightMatrix0to1[3][11] = -0.360306887140196;
   fWeightMatrix0to1[4][11] = -2.24941618659793;
   fWeightMatrix0to1[5][11] = -1.04052992317212;
   fWeightMatrix0to1[6][11] = 2.81562327585041;
   fWeightMatrix0to1[7][11] = 0.25190729935926;
   fWeightMatrix0to1[8][11] = -0.553144082825194;
   fWeightMatrix0to1[9][11] = 0.126356268560664;
   fWeightMatrix0to1[10][11] = -0.351388965035052;
   fWeightMatrix0to1[11][11] = 2.74220328849804;
   fWeightMatrix0to1[12][11] = 0.571792695675856;
   fWeightMatrix0to1[13][11] = 0.66938780987639;
   fWeightMatrix0to1[14][11] = -2.72677290119357;
   fWeightMatrix0to1[15][11] = 0.793593309557922;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.031614231180225;
   fWeightMatrix1to2[0][1] = -0.210629370101338;
   fWeightMatrix1to2[0][2] = 0.205569205571165;
   fWeightMatrix1to2[0][3] = 0.021370168415965;
   fWeightMatrix1to2[0][4] = -0.0858405718610122;
   fWeightMatrix1to2[0][5] = -0.0676961229585793;
   fWeightMatrix1to2[0][6] = 0.398779525314465;
   fWeightMatrix1to2[0][7] = -0.0201807655725848;
   fWeightMatrix1to2[0][8] = 0.00578160086119517;
   fWeightMatrix1to2[0][9] = -0.00769136595550975;
   fWeightMatrix1to2[0][10] = 0.0355690467344863;
   fWeightMatrix1to2[0][11] = -0.709625090754143;
   fWeightMatrix1to2[0][12] = 0.0379551201461583;
   fWeightMatrix1to2[0][13] = -0.0113340206725491;
   fWeightMatrix1to2[0][14] = 0.378116676042435;
   fWeightMatrix1to2[0][15] = -0.0246428613137096;
   fWeightMatrix1to2[0][16] = 0.5714596852273;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0700357034802;
   fMax_1[0][0] = 3.27965116501;
   fMin_1[1][0] = 0.0796247571707;
   fMax_1[1][0] = 3.29991745949;
   fMin_1[2][0] = 0.0700357034802;
   fMax_1[2][0] = 3.29991745949;
   fMin_1[0][1] = 0.39005368948;
   fMax_1[0][1] = 4.80312728882;
   fMin_1[1][1] = 0.380652487278;
   fMax_1[1][1] = 4.95207595825;
   fMin_1[2][1] = 0.380652487278;
   fMax_1[2][1] = 4.95207595825;
   fMin_1[0][2] = 0.475951552391;
   fMax_1[0][2] = 4.54190635681;
   fMin_1[1][2] = 0.400819450617;
   fMax_1[1][2] = 4.91523265839;
   fMin_1[2][2] = 0.400819450617;
   fMax_1[2][2] = 4.91523265839;
   fMin_1[0][3] = 0.288734763861;
   fMax_1[0][3] = 5.59597015381;
   fMin_1[1][3] = 0.0163523908705;
   fMax_1[1][3] = 5.91814279556;
   fMin_1[2][3] = 0.0163523908705;
   fMax_1[2][3] = 5.91814279556;
   fMin_1[0][4] = 0.403152883053;
   fMax_1[0][4] = 3.17182016373;
   fMin_1[1][4] = 0.400697886944;
   fMax_1[1][4] = 3.13782835007;
   fMin_1[2][4] = 0.400697886944;
   fMax_1[2][4] = 3.17182016373;
   fMin_1[0][5] = 0.0344244167209;
   fMax_1[0][5] = 3.14154648781;
   fMin_1[1][5] = 0.00037625504774;
   fMax_1[1][5] = 3.14149975777;
   fMin_1[2][5] = 0.00037625504774;
   fMax_1[2][5] = 3.14154648781;
   fMin_1[0][6] = 5.01443195343;
   fMax_1[0][6] = 98.743522644;
   fMin_1[1][6] = 5.01698303223;
   fMax_1[1][6] = 99.9985351562;
   fMin_1[2][6] = 5.01443195343;
   fMax_1[2][6] = 99.9985351562;
   fMin_1[0][7] = 22.2487831116;
   fMax_1[0][7] = 691.662414551;
   fMin_1[1][7] = 22.002456665;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.002456665;
   fMax_1[2][7] = 694.112365723;
   fMin_1[0][8] = 0.0236637573689;
   fMax_1[0][8] = 248.594039917;
   fMin_1[1][8] = 0.0127812996507;
   fMax_1[1][8] = 249.397186279;
   fMin_1[2][8] = 0.0127812996507;
   fMax_1[2][8] = 249.397186279;
   fMin_1[0][9] = 56.6907806396;
   fMax_1[0][9] = 392.435821533;
   fMin_1[1][9] = 25.0663490295;
   fMax_1[1][9] = 391.314117432;
   fMin_1[2][9] = 25.0663490295;
   fMax_1[2][9] = 392.435821533;
   fMin_1[0][10] = 5.08085107803;
   fMax_1[0][10] = 299.668151855;
   fMin_1[1][10] = 0.660549879074;
   fMax_1[1][10] = 297.30456543;
   fMin_1[2][10] = 0.660549879074;
   fMax_1[2][10] = 299.668151855;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
