// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May  6 12:20:46 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 17926
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0710297822952,3.29906010628]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.394397765398,4.95207595825]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400819450617,4.82403278351]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0285045839846,5.91814279556]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400462150574,3.18627643585]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.000525824725628,3.14152812958]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.0063123703,99.9996490479]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.1016559601,694.112365723]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0.0199588146061,249.843353271]
MT2                           MT2                           MT2                           MT2                                                             'F'    [32.4793205261,395.929016113]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.954420506954,298.936981201]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -1.24150580651398;
   fWeightMatrix0to1[1][0] = 0.33746860968096;
   fWeightMatrix0to1[2][0] = -0.598816427952684;
   fWeightMatrix0to1[3][0] = 1.53858044012765;
   fWeightMatrix0to1[4][0] = -0.334539910666833;
   fWeightMatrix0to1[5][0] = -1.54026493978321;
   fWeightMatrix0to1[6][0] = -0.0303676292618767;
   fWeightMatrix0to1[7][0] = 1.44830007585338;
   fWeightMatrix0to1[8][0] = -1.37529464338603;
   fWeightMatrix0to1[9][0] = 1.91414813897395;
   fWeightMatrix0to1[10][0] = -0.760350631460149;
   fWeightMatrix0to1[11][0] = 0.78863954572255;
   fWeightMatrix0to1[12][0] = -1.08832629850204;
   fWeightMatrix0to1[13][0] = -1.28786748910506;
   fWeightMatrix0to1[14][0] = -0.128414754067587;
   fWeightMatrix0to1[15][0] = 0.0366484960360549;
   fWeightMatrix0to1[0][1] = -0.0183772600797425;
   fWeightMatrix0to1[1][1] = 1.28602332392057;
   fWeightMatrix0to1[2][1] = 1.79087407873521;
   fWeightMatrix0to1[3][1] = 1.46796591140751;
   fWeightMatrix0to1[4][1] = -0.15199487829954;
   fWeightMatrix0to1[5][1] = 0.230158490916109;
   fWeightMatrix0to1[6][1] = -0.536399496687021;
   fWeightMatrix0to1[7][1] = 0.158334577612976;
   fWeightMatrix0to1[8][1] = -1.21984533572701;
   fWeightMatrix0to1[9][1] = 0.583161816826691;
   fWeightMatrix0to1[10][1] = 1.98175829202143;
   fWeightMatrix0to1[11][1] = -1.07019326017868;
   fWeightMatrix0to1[12][1] = -3.38379144426811;
   fWeightMatrix0to1[13][1] = 1.21959000124591;
   fWeightMatrix0to1[14][1] = -1.02823048862385;
   fWeightMatrix0to1[15][1] = 9.27272047709848;
   fWeightMatrix0to1[0][2] = -0.0256827149944314;
   fWeightMatrix0to1[1][2] = 0.237040704115381;
   fWeightMatrix0to1[2][2] = 0.711147261788727;
   fWeightMatrix0to1[3][2] = -0.177383848067837;
   fWeightMatrix0to1[4][2] = -0.640075796194078;
   fWeightMatrix0to1[5][2] = 2.27919336351361;
   fWeightMatrix0to1[6][2] = 0.0325424888016687;
   fWeightMatrix0to1[7][2] = 0.13571408948018;
   fWeightMatrix0to1[8][2] = 1.05762947273202;
   fWeightMatrix0to1[9][2] = 0.153300406909951;
   fWeightMatrix0to1[10][2] = 0.816964792841848;
   fWeightMatrix0to1[11][2] = -0.206814335805912;
   fWeightMatrix0to1[12][2] = 0.611041924557927;
   fWeightMatrix0to1[13][2] = -1.59164475861119;
   fWeightMatrix0to1[14][2] = 0.352580099923161;
   fWeightMatrix0to1[15][2] = -0.321102467616865;
   fWeightMatrix0to1[0][3] = 1.36406683432899;
   fWeightMatrix0to1[1][3] = 1.76698418734895;
   fWeightMatrix0to1[2][3] = 0.700154929358454;
   fWeightMatrix0to1[3][3] = 1.29046175698202;
   fWeightMatrix0to1[4][3] = -0.366149464086189;
   fWeightMatrix0to1[5][3] = 1.83304087140769;
   fWeightMatrix0to1[6][3] = -0.979189377811198;
   fWeightMatrix0to1[7][3] = 1.282782572045;
   fWeightMatrix0to1[8][3] = -1.32169578436515;
   fWeightMatrix0to1[9][3] = -0.581630778541146;
   fWeightMatrix0to1[10][3] = 2.41904315012032;
   fWeightMatrix0to1[11][3] = -0.640471083904468;
   fWeightMatrix0to1[12][3] = 0.726135215756089;
   fWeightMatrix0to1[13][3] = -0.597704135254901;
   fWeightMatrix0to1[14][3] = 2.5358358413249;
   fWeightMatrix0to1[15][3] = -2.37616903824166;
   fWeightMatrix0to1[0][4] = 0.308870075399088;
   fWeightMatrix0to1[1][4] = -0.463198056055543;
   fWeightMatrix0to1[2][4] = 0.0351304410866552;
   fWeightMatrix0to1[3][4] = -1.10595210539354;
   fWeightMatrix0to1[4][4] = 0.252947728273878;
   fWeightMatrix0to1[5][4] = -0.49397585042094;
   fWeightMatrix0to1[6][4] = 0.369356766460176;
   fWeightMatrix0to1[7][4] = -0.55839827770339;
   fWeightMatrix0to1[8][4] = 0.521905936452612;
   fWeightMatrix0to1[9][4] = 1.52484251874747;
   fWeightMatrix0to1[10][4] = 0.145165631315339;
   fWeightMatrix0to1[11][4] = 0.418431043157716;
   fWeightMatrix0to1[12][4] = 0.152541042694808;
   fWeightMatrix0to1[13][4] = -1.7752474024524;
   fWeightMatrix0to1[14][4] = 0.00976061700492029;
   fWeightMatrix0to1[15][4] = 0.432427193188424;
   fWeightMatrix0to1[0][5] = 0.241546617105873;
   fWeightMatrix0to1[1][5] = -1.05079369208647;
   fWeightMatrix0to1[2][5] = 0.145893524504568;
   fWeightMatrix0to1[3][5] = -1.18802562942145;
   fWeightMatrix0to1[4][5] = -0.449443760086674;
   fWeightMatrix0to1[5][5] = -0.0920544403163453;
   fWeightMatrix0to1[6][5] = -0.740614320261323;
   fWeightMatrix0to1[7][5] = -0.346966829541462;
   fWeightMatrix0to1[8][5] = -1.64579985116685;
   fWeightMatrix0to1[9][5] = -3.74598528170407;
   fWeightMatrix0to1[10][5] = 0.624773153780722;
   fWeightMatrix0to1[11][5] = -0.798242867289801;
   fWeightMatrix0to1[12][5] = 0.00341780120602969;
   fWeightMatrix0to1[13][5] = -1.44556874640461;
   fWeightMatrix0to1[14][5] = -0.899885361023926;
   fWeightMatrix0to1[15][5] = 1.11098124149182;
   fWeightMatrix0to1[0][6] = -1.04818503834195;
   fWeightMatrix0to1[1][6] = 0.43510106345324;
   fWeightMatrix0to1[2][6] = -1.16874478006536;
   fWeightMatrix0to1[3][6] = 0.192529458259261;
   fWeightMatrix0to1[4][6] = -2.66339652663924;
   fWeightMatrix0to1[5][6] = -1.01212141014487;
   fWeightMatrix0to1[6][6] = -3.30110682372977;
   fWeightMatrix0to1[7][6] = 3.08849287762191;
   fWeightMatrix0to1[8][6] = -1.18496875981526;
   fWeightMatrix0to1[9][6] = 0.493987283868186;
   fWeightMatrix0to1[10][6] = -2.36710504248968;
   fWeightMatrix0to1[11][6] = -1.22647827488032;
   fWeightMatrix0to1[12][6] = -0.763415530218817;
   fWeightMatrix0to1[13][6] = -0.481589917098252;
   fWeightMatrix0to1[14][6] = -0.571506368538077;
   fWeightMatrix0to1[15][6] = -0.683515307355433;
   fWeightMatrix0to1[0][7] = 0.336655160038457;
   fWeightMatrix0to1[1][7] = -3.3449591163265;
   fWeightMatrix0to1[2][7] = -5.14359951673714;
   fWeightMatrix0to1[3][7] = 1.70360931607776;
   fWeightMatrix0to1[4][7] = -0.343116051784049;
   fWeightMatrix0to1[5][7] = -0.204600741382201;
   fWeightMatrix0to1[6][7] = 1.81234553371767;
   fWeightMatrix0to1[7][7] = -1.15323276533999;
   fWeightMatrix0to1[8][7] = -1.68205161350974;
   fWeightMatrix0to1[9][7] = -2.71631002472399;
   fWeightMatrix0to1[10][7] = -0.346208887151096;
   fWeightMatrix0to1[11][7] = 0.816175770576005;
   fWeightMatrix0to1[12][7] = -0.79855979102645;
   fWeightMatrix0to1[13][7] = 0.749795479749839;
   fWeightMatrix0to1[14][7] = -10.6535312603238;
   fWeightMatrix0to1[15][7] = 2.67986221573575;
   fWeightMatrix0to1[0][8] = -5.51681168327929;
   fWeightMatrix0to1[1][8] = 0.34403725587134;
   fWeightMatrix0to1[2][8] = -1.95683337174808;
   fWeightMatrix0to1[3][8] = -1.67518399284096;
   fWeightMatrix0to1[4][8] = 0.281184723943414;
   fWeightMatrix0to1[5][8] = -0.842194257203425;
   fWeightMatrix0to1[6][8] = 0.940285227549535;
   fWeightMatrix0to1[7][8] = 0.524650907825725;
   fWeightMatrix0to1[8][8] = 1.53535780282553;
   fWeightMatrix0to1[9][8] = -1.19977455517419;
   fWeightMatrix0to1[10][8] = -0.462445004570918;
   fWeightMatrix0to1[11][8] = 4.24695540373617;
   fWeightMatrix0to1[12][8] = -1.77865435553103;
   fWeightMatrix0to1[13][8] = -1.22156345524692;
   fWeightMatrix0to1[14][8] = -0.59192787602587;
   fWeightMatrix0to1[15][8] = -0.232053666178246;
   fWeightMatrix0to1[0][9] = 0.718656503913646;
   fWeightMatrix0to1[1][9] = 2.43630699959545;
   fWeightMatrix0to1[2][9] = 8.35963546373111;
   fWeightMatrix0to1[3][9] = -0.315754525665854;
   fWeightMatrix0to1[4][9] = -2.41528660547826;
   fWeightMatrix0to1[5][9] = 0.0579090159155347;
   fWeightMatrix0to1[6][9] = -4.16065195425575;
   fWeightMatrix0to1[7][9] = 0.563940724910364;
   fWeightMatrix0to1[8][9] = 1.71274551844121;
   fWeightMatrix0to1[9][9] = -1.98897181499719;
   fWeightMatrix0to1[10][9] = -1.23341759170761;
   fWeightMatrix0to1[11][9] = 3.07148422762506;
   fWeightMatrix0to1[12][9] = 6.59817949778522;
   fWeightMatrix0to1[13][9] = -0.189547102345598;
   fWeightMatrix0to1[14][9] = 3.16169637860238;
   fWeightMatrix0to1[15][9] = 1.46730167857388;
   fWeightMatrix0to1[0][10] = 0.541093254880758;
   fWeightMatrix0to1[1][10] = 1.72845133293102;
   fWeightMatrix0to1[2][10] = 1.506052898546;
   fWeightMatrix0to1[3][10] = 0.208296539924677;
   fWeightMatrix0to1[4][10] = -0.0588383613521656;
   fWeightMatrix0to1[5][10] = -1.47218941421262;
   fWeightMatrix0to1[6][10] = -1.17562349841058;
   fWeightMatrix0to1[7][10] = 0.404808239176534;
   fWeightMatrix0to1[8][10] = -0.987214052706215;
   fWeightMatrix0to1[9][10] = -4.97293990009719;
   fWeightMatrix0to1[10][10] = 3.88657383581669;
   fWeightMatrix0to1[11][10] = -0.72271651157579;
   fWeightMatrix0to1[12][10] = -0.0373771338593992;
   fWeightMatrix0to1[13][10] = 1.54401599092272;
   fWeightMatrix0to1[14][10] = 1.84462337968089;
   fWeightMatrix0to1[15][10] = 2.76734285083443;
   fWeightMatrix0to1[0][11] = -0.583006042394318;
   fWeightMatrix0to1[1][11] = -1.58243887675988;
   fWeightMatrix0to1[2][11] = -0.728084269249454;
   fWeightMatrix0to1[3][11] = -1.51375810439029;
   fWeightMatrix0to1[4][11] = -2.36711655775021;
   fWeightMatrix0to1[5][11] = 0.0804096529554604;
   fWeightMatrix0to1[6][11] = 3.76171928549307;
   fWeightMatrix0to1[7][11] = -4.06179942531325;
   fWeightMatrix0to1[8][11] = -0.170630868732131;
   fWeightMatrix0to1[9][11] = 0.302408516229591;
   fWeightMatrix0to1[10][11] = -1.58269281374585;
   fWeightMatrix0to1[11][11] = 4.35519708638392;
   fWeightMatrix0to1[12][11] = 1.2311535593942;
   fWeightMatrix0to1[13][11] = -0.10084622884119;
   fWeightMatrix0to1[14][11] = -6.17790373166692;
   fWeightMatrix0to1[15][11] = 8.54274086565607;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0733177362961156;
   fWeightMatrix1to2[0][1] = -0.235686488722404;
   fWeightMatrix1to2[0][2] = 0.284211056846497;
   fWeightMatrix1to2[0][3] = -0.0219217327017726;
   fWeightMatrix1to2[0][4] = -0.0400988247461714;
   fWeightMatrix1to2[0][5] = 0.0135573298626722;
   fWeightMatrix1to2[0][6] = 0.227313891406929;
   fWeightMatrix1to2[0][7] = 0.119113498673883;
   fWeightMatrix1to2[0][8] = 0.00553762465126214;
   fWeightMatrix1to2[0][9] = -0.0660669471353064;
   fWeightMatrix1to2[0][10] = -0.0448539398682503;
   fWeightMatrix1to2[0][11] = 0.0575699072641923;
   fWeightMatrix1to2[0][12] = -0.0810479199661274;
   fWeightMatrix1to2[0][13] = 0.0308701239202611;
   fWeightMatrix1to2[0][14] = 0.251839374528703;
   fWeightMatrix1to2[0][15] = 0.165240175793306;
   fWeightMatrix1to2[0][16] = -0.0505152314194371;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0710297822952;
   fMax_1[0][0] = 3.24809241295;
   fMin_1[1][0] = 0.0744008347392;
   fMax_1[1][0] = 3.29906010628;
   fMin_1[2][0] = 0.0710297822952;
   fMax_1[2][0] = 3.29906010628;
   fMin_1[0][1] = 0.394397765398;
   fMax_1[0][1] = 4.86755418777;
   fMin_1[1][1] = 0.394795924425;
   fMax_1[1][1] = 4.95207595825;
   fMin_1[2][1] = 0.394397765398;
   fMax_1[2][1] = 4.95207595825;
   fMin_1[0][2] = 0.428268820047;
   fMax_1[0][2] = 4.55481052399;
   fMin_1[1][2] = 0.400819450617;
   fMax_1[1][2] = 4.82403278351;
   fMin_1[2][2] = 0.400819450617;
   fMax_1[2][2] = 4.82403278351;
   fMin_1[0][3] = 0.482309132814;
   fMax_1[0][3] = 5.54319143295;
   fMin_1[1][3] = 0.0285045839846;
   fMax_1[1][3] = 5.91814279556;
   fMin_1[2][3] = 0.0285045839846;
   fMax_1[2][3] = 5.91814279556;
   fMin_1[0][4] = 0.403237849474;
   fMax_1[0][4] = 3.18627643585;
   fMin_1[1][4] = 0.400462150574;
   fMax_1[1][4] = 3.18153500557;
   fMin_1[2][4] = 0.400462150574;
   fMax_1[2][4] = 3.18627643585;
   fMin_1[0][5] = 0.00503854127601;
   fMax_1[0][5] = 3.14152812958;
   fMin_1[1][5] = 0.000525824725628;
   fMax_1[1][5] = 3.14149975777;
   fMin_1[2][5] = 0.000525824725628;
   fMax_1[2][5] = 3.14152812958;
   fMin_1[0][6] = 5.0063123703;
   fMax_1[0][6] = 92.8833694458;
   fMin_1[1][6] = 5.02790021896;
   fMax_1[1][6] = 99.9996490479;
   fMin_1[2][6] = 5.0063123703;
   fMax_1[2][6] = 99.9996490479;
   fMin_1[0][7] = 22.5491504669;
   fMax_1[0][7] = 656.016723633;
   fMin_1[1][7] = 22.1016559601;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.1016559601;
   fMax_1[2][7] = 694.112365723;
   fMin_1[0][8] = 0.0199588146061;
   fMax_1[0][8] = 249.251281738;
   fMin_1[1][8] = 0.0371361412108;
   fMax_1[1][8] = 249.843353271;
   fMin_1[2][8] = 0.0199588146061;
   fMax_1[2][8] = 249.843353271;
   fMin_1[0][9] = 49.7347831726;
   fMax_1[0][9] = 395.929016113;
   fMin_1[1][9] = 32.4793205261;
   fMax_1[1][9] = 395.092895508;
   fMin_1[2][9] = 32.4793205261;
   fMax_1[2][9] = 395.929016113;
   fMin_1[0][10] = 2.84827232361;
   fMax_1[0][10] = 295.275390625;
   fMin_1[1][10] = 0.954420506954;
   fMax_1[1][10] = 298.936981201;
   fMin_1[2][10] = 0.954420506954;
   fMax_1[2][10] = 298.936981201;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
