// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May 13 14:55:22 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 17440
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0704806447029,3.29943013191]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380652487278,4.96937084198]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400819450617,4.85822916031]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0399613082409,5.81896591187]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400462150574,3.19580006599]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.00037625504774,3.14159083366]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.02790021896,99.9996490479]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.0869197845,699.872253418]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.843353271]
MT2                           MT2                           MT2                           MT2                                                             'F'    [25.0663490295,399.97177124]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.954420506954,299.942260742]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.519900552674831;
   fWeightMatrix0to1[1][0] = 1.5684434552303;
   fWeightMatrix0to1[2][0] = 0.120120178413399;
   fWeightMatrix0to1[3][0] = 1.76822282065711;
   fWeightMatrix0to1[4][0] = -1.1698610439337;
   fWeightMatrix0to1[5][0] = -1.4730650414249;
   fWeightMatrix0to1[6][0] = 0.0584330872899778;
   fWeightMatrix0to1[7][0] = 1.83103447722376;
   fWeightMatrix0to1[8][0] = -1.44362110123335;
   fWeightMatrix0to1[9][0] = -1.67877035337968;
   fWeightMatrix0to1[10][0] = -1.27470640310171;
   fWeightMatrix0to1[11][0] = 0.582142069990239;
   fWeightMatrix0to1[12][0] = -1.02866814394503;
   fWeightMatrix0to1[13][0] = -0.567766612997719;
   fWeightMatrix0to1[14][0] = -0.920002888600428;
   fWeightMatrix0to1[15][0] = 1.1673581454028;
   fWeightMatrix0to1[0][1] = -0.278917280795172;
   fWeightMatrix0to1[1][1] = 1.09682750667237;
   fWeightMatrix0to1[2][1] = 0.0127056341192801;
   fWeightMatrix0to1[3][1] = 1.37600904305752;
   fWeightMatrix0to1[4][1] = -0.508784978658705;
   fWeightMatrix0to1[5][1] = -0.667935864234751;
   fWeightMatrix0to1[6][1] = 1.14352359373142;
   fWeightMatrix0to1[7][1] = -0.126366178510545;
   fWeightMatrix0to1[8][1] = -1.07740162290112;
   fWeightMatrix0to1[9][1] = -0.0913290376093967;
   fWeightMatrix0to1[10][1] = 1.27932958771416;
   fWeightMatrix0to1[11][1] = -0.854153668142445;
   fWeightMatrix0to1[12][1] = -1.65582507211618;
   fWeightMatrix0to1[13][1] = 0.165266854971325;
   fWeightMatrix0to1[14][1] = 0.792021347207746;
   fWeightMatrix0to1[15][1] = 1.79238312510786;
   fWeightMatrix0to1[0][2] = -0.225510320950462;
   fWeightMatrix0to1[1][2] = -0.000662946693252128;
   fWeightMatrix0to1[2][2] = 0.0689042880731543;
   fWeightMatrix0to1[3][2] = -0.353174408485941;
   fWeightMatrix0to1[4][2] = -0.702780942857009;
   fWeightMatrix0to1[5][2] = 1.95933951191698;
   fWeightMatrix0to1[6][2] = -0.574011430670773;
   fWeightMatrix0to1[7][2] = 0.871104262554591;
   fWeightMatrix0to1[8][2] = 1.19712957511119;
   fWeightMatrix0to1[9][2] = 0.697096576064714;
   fWeightMatrix0to1[10][2] = 1.70727707282647;
   fWeightMatrix0to1[11][2] = 0.705021131017575;
   fWeightMatrix0to1[12][2] = -0.480567033334176;
   fWeightMatrix0to1[13][2] = -1.55438191852479;
   fWeightMatrix0to1[14][2] = 0.0478714580387233;
   fWeightMatrix0to1[15][2] = 0.0507590704122108;
   fWeightMatrix0to1[0][3] = 1.44106385561663;
   fWeightMatrix0to1[1][3] = 1.28866987045543;
   fWeightMatrix0to1[2][3] = 1.36623327593335;
   fWeightMatrix0to1[3][3] = 1.34648131240927;
   fWeightMatrix0to1[4][3] = -1.15848612310905;
   fWeightMatrix0to1[5][3] = 1.36125639341472;
   fWeightMatrix0to1[6][3] = -1.74315583190223;
   fWeightMatrix0to1[7][3] = -1.00309511097638;
   fWeightMatrix0to1[8][3] = -1.22865375668309;
   fWeightMatrix0to1[9][3] = -1.71248887474724;
   fWeightMatrix0to1[10][3] = 1.38762866362473;
   fWeightMatrix0to1[11][3] = 0.506729563841092;
   fWeightMatrix0to1[12][3] = -1.57453798393802;
   fWeightMatrix0to1[13][3] = 0.275835099456936;
   fWeightMatrix0to1[14][3] = -0.216971977769396;
   fWeightMatrix0to1[15][3] = 0.615646972221856;
   fWeightMatrix0to1[0][4] = 2.10030422327468;
   fWeightMatrix0to1[1][4] = -0.378665590861728;
   fWeightMatrix0to1[2][4] = 0.21716018176199;
   fWeightMatrix0to1[3][4] = -1.15084875074473;
   fWeightMatrix0to1[4][4] = 1.24392986354465;
   fWeightMatrix0to1[5][4] = -0.425848875463162;
   fWeightMatrix0to1[6][4] = -0.697305655336516;
   fWeightMatrix0to1[7][4] = -1.64680476851662;
   fWeightMatrix0to1[8][4] = 0.674996517486364;
   fWeightMatrix0to1[9][4] = 0.41875864764615;
   fWeightMatrix0to1[10][4] = 1.45073144152955;
   fWeightMatrix0to1[11][4] = -0.426238658554503;
   fWeightMatrix0to1[12][4] = -1.69840520337672;
   fWeightMatrix0to1[13][4] = -1.9081946656119;
   fWeightMatrix0to1[14][4] = -0.0115821402301284;
   fWeightMatrix0to1[15][4] = 0.0825947403570439;
   fWeightMatrix0to1[0][5] = 1.25162179232657;
   fWeightMatrix0to1[1][5] = 0.0451613529248113;
   fWeightMatrix0to1[2][5] = 0.525871979925712;
   fWeightMatrix0to1[3][5] = -0.7232687167027;
   fWeightMatrix0to1[4][5] = -0.0913788051409093;
   fWeightMatrix0to1[5][5] = -0.666707256341229;
   fWeightMatrix0to1[6][5] = 0.250332822749602;
   fWeightMatrix0to1[7][5] = -0.943377978750583;
   fWeightMatrix0to1[8][5] = -1.49467643423529;
   fWeightMatrix0to1[9][5] = -1.01647432478291;
   fWeightMatrix0to1[10][5] = -0.709615108869552;
   fWeightMatrix0to1[11][5] = 0.0667786827531236;
   fWeightMatrix0to1[12][5] = 1.38566397495051;
   fWeightMatrix0to1[13][5] = -1.48764427798723;
   fWeightMatrix0to1[14][5] = 0.423715120180341;
   fWeightMatrix0to1[15][5] = 1.13152608335839;
   fWeightMatrix0to1[0][6] = -1.19596599108069;
   fWeightMatrix0to1[1][6] = -0.155673693787767;
   fWeightMatrix0to1[2][6] = -1.09897839201983;
   fWeightMatrix0to1[3][6] = 0.0663597915552249;
   fWeightMatrix0to1[4][6] = -2.01887318942758;
   fWeightMatrix0to1[5][6] = -2.04984597975147;
   fWeightMatrix0to1[6][6] = 1.43329682843944;
   fWeightMatrix0to1[7][6] = 1.83694400105813;
   fWeightMatrix0to1[8][6] = -1.15355309285384;
   fWeightMatrix0to1[9][6] = 1.45388983785894;
   fWeightMatrix0to1[10][6] = -0.667757192286841;
   fWeightMatrix0to1[11][6] = 0.168364451456545;
   fWeightMatrix0to1[12][6] = -0.148507379974012;
   fWeightMatrix0to1[13][6] = 0.213331120194841;
   fWeightMatrix0to1[14][6] = -0.726912987390034;
   fWeightMatrix0to1[15][6] = 0.764761726273964;
   fWeightMatrix0to1[0][7] = 0.67917848865067;
   fWeightMatrix0to1[1][7] = -0.209727036144832;
   fWeightMatrix0to1[2][7] = -1.11054954819194;
   fWeightMatrix0to1[3][7] = 1.61745303433333;
   fWeightMatrix0to1[4][7] = 0.285591229709167;
   fWeightMatrix0to1[5][7] = -0.155135656024511;
   fWeightMatrix0to1[6][7] = 1.3452927227424;
   fWeightMatrix0to1[7][7] = -1.63522334532896;
   fWeightMatrix0to1[8][7] = -1.41558644203221;
   fWeightMatrix0to1[9][7] = -0.264436777637611;
   fWeightMatrix0to1[10][7] = -0.106543917661671;
   fWeightMatrix0to1[11][7] = 0.97546584619462;
   fWeightMatrix0to1[12][7] = 0.875079569781558;
   fWeightMatrix0to1[13][7] = -0.336799194131452;
   fWeightMatrix0to1[14][7] = -2.32345975013771;
   fWeightMatrix0to1[15][7] = 0.442411123024489;
   fWeightMatrix0to1[0][8] = -1.38550267446945;
   fWeightMatrix0to1[1][8] = 0.719341973905331;
   fWeightMatrix0to1[2][8] = -0.221530082948278;
   fWeightMatrix0to1[3][8] = -1.95695946227057;
   fWeightMatrix0to1[4][8] = 0.305528870030253;
   fWeightMatrix0to1[5][8] = -0.912546048054341;
   fWeightMatrix0to1[6][8] = 0.651636002387894;
   fWeightMatrix0to1[7][8] = 0.826105380376045;
   fWeightMatrix0to1[8][8] = 1.69246802245435;
   fWeightMatrix0to1[9][8] = -1.47854619659861;
   fWeightMatrix0to1[10][8] = 0.26626413902427;
   fWeightMatrix0to1[11][8] = 0.405855807050287;
   fWeightMatrix0to1[12][8] = 1.45140384727429;
   fWeightMatrix0to1[13][8] = 0.285217950220831;
   fWeightMatrix0to1[14][8] = -1.218494883003;
   fWeightMatrix0to1[15][8] = -0.0811731538171075;
   fWeightMatrix0to1[0][9] = -1.23095762715389;
   fWeightMatrix0to1[1][9] = 2.46097414078373;
   fWeightMatrix0to1[2][9] = 1.71663895087995;
   fWeightMatrix0to1[3][9] = -0.587885408767546;
   fWeightMatrix0to1[4][9] = -0.786841148579166;
   fWeightMatrix0to1[5][9] = 0.442029299669898;
   fWeightMatrix0to1[6][9] = -2.07516242158596;
   fWeightMatrix0to1[7][9] = 0.459246882367998;
   fWeightMatrix0to1[8][9] = 1.7898343771624;
   fWeightMatrix0to1[9][9] = -0.640141270331818;
   fWeightMatrix0to1[10][9] = -0.408548300106087;
   fWeightMatrix0to1[11][9] = -0.67617996510671;
   fWeightMatrix0to1[12][9] = 1.21107542379988;
   fWeightMatrix0to1[13][9] = 0.294636763818561;
   fWeightMatrix0to1[14][9] = 5.42669676610108;
   fWeightMatrix0to1[15][9] = -1.49462695989754;
   fWeightMatrix0to1[0][10] = 1.6173554847986;
   fWeightMatrix0to1[1][10] = 1.08128729756048;
   fWeightMatrix0to1[2][10] = 0.822973726712146;
   fWeightMatrix0to1[3][10] = 0.464892821449299;
   fWeightMatrix0to1[4][10] = 0.99064549546423;
   fWeightMatrix0to1[5][10] = -0.0861329595819223;
   fWeightMatrix0to1[6][10] = -1.21428015427044;
   fWeightMatrix0to1[7][10] = 0.834908613181991;
   fWeightMatrix0to1[8][10] = -0.816616671820749;
   fWeightMatrix0to1[9][10] = -1.15786476534481;
   fWeightMatrix0to1[10][10] = 1.93952233944535;
   fWeightMatrix0to1[11][10] = 0.128548003344591;
   fWeightMatrix0to1[12][10] = -0.421764882170833;
   fWeightMatrix0to1[13][10] = 1.13362774000153;
   fWeightMatrix0to1[14][10] = 0.18409824502891;
   fWeightMatrix0to1[15][10] = -1.74494533283349;
   fWeightMatrix0to1[0][11] = -0.132638118279;
   fWeightMatrix0to1[1][11] = -0.891559225669288;
   fWeightMatrix0to1[2][11] = -0.431337388993212;
   fWeightMatrix0to1[3][11] = -1.44992797759562;
   fWeightMatrix0to1[4][11] = -2.03368948307097;
   fWeightMatrix0to1[5][11] = -0.111019477544535;
   fWeightMatrix0to1[6][11] = 2.07379522528127;
   fWeightMatrix0to1[7][11] = -0.974754154388669;
   fWeightMatrix0to1[8][11] = -0.335329664013606;
   fWeightMatrix0to1[9][11] = 0.388451596320122;
   fWeightMatrix0to1[10][11] = -0.323993104574801;
   fWeightMatrix0to1[11][11] = 3.11481859731875;
   fWeightMatrix0to1[12][11] = -0.387195996785028;
   fWeightMatrix0to1[13][11] = 0.031155908552216;
   fWeightMatrix0to1[14][11] = -1.63595954992887;
   fWeightMatrix0to1[15][11] = 0.580524020317867;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0320087456062363;
   fWeightMatrix1to2[0][1] = -0.156643855130314;
   fWeightMatrix1to2[0][2] = -0.122125338273546;
   fWeightMatrix1to2[0][3] = 0.0102347092958252;
   fWeightMatrix1to2[0][4] = -0.0666720663584717;
   fWeightMatrix1to2[0][5] = 0.0262749420975547;
   fWeightMatrix1to2[0][6] = -0.173672085890616;
   fWeightMatrix1to2[0][7] = 0.00434809043152121;
   fWeightMatrix1to2[0][8] = -0.00459205493012063;
   fWeightMatrix1to2[0][9] = -0.0682519028849526;
   fWeightMatrix1to2[0][10] = 0.0146254539715126;
   fWeightMatrix1to2[0][11] = -0.853252990190616;
   fWeightMatrix1to2[0][12] = 0.00723473008088345;
   fWeightMatrix1to2[0][13] = -0.00186468595740707;
   fWeightMatrix1to2[0][14] = 0.398138648422007;
   fWeightMatrix1to2[0][15] = -0.0169855750328262;
   fWeightMatrix1to2[0][16] = 1.22505883405551;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0704806447029;
   fMax_1[0][0] = 3.19691205025;
   fMin_1[1][0] = 0.0710144713521;
   fMax_1[1][0] = 3.29943013191;
   fMin_1[2][0] = 0.0704806447029;
   fMax_1[2][0] = 3.29943013191;
   fMin_1[0][1] = 0.386050820351;
   fMax_1[0][1] = 4.96937084198;
   fMin_1[1][1] = 0.380652487278;
   fMax_1[1][1] = 4.94220972061;
   fMin_1[2][1] = 0.380652487278;
   fMax_1[2][1] = 4.96937084198;
   fMin_1[0][2] = 0.501157164574;
   fMax_1[0][2] = 4.85822916031;
   fMin_1[1][2] = 0.400819450617;
   fMax_1[1][2] = 4.8140463829;
   fMin_1[2][2] = 0.400819450617;
   fMax_1[2][2] = 4.85822916031;
   fMin_1[0][3] = 0.79715269804;
   fMax_1[0][3] = 5.65362501144;
   fMin_1[1][3] = 0.0399613082409;
   fMax_1[1][3] = 5.81896591187;
   fMin_1[2][3] = 0.0399613082409;
   fMax_1[2][3] = 5.81896591187;
   fMin_1[0][4] = 0.434721857309;
   fMax_1[0][4] = 3.19580006599;
   fMin_1[1][4] = 0.400462150574;
   fMax_1[1][4] = 3.11300230026;
   fMin_1[2][4] = 0.400462150574;
   fMax_1[2][4] = 3.19580006599;
   fMin_1[0][5] = 0.0334732420743;
   fMax_1[0][5] = 3.14159083366;
   fMin_1[1][5] = 0.00037625504774;
   fMax_1[1][5] = 3.14149975777;
   fMin_1[2][5] = 0.00037625504774;
   fMax_1[2][5] = 3.14159083366;
   fMin_1[0][6] = 5.05816555023;
   fMax_1[0][6] = 92.9765930176;
   fMin_1[1][6] = 5.02790021896;
   fMax_1[1][6] = 99.9996490479;
   fMin_1[2][6] = 5.02790021896;
   fMax_1[2][6] = 99.9996490479;
   fMin_1[0][7] = 22.0869197845;
   fMax_1[0][7] = 699.872253418;
   fMin_1[1][7] = 22.1846733093;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.0869197845;
   fMax_1[2][7] = 699.872253418;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 248.674987793;
   fMin_1[1][8] = 0.0127812996507;
   fMax_1[1][8] = 249.843353271;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.843353271;
   fMin_1[0][9] = 42.3850440979;
   fMax_1[0][9] = 399.97177124;
   fMin_1[1][9] = 25.0663490295;
   fMax_1[1][9] = 395.092895508;
   fMin_1[2][9] = 25.0663490295;
   fMax_1[2][9] = 399.97177124;
   fMin_1[0][10] = 6.05513429642;
   fMax_1[0][10] = 299.942260742;
   fMin_1[1][10] = 0.954420506954;
   fMax_1[1][10] = 298.936981201;
   fMin_1[2][10] = 0.954420506954;
   fMax_1[2][10] = 299.942260742;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
