// Class: ReadMLPBFGS
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLPBFGS
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri May  6 11:21:21 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 16525
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TrainingMethod: "BFGS" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0710144713521,3.29943013191]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.380652487278,4.97898674011]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.401567369699,4.91523265839]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.0163523908705,5.91814279556]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400563418865,3.18510365486]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [0.00037625504774,3.14149975777]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00658273697,99.9996490479]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.1685295105,694.112365723]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0.0127812996507,249.781051636]
MT2                           MT2                           MT2                           MT2                                                             'F'    [25.0663490295,392.591949463]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.660549879074,298.342681885]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLPBFGS : public IClassifierReader {

 public:

   // constructor
   ReadMLPBFGS( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLPBFGS" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLPBFGS() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLPBFGS::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.141530198775158;
   fWeightMatrix0to1[1][0] = 0.953825351348588;
   fWeightMatrix0to1[2][0] = -0.128896505599046;
   fWeightMatrix0to1[3][0] = -0.0209574986288867;
   fWeightMatrix0to1[4][0] = 0.0640032059010078;
   fWeightMatrix0to1[5][0] = 0.116534663182163;
   fWeightMatrix0to1[6][0] = -0.0362925064874288;
   fWeightMatrix0to1[7][0] = 2.3701350814986;
   fWeightMatrix0to1[8][0] = 1.32078603657616;
   fWeightMatrix0to1[9][0] = -1.49961726063449;
   fWeightMatrix0to1[10][0] = -4.06928406513472;
   fWeightMatrix0to1[11][0] = -1.72295552852988;
   fWeightMatrix0to1[12][0] = -0.875631339333657;
   fWeightMatrix0to1[13][0] = 1.48837570520778;
   fWeightMatrix0to1[14][0] = 0.53826057302622;
   fWeightMatrix0to1[15][0] = -0.157350727876878;
   fWeightMatrix0to1[0][1] = -0.414539880751405;
   fWeightMatrix0to1[1][1] = 1.59385847359847;
   fWeightMatrix0to1[2][1] = -0.813948748365968;
   fWeightMatrix0to1[3][1] = 0.0618086409063357;
   fWeightMatrix0to1[4][1] = 0.671511192003243;
   fWeightMatrix0to1[5][1] = -2.42953337072088;
   fWeightMatrix0to1[6][1] = -0.326643511909828;
   fWeightMatrix0to1[7][1] = -1.53311097508609;
   fWeightMatrix0to1[8][1] = -0.34569690709495;
   fWeightMatrix0to1[9][1] = -0.315716620167407;
   fWeightMatrix0to1[10][1] = -0.537183480677336;
   fWeightMatrix0to1[11][1] = -2.7643821754369;
   fWeightMatrix0to1[12][1] = -0.310298718100555;
   fWeightMatrix0to1[13][1] = 0.848174019521476;
   fWeightMatrix0to1[14][1] = 0.192740006303018;
   fWeightMatrix0to1[15][1] = 4.53688927773514;
   fWeightMatrix0to1[0][2] = 0.436412699424344;
   fWeightMatrix0to1[1][2] = 0.277906359451458;
   fWeightMatrix0to1[2][2] = 0.265173068201102;
   fWeightMatrix0to1[3][2] = 0.435606644296476;
   fWeightMatrix0to1[4][2] = -0.963940611836275;
   fWeightMatrix0to1[5][2] = -0.0073113523856138;
   fWeightMatrix0to1[6][2] = -0.232110088273723;
   fWeightMatrix0to1[7][2] = -0.197180866411004;
   fWeightMatrix0to1[8][2] = 1.79228953546981;
   fWeightMatrix0to1[9][2] = -2.79642404840123;
   fWeightMatrix0to1[10][2] = 3.86630012254356;
   fWeightMatrix0to1[11][2] = -0.415622746011966;
   fWeightMatrix0to1[12][2] = -2.88942178020582;
   fWeightMatrix0to1[13][2] = -0.694563852641247;
   fWeightMatrix0to1[14][2] = -0.186155444005222;
   fWeightMatrix0to1[15][2] = -1.62889023017322;
   fWeightMatrix0to1[0][3] = 2.34751718940569;
   fWeightMatrix0to1[1][3] = 0.203693285735645;
   fWeightMatrix0to1[2][3] = 0.206587164811673;
   fWeightMatrix0to1[3][3] = 1.81143753709453;
   fWeightMatrix0to1[4][3] = -2.43640992696661;
   fWeightMatrix0to1[5][3] = 1.90549184846217;
   fWeightMatrix0to1[6][3] = 0.294152652159903;
   fWeightMatrix0to1[7][3] = -0.511889799757451;
   fWeightMatrix0to1[8][3] = 0.170994682580111;
   fWeightMatrix0to1[9][3] = -0.138081170061434;
   fWeightMatrix0to1[10][3] = 2.94580102220476;
   fWeightMatrix0to1[11][3] = -0.436282978396592;
   fWeightMatrix0to1[12][3] = -2.47553150678538;
   fWeightMatrix0to1[13][3] = 0.897277960409156;
   fWeightMatrix0to1[14][3] = 0.238563129413665;
   fWeightMatrix0to1[15][3] = 0.0311707812676317;
   fWeightMatrix0to1[0][4] = 1.32069038900728;
   fWeightMatrix0to1[1][4] = 2.31944280437194;
   fWeightMatrix0to1[2][4] = 0.044646054407775;
   fWeightMatrix0to1[3][4] = -1.04978969374084;
   fWeightMatrix0to1[4][4] = -0.092283394881594;
   fWeightMatrix0to1[5][4] = -0.180900768944034;
   fWeightMatrix0to1[6][4] = 0.0528487978323249;
   fWeightMatrix0to1[7][4] = 0.0937100021627649;
   fWeightMatrix0to1[8][4] = -0.246313370135336;
   fWeightMatrix0to1[9][4] = 0.307983325685088;
   fWeightMatrix0to1[10][4] = -1.20480140152169;
   fWeightMatrix0to1[11][4] = 2.08298421827101;
   fWeightMatrix0to1[12][4] = -1.40270297768924;
   fWeightMatrix0to1[13][4] = -1.62927038941075;
   fWeightMatrix0to1[14][4] = -1.00133936629129;
   fWeightMatrix0to1[15][4] = -1.51005919841907;
   fWeightMatrix0to1[0][5] = -0.232851975430704;
   fWeightMatrix0to1[1][5] = -0.608055002637556;
   fWeightMatrix0to1[2][5] = -0.090529686137574;
   fWeightMatrix0to1[3][5] = -1.60796551325086;
   fWeightMatrix0to1[4][5] = 1.05454312040905;
   fWeightMatrix0to1[5][5] = 0.177265211742355;
   fWeightMatrix0to1[6][5] = 0.0414543767008921;
   fWeightMatrix0to1[7][5] = -1.71926896988369;
   fWeightMatrix0to1[8][5] = -0.828638002351973;
   fWeightMatrix0to1[9][5] = 1.25040482258562;
   fWeightMatrix0to1[10][5] = 0.0961612405486783;
   fWeightMatrix0to1[11][5] = 0.61477621832087;
   fWeightMatrix0to1[12][5] = 0.612542414759425;
   fWeightMatrix0to1[13][5] = -1.63969343629741;
   fWeightMatrix0to1[14][5] = 2.28654259589342;
   fWeightMatrix0to1[15][5] = 3.08451197179069;
   fWeightMatrix0to1[0][6] = -2.59305777772335;
   fWeightMatrix0to1[1][6] = -2.40386515363111;
   fWeightMatrix0to1[2][6] = -0.372080194052104;
   fWeightMatrix0to1[3][6] = 1.55374982690229;
   fWeightMatrix0to1[4][6] = -0.345374431278134;
   fWeightMatrix0to1[5][6] = -2.26067411146546;
   fWeightMatrix0to1[6][6] = -0.419595515752388;
   fWeightMatrix0to1[7][6] = -0.0362068330547288;
   fWeightMatrix0to1[8][6] = -2.66354332491092;
   fWeightMatrix0to1[9][6] = 3.24297063310294;
   fWeightMatrix0to1[10][6] = -0.382991913581244;
   fWeightMatrix0to1[11][6] = 0.521981988297663;
   fWeightMatrix0to1[12][6] = 0.300794216646518;
   fWeightMatrix0to1[13][6] = 1.0265225926511;
   fWeightMatrix0to1[14][6] = -7.51714369807084;
   fWeightMatrix0to1[15][6] = -0.765279225422397;
   fWeightMatrix0to1[0][7] = 0.0755331016904267;
   fWeightMatrix0to1[1][7] = 1.25818476604408;
   fWeightMatrix0to1[2][7] = -14.8355576541352;
   fWeightMatrix0to1[3][7] = 1.00894904119481;
   fWeightMatrix0to1[4][7] = 2.73012794929624;
   fWeightMatrix0to1[5][7] = -2.14240208744388;
   fWeightMatrix0to1[6][7] = 18.5384491409306;
   fWeightMatrix0to1[7][7] = -1.21339387351102;
   fWeightMatrix0to1[8][7] = -5.50377937035216;
   fWeightMatrix0to1[9][7] = 1.69041024794217;
   fWeightMatrix0to1[10][7] = -2.66147980344916;
   fWeightMatrix0to1[11][7] = 4.03963292149019;
   fWeightMatrix0to1[12][7] = -0.207915936106456;
   fWeightMatrix0to1[13][7] = -1.20221215510605;
   fWeightMatrix0to1[14][7] = -1.92009024641166;
   fWeightMatrix0to1[15][7] = 3.15726631184834;
   fWeightMatrix0to1[0][8] = -7.52633186069271;
   fWeightMatrix0to1[1][8] = -1.47370818692497;
   fWeightMatrix0to1[2][8] = -0.87011204491266;
   fWeightMatrix0to1[3][8] = -4.19471569849039;
   fWeightMatrix0to1[4][8] = 1.23403212375293;
   fWeightMatrix0to1[5][8] = -2.13875138278274;
   fWeightMatrix0to1[6][8] = 0.565717608182586;
   fWeightMatrix0to1[7][8] = 2.48994040685175;
   fWeightMatrix0to1[8][8] = 1.1794181986387;
   fWeightMatrix0to1[9][8] = -6.1226288882933;
   fWeightMatrix0to1[10][8] = -0.0738487682586804;
   fWeightMatrix0to1[11][8] = 2.34254877563053;
   fWeightMatrix0to1[12][8] = 2.18464418553328;
   fWeightMatrix0to1[13][8] = -0.101939976954534;
   fWeightMatrix0to1[14][8] = -1.61195109623696;
   fWeightMatrix0to1[15][8] = -0.592286664881653;
   fWeightMatrix0to1[0][9] = -0.328750254393703;
   fWeightMatrix0to1[1][9] = 1.47382183089397;
   fWeightMatrix0to1[2][9] = 2.37385219088841;
   fWeightMatrix0to1[3][9] = 0.359448157330471;
   fWeightMatrix0to1[4][9] = -4.27620460777789;
   fWeightMatrix0to1[5][9] = 3.38422734385456;
   fWeightMatrix0to1[6][9] = -3.10965234286924;
   fWeightMatrix0to1[7][9] = -0.758772053423638;
   fWeightMatrix0to1[8][9] = 4.85613105115487;
   fWeightMatrix0to1[9][9] = 0.506064524744764;
   fWeightMatrix0to1[10][9] = -0.899273648954731;
   fWeightMatrix0to1[11][9] = 0.757247221129396;
   fWeightMatrix0to1[12][9] = 3.43066640964057;
   fWeightMatrix0to1[13][9] = -0.505043236246566;
   fWeightMatrix0to1[14][9] = 0.19634081607843;
   fWeightMatrix0to1[15][9] = -4.01557100967158;
   fWeightMatrix0to1[0][10] = 0.981704904577098;
   fWeightMatrix0to1[1][10] = -0.39112179116654;
   fWeightMatrix0to1[2][10] = 0.726795045367025;
   fWeightMatrix0to1[3][10] = 1.71732605479561;
   fWeightMatrix0to1[4][10] = -2.15285945762384;
   fWeightMatrix0to1[5][10] = -0.199460559069143;
   fWeightMatrix0to1[6][10] = -1.23485793975991;
   fWeightMatrix0to1[7][10] = 0.950812057297808;
   fWeightMatrix0to1[8][10] = 1.4676725736398;
   fWeightMatrix0to1[9][10] = -1.22519435488203;
   fWeightMatrix0to1[10][10] = 1.50333465047711;
   fWeightMatrix0to1[11][10] = -1.34772603335744;
   fWeightMatrix0to1[12][10] = -0.204288387451555;
   fWeightMatrix0to1[13][10] = -0.0635246096203312;
   fWeightMatrix0to1[14][10] = -2.60077870160243;
   fWeightMatrix0to1[15][10] = -2.82355084065055;
   fWeightMatrix0to1[0][11] = 0.173537964689091;
   fWeightMatrix0to1[1][11] = -1.87643983039771;
   fWeightMatrix0to1[2][11] = -9.91673537386233;
   fWeightMatrix0to1[3][11] = -0.901221421100064;
   fWeightMatrix0to1[4][11] = -2.29568980656978;
   fWeightMatrix0to1[5][11] = 1.31363668476933;
   fWeightMatrix0to1[6][11] = 12.7072606413758;
   fWeightMatrix0to1[7][11] = -2.82955233873461;
   fWeightMatrix0to1[8][11] = 0.0438597450245337;
   fWeightMatrix0to1[9][11] = 1.16793239367742;
   fWeightMatrix0to1[10][11] = -3.70272807022038;
   fWeightMatrix0to1[11][11] = -0.537804358391693;
   fWeightMatrix0to1[12][11] = 1.39428953695152;
   fWeightMatrix0to1[13][11] = -0.228228539825347;
   fWeightMatrix0to1[14][11] = -2.98268415467668;
   fWeightMatrix0to1[15][11] = -0.142215983371738;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.0746105150425236;
   fWeightMatrix1to2[0][1] = 0.0973005822447111;
   fWeightMatrix1to2[0][2] = 0.379422178549821;
   fWeightMatrix1to2[0][3] = -0.047546870896101;
   fWeightMatrix1to2[0][4] = -0.084773148943743;
   fWeightMatrix1to2[0][5] = -0.0948997670964277;
   fWeightMatrix1to2[0][6] = 0.361206270831565;
   fWeightMatrix1to2[0][7] = 0.0392017143074658;
   fWeightMatrix1to2[0][8] = 0.0599560034045273;
   fWeightMatrix1to2[0][9] = 0.073705390909585;
   fWeightMatrix1to2[0][10] = 0.0555656343530347;
   fWeightMatrix1to2[0][11] = 0.0636786111361153;
   fWeightMatrix1to2[0][12] = 0.048150024689464;
   fWeightMatrix1to2[0][13] = 0.0227974717441475;
   fWeightMatrix1to2[0][14] = 0.0623537881786813;
   fWeightMatrix1to2[0][15] = 0.0699771910719073;
   fWeightMatrix1to2[0][16] = 0.196205504722133;
}

inline double ReadMLPBFGS::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLPBFGS::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLPBFGS::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLPBFGS::Clear() 
{
   // nothing to clear
}
   inline double ReadMLPBFGS::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0883396416903;
   fMax_1[0][0] = 3.27448964119;
   fMin_1[1][0] = 0.0710144713521;
   fMax_1[1][0] = 3.29943013191;
   fMin_1[2][0] = 0.0710144713521;
   fMax_1[2][0] = 3.29943013191;
   fMin_1[0][1] = 0.384740293026;
   fMax_1[0][1] = 4.9785656929;
   fMin_1[1][1] = 0.380652487278;
   fMax_1[1][1] = 4.97898674011;
   fMin_1[2][1] = 0.380652487278;
   fMax_1[2][1] = 4.97898674011;
   fMin_1[0][2] = 0.42588865757;
   fMax_1[0][2] = 4.58631658554;
   fMin_1[1][2] = 0.401567369699;
   fMax_1[1][2] = 4.91523265839;
   fMin_1[2][2] = 0.401567369699;
   fMax_1[2][2] = 4.91523265839;
   fMin_1[0][3] = 0.205801799893;
   fMax_1[0][3] = 5.64617824554;
   fMin_1[1][3] = 0.0163523908705;
   fMax_1[1][3] = 5.91814279556;
   fMin_1[2][3] = 0.0163523908705;
   fMax_1[2][3] = 5.91814279556;
   fMin_1[0][4] = 0.405622512102;
   fMax_1[0][4] = 3.18510365486;
   fMin_1[1][4] = 0.400563418865;
   fMax_1[1][4] = 3.14165353775;
   fMin_1[2][4] = 0.400563418865;
   fMax_1[2][4] = 3.18510365486;
   fMin_1[0][5] = 0.00980622135103;
   fMax_1[0][5] = 3.14102244377;
   fMin_1[1][5] = 0.00037625504774;
   fMax_1[1][5] = 3.14149975777;
   fMin_1[2][5] = 0.00037625504774;
   fMax_1[2][5] = 3.14149975777;
   fMin_1[0][6] = 5.1002573967;
   fMax_1[0][6] = 87.9802398682;
   fMin_1[1][6] = 5.00658273697;
   fMax_1[1][6] = 99.9996490479;
   fMin_1[2][6] = 5.00658273697;
   fMax_1[2][6] = 99.9996490479;
   fMin_1[0][7] = 22.1885509491;
   fMax_1[0][7] = 627.116210938;
   fMin_1[1][7] = 22.1685295105;
   fMax_1[1][7] = 694.112365723;
   fMin_1[2][7] = 22.1685295105;
   fMax_1[2][7] = 694.112365723;
   fMin_1[0][8] = 0.102857388556;
   fMax_1[0][8] = 248.999359131;
   fMin_1[1][8] = 0.0127812996507;
   fMax_1[1][8] = 249.781051636;
   fMin_1[2][8] = 0.0127812996507;
   fMax_1[2][8] = 249.781051636;
   fMin_1[0][9] = 49.3990783691;
   fMax_1[0][9] = 392.591949463;
   fMin_1[1][9] = 25.0663490295;
   fMax_1[1][9] = 391.314117432;
   fMin_1[2][9] = 25.0663490295;
   fMax_1[2][9] = 392.591949463;
   fMin_1[0][10] = 2.32598638535;
   fMax_1[0][10] = 278.497467041;
   fMin_1[1][10] = 0.660549879074;
   fMax_1[1][10] = 298.342681885;
   fMin_1[2][10] = 0.660549879074;
   fMax_1[2][10] = 298.342681885;
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLPBFGS::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLPBFGS::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
