// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/04       [335876]
Creator        : lpernie
Date           : Fri Jul 15 14:32:21 2016
Host           : Linux login01.brazos.tamu.edu 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/lpernie/Hhh/delphes/diHiggs/MVAs
Training events: 192264
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
dR_l1l2                       dR_l1l2                       dR_l1l2                       dR_l1l2                                                         'F'    [0.0704806447029,3.29987287521]
dR_b1b2                       dR_b1b2                       dR_b1b2                       dR_b1b2                                                         'F'    [0.383513450623,4.99538564682]
dR_bl                         dR_bl                         dR_bl                         dR_bl                                                           'F'    [0.400014162064,4.98474645615]
dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                   dR_l1l2b1b2                                                     'F'    [0.00575727969408,5.99961948395]
MINdR_bl                      MINdR_bl                      MINdR_bl                      MINdR_bl                                                        'F'    [0.400001376867,3.19977164268]
dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                 dphi_l1l2b1b2                                                   'F'    [1.97242206923e-05,3.1415886879]
mass_l1l2                     mass_l1l2                     mass_l1l2                     mass_l1l2                                                       'F'    [5.00372505188,99.99949646]
mass_b1b2                     mass_b1b2                     mass_b1b2                     mass_b1b2                                                       'F'    [22.2296066284,699.396728516]
mass_trans                    mass_trans                    mass_trans                    mass_trans                                                      'F'    [0,249.991043091]
MT2                           MT2                           MT2                           MT2                                                             'F'    [24.572063446,399.818786621]
pt_b1b2                       pt_b1b2                       pt_b1b2                       pt_b1b2                                                         'F'    [0.326862245798,299.945465088]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "dR_l1l2", "dR_b1b2", "dR_bl", "dR_l1l2b1b2", "MINdR_bl", "dphi_l1l2b1b2", "mass_l1l2", "mass_b1b2", "mass_trans", "MT2", "pt_b1b2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 0.99999988079071;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.670627801296687;
   fWeightMatrix0to1[1][0] = 0.0824848092174059;
   fWeightMatrix0to1[2][0] = -0.448718984453197;
   fWeightMatrix0to1[3][0] = 1.10438242994406;
   fWeightMatrix0to1[4][0] = -1.71764541861592;
   fWeightMatrix0to1[5][0] = -1.11961811491494;
   fWeightMatrix0to1[6][0] = 0.848158301488813;
   fWeightMatrix0to1[7][0] = 1.2280184958581;
   fWeightMatrix0to1[8][0] = -0.77506657913761;
   fWeightMatrix0to1[9][0] = -1.22585508266721;
   fWeightMatrix0to1[10][0] = -0.988124453051871;
   fWeightMatrix0to1[11][0] = -0.131282465856226;
   fWeightMatrix0to1[12][0] = -0.808904715027342;
   fWeightMatrix0to1[13][0] = -0.665989740767716;
   fWeightMatrix0to1[14][0] = 0.173389032537213;
   fWeightMatrix0to1[15][0] = 0.535279321229243;
   fWeightMatrix0to1[0][1] = -0.844543811681776;
   fWeightMatrix0to1[1][1] = 0.957727923700018;
   fWeightMatrix0to1[2][1] = 0.715664144998292;
   fWeightMatrix0to1[3][1] = 1.32984739582881;
   fWeightMatrix0to1[4][1] = -0.387510097802208;
   fWeightMatrix0to1[5][1] = -0.529313107919988;
   fWeightMatrix0to1[6][1] = -0.0951010592484676;
   fWeightMatrix0to1[7][1] = -0.117730262427865;
   fWeightMatrix0to1[8][1] = -1.04040325202786;
   fWeightMatrix0to1[9][1] = -0.242514189183988;
   fWeightMatrix0to1[10][1] = 1.54647897832794;
   fWeightMatrix0to1[11][1] = -0.994082913170228;
   fWeightMatrix0to1[12][1] = -1.35160177122552;
   fWeightMatrix0to1[13][1] = 0.003473785643205;
   fWeightMatrix0to1[14][1] = 0.586636882935962;
   fWeightMatrix0to1[15][1] = 1.34579005942894;
   fWeightMatrix0to1[0][2] = -0.397768581220969;
   fWeightMatrix0to1[1][2] = 0.464827586807079;
   fWeightMatrix0to1[2][2] = 0.493274501966603;
   fWeightMatrix0to1[3][2] = 0.221579190967284;
   fWeightMatrix0to1[4][2] = -0.968399285438549;
   fWeightMatrix0to1[5][2] = 1.74531781370648;
   fWeightMatrix0to1[6][2] = 0.432526463560242;
   fWeightMatrix0to1[7][2] = 0.742107637064537;
   fWeightMatrix0to1[8][2] = 1.40880365669673;
   fWeightMatrix0to1[9][2] = 0.905960882605662;
   fWeightMatrix0to1[10][2] = 1.60918493913764;
   fWeightMatrix0to1[11][2] = 0.726580836900125;
   fWeightMatrix0to1[12][2] = 0.187757784395609;
   fWeightMatrix0to1[13][2] = -1.4512137121065;
   fWeightMatrix0to1[14][2] = 0.342149866849328;
   fWeightMatrix0to1[15][2] = -0.438364726464712;
   fWeightMatrix0to1[0][3] = 1.4895079422391;
   fWeightMatrix0to1[1][3] = 0.960340179651343;
   fWeightMatrix0to1[2][3] = 0.7740884201028;
   fWeightMatrix0to1[3][3] = 1.69597817517705;
   fWeightMatrix0to1[4][3] = -1.32807794341238;
   fWeightMatrix0to1[5][3] = 1.24666115610298;
   fWeightMatrix0to1[6][3] = -0.872644232583899;
   fWeightMatrix0to1[7][3] = -1.01169623702949;
   fWeightMatrix0to1[8][3] = -0.893663218891565;
   fWeightMatrix0to1[9][3] = -1.73588584122659;
   fWeightMatrix0to1[10][3] = 1.4247344852458;
   fWeightMatrix0to1[11][3] = 0.84769182790916;
   fWeightMatrix0to1[12][3] = -1.05838044617351;
   fWeightMatrix0to1[13][3] = 0.312399184281655;
   fWeightMatrix0to1[14][3] = -0.341186146386931;
   fWeightMatrix0to1[15][3] = 0.176510303212445;
   fWeightMatrix0to1[0][4] = 1.23307224822281;
   fWeightMatrix0to1[1][4] = -0.537096398151938;
   fWeightMatrix0to1[2][4] = -0.120772532058418;
   fWeightMatrix0to1[3][4] = -0.774268351106924;
   fWeightMatrix0to1[4][4] = 0.997022635663981;
   fWeightMatrix0to1[5][4] = -0.755197352582417;
   fWeightMatrix0to1[6][4] = -0.43335316546952;
   fWeightMatrix0to1[7][4] = -1.88815817350017;
   fWeightMatrix0to1[8][4] = 0.946867776213155;
   fWeightMatrix0to1[9][4] = 0.811860918717683;
   fWeightMatrix0to1[10][4] = 1.0587428694176;
   fWeightMatrix0to1[11][4] = 0.0812373710711689;
   fWeightMatrix0to1[12][4] = -0.370575742386366;
   fWeightMatrix0to1[13][4] = -1.62961228434283;
   fWeightMatrix0to1[14][4] = 0.792606459400113;
   fWeightMatrix0to1[15][4] = -0.139797622239298;
   fWeightMatrix0to1[0][5] = -0.527929694500432;
   fWeightMatrix0to1[1][5] = -0.0836682073370419;
   fWeightMatrix0to1[2][5] = -0.245904623173548;
   fWeightMatrix0to1[3][5] = -0.510546258246875;
   fWeightMatrix0to1[4][5] = -0.500910129648092;
   fWeightMatrix0to1[5][5] = -0.79970270761796;
   fWeightMatrix0to1[6][5] = -0.183947346169198;
   fWeightMatrix0to1[7][5] = 0.223278962989427;
   fWeightMatrix0to1[8][5] = -1.39283503304642;
   fWeightMatrix0to1[9][5] = -1.30179118856456;
   fWeightMatrix0to1[10][5] = -1.09585369273428;
   fWeightMatrix0to1[11][5] = -0.502393431146681;
   fWeightMatrix0to1[12][5] = 1.18140174764128;
   fWeightMatrix0to1[13][5] = -0.625827225278275;
   fWeightMatrix0to1[14][5] = -0.633577225734728;
   fWeightMatrix0to1[15][5] = 1.07765126578733;
   fWeightMatrix0to1[0][6] = -1.29282394877077;
   fWeightMatrix0to1[1][6] = 0.0215787503803027;
   fWeightMatrix0to1[2][6] = -0.750269262503463;
   fWeightMatrix0to1[3][6] = -0.266369427446571;
   fWeightMatrix0to1[4][6] = -1.33722657140891;
   fWeightMatrix0to1[5][6] = -1.46763554386893;
   fWeightMatrix0to1[6][6] = 0.703685736385947;
   fWeightMatrix0to1[7][6] = 0.969025646501746;
   fWeightMatrix0to1[8][6] = -0.85889507858187;
   fWeightMatrix0to1[9][6] = 1.2770221363639;
   fWeightMatrix0to1[10][6] = -0.541828378453474;
   fWeightMatrix0to1[11][6] = -0.520534255842149;
   fWeightMatrix0to1[12][6] = -0.105811208605324;
   fWeightMatrix0to1[13][6] = 0.174615822407526;
   fWeightMatrix0to1[14][6] = -1.23268898517254;
   fWeightMatrix0to1[15][6] = 0.21454770367664;
   fWeightMatrix0to1[0][7] = 1.15747280384156;
   fWeightMatrix0to1[1][7] = -0.954558413204835;
   fWeightMatrix0to1[2][7] = -1.77538987462548;
   fWeightMatrix0to1[3][7] = 1.97565703212407;
   fWeightMatrix0to1[4][7] = 0.561397107603355;
   fWeightMatrix0to1[5][7] = -0.497340957493358;
   fWeightMatrix0to1[6][7] = 4.95476890201847;
   fWeightMatrix0to1[7][7] = -2.56779836693553;
   fWeightMatrix0to1[8][7] = -0.617388250910604;
   fWeightMatrix0to1[9][7] = -0.112113726216744;
   fWeightMatrix0to1[10][7] = 0.246629776620342;
   fWeightMatrix0to1[11][7] = 2.12872213242243;
   fWeightMatrix0to1[12][7] = 1.83056241896475;
   fWeightMatrix0to1[13][7] = -1.05617750735978;
   fWeightMatrix0to1[14][7] = -0.128929702772643;
   fWeightMatrix0to1[15][7] = -0.178533312488638;
   fWeightMatrix0to1[0][8] = -0.582377638880105;
   fWeightMatrix0to1[1][8] = -0.0321706467585107;
   fWeightMatrix0to1[2][8] = -0.802139246985323;
   fWeightMatrix0to1[3][8] = -1.33416748312296;
   fWeightMatrix0to1[4][8] = 0.61357557781839;
   fWeightMatrix0to1[5][8] = -1.42311521959371;
   fWeightMatrix0to1[6][8] = 0.710745579880031;
   fWeightMatrix0to1[7][8] = 0.312239347877807;
   fWeightMatrix0to1[8][8] = 1.50543020600341;
   fWeightMatrix0to1[9][8] = -1.48008296446993;
   fWeightMatrix0to1[10][8] = 0.415986483181238;
   fWeightMatrix0to1[11][8] = 1.08061213054272;
   fWeightMatrix0to1[12][8] = 1.11274660634592;
   fWeightMatrix0to1[13][8] = -0.124707286527833;
   fWeightMatrix0to1[14][8] = -0.797100419939811;
   fWeightMatrix0to1[15][8] = -0.190189475917874;
   fWeightMatrix0to1[0][9] = -0.644718668442136;
   fWeightMatrix0to1[1][9] = 2.34024501632293;
   fWeightMatrix0to1[2][9] = 3.7090296575445;
   fWeightMatrix0to1[3][9] = 0.0839457153195072;
   fWeightMatrix0to1[4][9] = -0.0314297333946075;
   fWeightMatrix0to1[5][9] = 0.322510519314138;
   fWeightMatrix0to1[6][9] = -3.38458887072979;
   fWeightMatrix0to1[7][9] = -0.497430422070211;
   fWeightMatrix0to1[8][9] = 2.19881780369974;
   fWeightMatrix0to1[9][9] = -0.713305933206278;
   fWeightMatrix0to1[10][9] = -0.17985675628972;
   fWeightMatrix0to1[11][9] = 0.503537916681924;
   fWeightMatrix0to1[12][9] = 1.59487848542593;
   fWeightMatrix0to1[13][9] = -0.210286546282419;
   fWeightMatrix0to1[14][9] = 0.76579969966293;
   fWeightMatrix0to1[15][9] = -1.78591459883765;
   fWeightMatrix0to1[0][10] = 0.899060700981463;
   fWeightMatrix0to1[1][10] = 0.59098307758172;
   fWeightMatrix0to1[2][10] = 0.558324297392175;
   fWeightMatrix0to1[3][10] = 0.92035771116091;
   fWeightMatrix0to1[4][10] = 1.26728799336926;
   fWeightMatrix0to1[5][10] = -0.412804793905687;
   fWeightMatrix0to1[6][10] = -1.23866585831499;
   fWeightMatrix0to1[7][10] = -0.268001304511868;
   fWeightMatrix0to1[8][10] = 0.0334258665927301;
   fWeightMatrix0to1[9][10] = -0.682781084820012;
   fWeightMatrix0to1[10][10] = 1.87236308524656;
   fWeightMatrix0to1[11][10] = 0.896181795092127;
   fWeightMatrix0to1[12][10] = 0.191819062438651;
   fWeightMatrix0to1[13][10] = 0.596573739031524;
   fWeightMatrix0to1[14][10] = 1.913878507681;
   fWeightMatrix0to1[15][10] = -1.61729420967043;
   fWeightMatrix0to1[0][11] = -1.99442970708381;
   fWeightMatrix0to1[1][11] = -1.96803783543489;
   fWeightMatrix0to1[2][11] = -1.55069615905884;
   fWeightMatrix0to1[3][11] = -2.18516855649055;
   fWeightMatrix0to1[4][11] = -1.87203107719233;
   fWeightMatrix0to1[5][11] = 0.498942451585742;
   fWeightMatrix0to1[6][11] = 5.5292104677615;
   fWeightMatrix0to1[7][11] = 1.33193341621087;
   fWeightMatrix0to1[8][11] = -1.47879249490573;
   fWeightMatrix0to1[9][11] = -0.0335591320594865;
   fWeightMatrix0to1[10][11] = -1.00214946828357;
   fWeightMatrix0to1[11][11] = 0.201890332598178;
   fWeightMatrix0to1[12][11] = -2.12416067994119;
   fWeightMatrix0to1[13][11] = 1.10650492086913;
   fWeightMatrix0to1[14][11] = -2.16866132838154;
   fWeightMatrix0to1[15][11] = 1.63484153425189;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.149144256967381;
   fWeightMatrix1to2[0][1] = -0.261962711739791;
   fWeightMatrix1to2[0][2] = 0.161898929977434;
   fWeightMatrix1to2[0][3] = 0.0134669092488616;
   fWeightMatrix1to2[0][4] = 0.00368103575302657;
   fWeightMatrix1to2[0][5] = -0.000530706908164508;
   fWeightMatrix1to2[0][6] = -0.401897296298281;
   fWeightMatrix1to2[0][7] = -0.040496089701005;
   fWeightMatrix1to2[0][8] = -0.011403660363655;
   fWeightMatrix1to2[0][9] = 5.85367943857026e-05;
   fWeightMatrix1to2[0][10] = -0.0141392932206556;
   fWeightMatrix1to2[0][11] = -0.0134877395766117;
   fWeightMatrix1to2[0][12] = 0.0701188169695375;
   fWeightMatrix1to2[0][13] = 0.00238275586428233;
   fWeightMatrix1to2[0][14] = 0.128524593704816;
   fWeightMatrix1to2[0][15] = 0.0262777869502239;
   fWeightMatrix1to2[0][16] = 0.341671618329932;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0.0704806447029;
   fMax_1[0][0] = 3.17232131958;
   fMin_1[1][0] = 0.0706459358335;
   fMax_1[1][0] = 3.29987287521;
   fMin_1[2][0] = 0.0704806447029;
   fMax_1[2][0] = 3.29987287521;
   fMin_1[0][1] = 0.40469455719;
   fMax_1[0][1] = 4.96937084198;
   fMin_1[1][1] = 0.383513450623;
   fMax_1[1][1] = 4.99538564682;
   fMin_1[2][1] = 0.383513450623;
   fMax_1[2][1] = 4.99538564682;
   fMin_1[0][2] = 0.418494284153;
   fMax_1[0][2] = 4.80815696716;
   fMin_1[1][2] = 0.400014162064;
   fMax_1[1][2] = 4.98474645615;
   fMin_1[2][2] = 0.400014162064;
   fMax_1[2][2] = 4.98474645615;
   fMin_1[0][3] = 0.298414796591;
   fMax_1[0][3] = 5.8733496666;
   fMin_1[1][3] = 0.00575727969408;
   fMax_1[1][3] = 5.99961948395;
   fMin_1[2][3] = 0.00575727969408;
   fMax_1[2][3] = 5.99961948395;
   fMin_1[0][4] = 0.418494284153;
   fMax_1[0][4] = 3.19977164268;
   fMin_1[1][4] = 0.400001376867;
   fMax_1[1][4] = 3.19892525673;
   fMin_1[2][4] = 0.400001376867;
   fMax_1[2][4] = 3.19977164268;
   fMin_1[0][5] = 0.0128750484437;
   fMax_1[0][5] = 3.14142918587;
   fMin_1[1][5] = 1.97242206923e-05;
   fMax_1[1][5] = 3.1415886879;
   fMin_1[2][5] = 1.97242206923e-05;
   fMax_1[2][5] = 3.1415886879;
   fMin_1[0][6] = 5.03305721283;
   fMax_1[0][6] = 92.9765930176;
   fMin_1[1][6] = 5.00372505188;
   fMax_1[1][6] = 99.99949646;
   fMin_1[2][6] = 5.00372505188;
   fMax_1[2][6] = 99.99949646;
   fMin_1[0][7] = 22.5504970551;
   fMax_1[0][7] = 695.586486816;
   fMin_1[1][7] = 22.2296066284;
   fMax_1[1][7] = 699.396728516;
   fMin_1[2][7] = 22.2296066284;
   fMax_1[2][7] = 699.396728516;
   fMin_1[0][8] = 0;
   fMax_1[0][8] = 249.004089355;
   fMin_1[1][8] = 0;
   fMax_1[1][8] = 249.991043091;
   fMin_1[2][8] = 0;
   fMax_1[2][8] = 249.991043091;
   fMin_1[0][9] = 42.3850440979;
   fMax_1[0][9] = 398.096343994;
   fMin_1[1][9] = 24.572063446;
   fMax_1[1][9] = 399.818786621;
   fMin_1[2][9] = 24.572063446;
   fMax_1[2][9] = 399.818786621;
   fMin_1[0][10] = 3.84883117676;
   fMax_1[0][10] = 299.945465088;
   fMin_1[1][10] = 0.326862245798;
   fMax_1[1][10] = 299.8175354;
   fMin_1[2][10] = 0.326862245798;
   fMax_1[2][10] = 299.945465088;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
